<?php 
//Export Module 'blr_stations' Date: 13-06-2017z
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('blr_stations', 'BLR Stations','blr_stations','blr_stations, permissionnaires, ref_ville','blr_stations',NULL,'0', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'blr_stations' </li>";}
  //Task 'blr_stations' 'BLR Stations'
<<<<<<< HEAD
  if(!$result_task_117 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('blr_stations', $result_insert_modul, 'blr_stations','blr_stations', '1', 'BLR Stations', 'blr', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'BLR Stations' </li>";}
      // Action Task 117 - 'BLR Stations'
      if(!$result_action_150 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_117, 'a191a2768a0bdf0dc919b7c910122881', 'BLR Stations', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'BLR Stations' </li>";}
      // Action Task 117 - 'Modifier Station'
      if(!$result_action_151 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_117, 'd8303c8ab796472638c98d83dfda83e2', 'Modifier Station', '".'<li><a href="#" class="this_url" data="%id%" rel="editblr_stations"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier Station</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Station' </li>";}
      // Action Task 117 - 'Supprimer Station'
      if(!$result_action_152 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_117, 'e2301b8b334011305f493a95e4f69c90', 'Supprimer Station', '".'<li><a href="#" class="this_exec" data="%id%" rel="deleteblr_stations"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Supprimer Station</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Station' </li>";}
      // Action Task 117 - 'Liste clients'
      if(!$result_action_153 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_117, '162166ae8b76398166b2c4425ceff3d3', 'Liste clients', '".'<li><a href="#" class="this_url" data="%id%" rel="blr_clients"  >
<i class="ace-icon fa fa-cogs bigger-100"></i> Liste clients</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste clients' </li>";}
      // Action Task 117 - 'Validation station'
      if(!$result_action_154 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_117, 'eddfb2225ea88e469526a2b84d019993', 'Validation station', '".'<li><a href="#" class="this_exec" data="%id%" rel="validblr_stations"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Validation station</a></li>'."', '0', '[-1-]', '0', '1', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Validation station' </li>";}
      // Action Task 117 - 'Liste des clients'
      if(!$result_action_155 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_117, '6b8043b600b88dd9c28595ff0748abf1', 'Liste des clients', '".'<li><a href="#" class="this_url" data="%id%" rel="blr_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Liste des clients</a></li>'."', '0', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste des clients' </li>";}
=======
  if(!$result_task_307 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('blr_stations', $result_insert_modul, 'blr_stations','blr_stations', '1', 'BLR Stations', 'blr', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'BLR Stations' </li>";}
      // Action Task 307 - 'BLR Stations'
      if(!$result_action_458 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_307, '89002431b276e5109323503cee2952ea', 'BLR Stations', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'BLR Stations' </li>";}
      // Action Task 307 - 'Modifier Station BLR'
      if(!$result_action_459 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_307, 'd6fd8b14c33cb4da2b5c56379716ab11', 'Modifier Station BLR', '".'<li><a href="#" class="this_url" data="%id%" rel="editblr_stations"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier Station BLR</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Station BLR' </li>";}
      // Action Task 307 - 'Liste clients BLR'
      if(!$result_action_460 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_307, '55107ffe5bf4bbcdf5c0f20e3d7549fa', 'Liste clients BLR', '".'<li><a href="#" class="this_url" data="%id%" rel="blr_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Liste clients BLR</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste clients BLR' </li>";}
      // Action Task 307 - 'Validation station BLR'
      if(!$result_action_461 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_307, '7656252b88ae0b1894c31648ef25d8d4', 'Validation station BLR', '".'<li><a href="#" class="this_exec" data="%id%" rel="validblr_stations"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Validation station BLR</a></li>'."', '0', '[-1-]', '0', '1', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Validation station BLR' </li>";}
      // Action Task 307 - 'Liste des clients BLR'
      if(!$result_action_462 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_307, '2d996dac5135fe8c0168ab83b4041600', 'Liste des clients BLR', '".'<li><a href="#" class="this_url" data="%id%" rel="blr_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Liste des clients BLR</a></li>'."', '0', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste des clients BLR' </li>";}
      // Action Task 307 - 'Détails station BLR'
      if(!$result_action_463 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_307, '01e2199e1d5cc932e6ec171e0d3e8cc4', 'Détails station BLR', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsblr"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Détails station BLR</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails station BLR' </li>";}
>>>>>>> origin/pre_deploy
  //Task 'addblr_stations' 'Ajouter Station'
  if(!$result_task_308 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addblr_stations', $result_insert_modul, 'addblr_stations','blr_stations', '1', 'Ajouter Station', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Station' </li>";}
      // Action Task 308 - 'Ajouter Station'
      if(!$result_action_464 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_308, '85dd8eec66cbca2dea98736a7d2c30fe', 'Ajouter Station', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Station' </li>";}
  //Task 'editblr_stations' 'Modifier Station'
<<<<<<< HEAD
  if(!$result_task_119 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editblr_stations', $result_insert_modul, 'editblr_stations','blr_stations', '1', 'Modifier Station', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Station' </li>";}
      // Action Task 119 - 'Modifier Station'
      if(!$result_action_157 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_119, '346cb5afdb12448749d5ba9052f58e8f', 'Modifier Station', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Station' </li>";}
  //Task 'deleteblr_stations' 'Supprimer Station'
  if(!$result_task_120 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteblr_stations', $result_insert_modul, 'deleteblr_stations','blr_stations', '1', 'Supprimer Station', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Station' </li>";}
      // Action Task 120 - 'Supprimer Station'
      if(!$result_action_158 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_120, '36f60650b0810e415b1a8a481e36c4e5', 'Supprimer Station', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Station' </li>";}
  //Task 'blr_clients' 'BLR Clients'
  if(!$result_task_121 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('blr_clients', $result_insert_modul, 'blr_clients','blr_stations', '1', 'BLR Clients', 'envelope', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'BLR Clients' </li>";}
      // Action Task 121 - 'BLR Clients'
      if(!$result_action_159 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_121, '6bfedc03abc106e249aa349d632240ea', 'BLR Clients', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'BLR Clients' </li>";}
      // Action Task 121 - 'Modifier BLR Client'
      if(!$result_action_160 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_121, '12cebf41f6459ebee3399f55ba6415a6', 'Modifier BLR Client', '".'<li><a href="#" class="this_url" data="%id%" rel="editblr_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier BLR Client</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier BLR Client' </li>";}
      // Action Task 121 - 'Validation client'
      if(!$result_action_161 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_121, '8269a897ed32f0ea0f1bc5fae676be0f', 'Validation client', '".'<li><a href="#" class="this_exec" data="%id%" rel="validblr_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Validation client</a></li>'."', '0', '[-1-]', '0', '1', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Validation client' </li>";}
=======
  if(!$result_task_309 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editblr_stations', $result_insert_modul, 'editblr_stations','blr_stations', '1', 'Modifier Station', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Station' </li>";}
      // Action Task 309 - 'Modifier Station'
      if(!$result_action_465 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_309, '346cb5afdb12448749d5ba9052f58e8f', 'Modifier Station', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Station' </li>";}
  //Task 'blr_clients' 'BLR Clients'
  if(!$result_task_310 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('blr_clients', $result_insert_modul, 'blr_clients','blr_stations', '1', 'BLR Clients', 'envelope', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'BLR Clients' </li>";}
      // Action Task 310 - 'BLR Clients'
      if(!$result_action_466 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_310, '94ee452d9718d8681273c58aa214a62d', 'BLR Clients', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'BLR Clients' </li>";}
      // Action Task 310 - 'Modifier client BLR'
      if(!$result_action_467 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_310, 'a29583a228f78b6eb6575c05da820cda', 'Modifier client BLR', '".'<li><a href="#" class="this_url" data="%id%" rel="editblr_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier client BLR</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier client BLR' </li>";}
      // Action Task 310 - 'Validation client BLR'
      if(!$result_action_468 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_310, '74574f61001d4b1aabf00448e737ebcf', 'Validation client BLR', '".'<li><a href="#" class="this_exec" data="%id%" rel="validblr_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Validation client BLR</a></li>'."', '0', '[-1-]', '0', '1', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Validation client BLR' </li>";}
      // Action Task 310 - 'Détails client BLR'
      if(!$result_action_469 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_310, 'd456a4883d52b9cb9c4587a3ad8e3c8f', 'Détails client BLR', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsblr_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Détails client BLR</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails client BLR' </li>";}
>>>>>>> origin/pre_deploy
  //Task 'addblr_clients' 'Ajouter BLR Client'
  if(!$result_task_311 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addblr_clients', $result_insert_modul, 'addblr_clients','blr_stations', '1', 'Ajouter BLR Client', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter BLR Client' </li>";}
      // Action Task 311 - 'Ajouter BLR Client'
      if(!$result_action_470 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_311, 'b51ae23cbcbccb606d8ff16eb4f09886', 'Ajouter BLR Client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter BLR Client' </li>";}
  //Task 'editblr_clients' 'Modifier BLR Client'
<<<<<<< HEAD
  if(!$result_task_123 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editblr_clients', $result_insert_modul, 'editblr_clients','blr_stations', '1', 'Modifier BLR Client', 'cogs', '1', '0', '0','form', 'null')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier BLR Client' </li>";}
      // Action Task 123 - 'Modifier BLR Client'
      if(!$result_action_163 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_123, '0f893cbf847755649a6a22eb9e9c8281', 'Modifier BLR Client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier BLR Client' </li>";}
=======
  if(!$result_task_312 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editblr_clients', $result_insert_modul, 'editblr_clients','blr_stations', '1', 'Modifier BLR Client', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier BLR Client' </li>";}
      // Action Task 312 - 'Modifier BLR Client'
      if(!$result_action_471 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_312, '0f893cbf847755649a6a22eb9e9c8281', 'Modifier BLR Client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier BLR Client' </li>";}
>>>>>>> origin/pre_deploy
  //Task 'deleteblr_clients' 'Supprimer client'
  if(!$result_task_313 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteblr_clients', $result_insert_modul, 'deleteblr_clients','blr_stations', '1', 'Supprimer client', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer client' </li>";}
      // Action Task 313 - 'Supprimer client'
      if(!$result_action_472 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_313, '2e886e73ecd068f54691c045eca44fd1', 'Supprimer client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer client' </li>";}
  //Task 'validblr_stations' 'Validation station BLR'
  if(!$result_task_314 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validblr_stations', $result_insert_modul, 'validblr_stations','blr_stations', '1', 'Validation station BLR', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Validation station BLR' </li>";}
      // Action Task 314 - 'Validation station BLR'
      if(!$result_action_473 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_314, 'c00ea603b44e49999a12973fdf2c8114', 'Validation station BLR', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Validation station BLR' </li>";}
  //Task 'validblr_clients' 'Validation client BLR'
<<<<<<< HEAD
  if(!$result_task_126 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validblr_clients', $result_insert_modul, 'validblr_clients','blr_stations', '1', 'Validation client BLR', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Validation client BLR' </li>";}
      // Action Task 126 - 'Validation client BLR'
      if(!$result_action_166 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_126, '65ce707888a0affde6ceb62ba78e89e0', 'Validation client BLR', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Validation client BLR' </li>";}
=======
  if(!$result_task_315 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validblr_clients', $result_insert_modul, 'validblr_clients','blr_stations', '1', 'Validation client BLR', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Validation client BLR' </li>";}
      // Action Task 315 - 'Validation client BLR'
      if(!$result_action_474 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_315, '65ce707888a0affde6ceb62ba78e89e0', 'Validation client BLR', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Validation client BLR' </li>";}
  //Task 'detailsblr' 'Détails station BLR'
  if(!$result_task_316 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsblr', $result_insert_modul, 'detailsblr','blr_stations', '1', 'Détails station BLR', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails station BLR' </li>";}
      // Action Task 316 - 'Détails station BLR'
      if(!$result_action_475 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_316, '06bdb0df5d68902f3ede5f42dbd9ff9a', 'Détails station BLR', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails station BLR' </li>";}
  //Task 'detailsblr_clients' 'Détails client BLR'
  if(!$result_task_317 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsblr_clients', $result_insert_modul, 'detailsblr_clients','blr_stations', '1', 'Détails client BLR', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails client BLR' </li>";}
      // Action Task 317 - 'Détails client BLR'
      if(!$result_action_476 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_317, '97c4d3e8a16d1e27b5dc79c992312184', 'Détails client BLR', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails client BLR' </li>";}
>>>>>>> origin/pre_deploy
