<?php 
//Export Module 'commerciale' Date: 26-01-2018
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('commerciale', 'Commerciale','commerciale/main','commerciaux','commerciale',NULL,'0', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'commerciale' </li>";}
  //Task 'commerciale' 'Commerciale'
  if(!$result_task_742 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('commerciale', $result_insert_modul, 'commerciale','commerciale/main', '1', 'Commerciale', 'lock', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Commerciale' </li>";}
      // Action Task 742 - 'Commerciale'
      if(!$result_action_1175 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_742, '179906c1666d7e9a7b4d1f52a1f84ec0', 'Commerciale','commerciale', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Commerciale' </li>";}
      // Action Task 742 - 'Modifier Commerciale'
      if(!$result_action_1180 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_742, '3e2b9ccbb5837f42342934bd9ba3aa49', 'Modifier Commerciale','editcommerciale', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editcommerciale"  ><i class="ace-icon fa fa-pencil-square-o bigger-100"></i> Modifier Commerciale</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Commerciale' </li>";}
      // Action Task 742 - 'Valider commerciale'
      if(!$result_action_1181 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_742, '1f4be058271867b2a398678fb0e49750', 'Valider commerciale','validcommerciale', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validcommerciale"  ><i class="ace-icon fa fa-check-square-o bigger-100"></i> Valider commerciale</a></li>'."', '0', '[-1-]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider commerciale' </li>";}
      // Action Task 742 - 'Détails commerciale'
      if(!$result_action_1183 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_742, '3980ecadef51319f03ae82b686e97dc4', 'Détails commerciale','detailscommerciale', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscommerciale"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails commerciale</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commerciale' </li>";}
      // Action Task 742 - 'Détails Commerciale'
      if(!$result_action_1184 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_742, 'b0abfcf29eaacb4bad1a88a663331182', 'Détails Commerciale','detailscommerciale', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscommerciale"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails Commerciale</a></li>'."', '0', '[-1-2-]', '1', '0', 'Commerciale Validé','success','".'<span class="label label-sm label-success">Commerciale Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Commerciale' </li>";}
      // Action Task 742 - 'Désactiver commerciale'
      if(!$result_action_1185 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_742, '923af4f85ccb0b69f7920e557ed03768', 'Désactiver commerciale','validcommerciale', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validcommerciale"  ><i class="ace-icon fa fa-unlock bigger-100"></i> Désactiver commerciale</a></li>'."', '0', '[-1-]', '1', '0', 'Commerciale Validé','success','".'<span class="label label-sm label-success">Commerciale Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver commerciale' </li>";}
      // Action Task 742 - 'Commissions'
      if(!$result_action_1191 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_742, 'f2e2a34f24f845f58e3af9e1baf3d34c', 'Commissions','commissions', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="commissions"  ><i class="ace-icon fa fa-signal bigger-100"></i> Commissions</a></li>'."', '0', '[-1-5-]', '1', '0', 'Commerciale Validé','success','".'<span class="label label-sm label-success">Commerciale Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Commissions' </li>";}
  //Task 'addcommerciale' 'Ajouter commerciale '
  if(!$result_task_743 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addcommerciale', $result_insert_modul, 'addcommerciale','commerciale/main', '1', 'Ajouter commerciale ', 'cogs', '1', '0', '0','formadd', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter commerciale ' </li>";}
      // Action Task 743 - 'Ajouter commerciale'
      if(!$result_action_1176 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_743, '03b0a2e252d4c53940ca1817d9083f0a', 'Ajouter commerciale','addcommerciale', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter commerciale' </li>";}
  //Task 'editcommerciale' 'Modifier Commerciale'
  if(!$result_task_744 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editcommerciale', $result_insert_modul, 'editcommerciale','commerciale/main', '1', 'Modifier Commerciale', 'cogs', '1', '0', '0','formedit', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Commerciale' </li>";}
      // Action Task 744 - 'Modifier Commerciale'
      if(!$result_action_1177 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_744, 'ab2d80f7396b53342b8455293be7c892', 'Modifier Commerciale','editcommerciale', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Commerciale' </li>";}
  //Task 'validcommerciale' 'Valider commerciale'
  if(!$result_task_745 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validcommerciale', $result_insert_modul, 'validcommerciale','commerciale/main', '1', 'Valider commerciale', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider commerciale' </li>";}
      // Action Task 745 - 'Valider commerciale'
      if(!$result_action_1178 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_745, 'b9de9130d6ec79fa1981fd935590d9c7', 'Valider commerciale','validcommerciale', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider commerciale' </li>";}
  //Task 'deletecommerciale' 'Supprimer commerciale'
  if(!$result_task_746 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletecommerciale', $result_insert_modul, 'deletecommerciale','commerciale/main', '1', 'Supprimer commerciale', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer commerciale' </li>";}
      // Action Task 746 - 'Supprimer commerciale'
      if(!$result_action_1179 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_746, '97f27dfbac6c8d8f785585ca54b1b8d4', 'Supprimer commerciale','deletecommerciale', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer commerciale' </li>";}
  //Task 'detailscommerciale' 'Détails commerciale'
  if(!$result_task_747 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailscommerciale', $result_insert_modul, 'detailscommerciale','commerciale/main', '1', 'Détails commerciale', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails commerciale' </li>";}
      // Action Task 747 - 'Détails commerciale'
      if(!$result_action_1182 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_747, '250db5ee83c4c30061b983a26fb91ba9', 'Détails commerciale','detailscommerciale', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commerciale' </li>";}
  //Task 'commissions' 'Commissions'
  if(!$result_task_750 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('commissions', $result_insert_modul, 'commissions','commerciale/main', '1', 'Commissions', 'signal', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Commissions' </li>";}
      // Action Task 750 - 'Commissions'
      if(!$result_action_1190 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_750, '738a72cd47c2630b73be1a92f8117525', 'Commissions','commissions', NULL, '".NULL."', '1', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Commissions' </li>";}
      // Action Task 750 - 'Payer Commission   '
      if(!$result_action_1193 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_750, '98f53da207662a231a3ff2377af1f03b', 'Payer Commission   ','paycommission', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="paycommission"  ><i class="ace-icon fa fa-euro bigger-100"></i> Payer Commission   </a></li>'."', '0', '[-1-5-]', '1', '0', 'Attente Payement','success','".'<span class="label label-sm label-success">Attente Payement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Payer Commission   ' </li>";}
      // Action Task 750 - 'Payer Commission'
      if(!$result_action_1194 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_750, 'a51a876db71f5da2d9ef1ac6e4929543', 'Payer Commission','paycommission', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="paycommission"  ><i class="ace-icon fa fa-euro bigger-100"></i> Payer Commission</a></li>'."', '0', '[-1-5-]', '2', '0', 'Payé Partiellement','info','".'<span class="label label-sm label-info">Payé Partiellement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Payer Commission' </li>";}
      // Action Task 750 - 'Modifier commission'
      if(!$result_action_1200 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_750, 'd4327189d68e6aae34e614fbd5ecc9b8', 'Modifier commission','editcommissions', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editcommissions"  ><i class="ace-icon fa fa-pencil-square-o bigger-100"></i> Modifier commission</a></li>'."', '0', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier commission' </li>";}
      // Action Task 750 - 'Valider Commission'
      if(!$result_action_1202 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_750, '31cb75b08edc1219b940b8d9c3f74dec', 'Valider Commission','validcommission', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validcommission"  ><i class="ace-icon fa fa-check-square-o bigger-100"></i> Valider Commission</a></li>'."', '0', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Commission' </li>";}
      // Action Task 750 - 'Détails commission'
      if(!$result_action_1204 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_750, '7b78301b1dfe281483854f0e23102bb1', 'Détails commission','detailscommission', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscommission"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails commission</a></li>'."', '0', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commission' </li>";}
      // Action Task 750 - 'Détails commission'
      if(!$result_action_1205 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_750, '9d48b04e7eb927ba243a8a52eed24d66', 'Détails commission','detailscommission', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscommission"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails commission</a></li>'."', '0', '[-1-5-]', '1', '0', 'Attente Payement','success','".'<span class="label label-sm label-success">Attente Payement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commission' </li>";}
      // Action Task 750 - 'Détails commission'
      if(!$result_action_1206 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_750, 'f9ecac816e2e67543667014a6e2bd01b', 'Détails commission','detailscommission', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscommission"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails commission</a></li>'."', '0', '[-1-5-]', '2', '0', 'Payé Partiellement','info','".'<span class="label label-sm label-info">Payé Partiellement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commission' </li>";}
      // Action Task 750 - 'Détails commission'
      if(!$result_action_1207 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_750, 'a824d5f254bea8798c2c719fba1d4f3b', 'Détails commission','detailscommission', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscommission"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails commission</a></li>'."', '0', '[-1-5-]', '3', '0', 'Commission Payée','danger','".'<span class="label label-sm label-danger">Commission Payée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commission' </li>";}
  //Task 'paycommission' 'Payer Commission'
  if(!$result_task_751 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('paycommission', $result_insert_modul, 'paycommission','commerciale/main', '1', 'Payer Commission', 'euro', '1', '0', '0','formpers', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Payer Commission' </li>";}
      // Action Task 751 - 'Payer Commission'
      if(!$result_action_1192 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_751, '5adc1562f2a8f48f30492133e6d82d48', 'Payer Commission','paycommission', NULL, '".NULL."', '1', '[-1-5-]', '0', '0', 'Attente Payement','info','".'<span class="label label-sm label-info">Attente Payement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Payer Commission' </li>";}
  //Task 'addcommissions' 'Ajouter commission'
  if(!$result_task_752 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addcommissions', $result_insert_modul, 'addcommissions','commerciale/main', '1', 'Ajouter commission', 'cogs', '1', '0', '0','formadd', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter commission' </li>";}
      // Action Task 752 - 'Ajouter commission'
      if(!$result_action_1198 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_752, 'd374ca19122a0b3f66f67bdbf74efc60', 'Ajouter commission','addcommissions', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter commission' </li>";}
  //Task 'editcommissions' 'Modifier commission'
  if(!$result_task_753 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editcommissions', $result_insert_modul, 'editcommissions','commerciale/main', '1', 'Modifier commission', 'cogs', '1', '0', '0','formedit', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier commission' </li>";}
      // Action Task 753 - 'Modifier commission'
      if(!$result_action_1199 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_753, '25bbc454f35643c1af3371fd02cc9195', 'Modifier commission','editcommissions', NULL, '".NULL."', '1', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier commission' </li>";}
  //Task 'validcommission' 'Valider Commission'
  if(!$result_task_754 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validcommission', $result_insert_modul, 'validcommission','commerciale/main', '1', 'Valider Commission', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Commission' </li>";}
      // Action Task 754 - 'Valider Commission'
      if(!$result_action_1201 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_754, 'c35c2ca29c5083910a20996ccd465a48', 'Valider Commission','validcommission', NULL, '".NULL."', '1', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Commission' </li>";}
  //Task 'detailscommission' 'Détails commission'
  if(!$result_task_755 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailscommission', $result_insert_modul, 'detailscommission','commerciale/main', '1', 'Détails commission', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails commission' </li>";}
      // Action Task 755 - 'Détails commission'
      if(!$result_action_1203 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_755, '418e3a3591fc54086c56b385077bfb71', 'Détails commission','detailscommission', NULL, '".NULL."', '1', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commission' </li>";}
