<?php 
//Export Module 'commerciale' Date: 29-06-2018
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('commerciale', 'Commerciale','commerciale/main','commerciaux','commerciale',NULL,'0', '0', '[-1-3-5-7-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'commerciale' </li>";}
  //Task 'commerciale' 'Commerciale'
  if(!$result_task_752 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('commerciale', $result_insert_modul, 'commerciale','commerciale/main', '1', 'Commerciale', 'lock', '1', '0', '0','list', '[-1-3-5-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Commerciale' </li>";}
      // Action Task 752 - 'Commerciale'
      if(!$result_action_1197 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_752, '179906c1666d7e9a7b4d1f52a1f84ec0', 'Commerciale','commerciale', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Commerciale' </li>";}
      // Action Task 752 - 'Modifier Commerciale'
      if(!$result_action_1198 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_752, '3e2b9ccbb5837f42342934bd9ba3aa49', 'Modifier Commerciale','editcommerciale', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editcommerciale"  ><i class="ace-icon fa fa-pencil-square-o bigger-100"></i> Modifier Commerciale</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Commerciale' </li>";}
      // Action Task 752 - 'Valider commerciale'
      if(!$result_action_1199 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_752, '1f4be058271867b2a398678fb0e49750', 'Valider commerciale','validcommerciale', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validcommerciale"  ><i class="ace-icon fa fa-check-square-o bigger-100"></i> Valider commerciale</a></li>'."', '0', '[-1-]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider commerciale' </li>";}
      // Action Task 752 - 'Détails commerciale'
      if(!$result_action_1200 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_752, '3980ecadef51319f03ae82b686e97dc4', 'Détails commerciale','detailscommerciale', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscommerciale"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails commerciale</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commerciale' </li>";}
      // Action Task 752 - 'Détails Commerciale'
      if(!$result_action_1201 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_752, 'b0abfcf29eaacb4bad1a88a663331182', 'Détails Commerciale','detailscommerciale', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscommerciale"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails Commerciale</a></li>'."', '0', '[-1-2-]', '1', '0', 'Commerciale Validé','success','".'<span class="label label-sm label-success">Commerciale Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Commerciale' </li>";}
      // Action Task 752 - 'Désactiver commerciale'
      if(!$result_action_1202 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_752, '923af4f85ccb0b69f7920e557ed03768', 'Désactiver commerciale','validcommerciale', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validcommerciale"  ><i class="ace-icon fa fa-unlock bigger-100"></i> Désactiver commerciale</a></li>'."', '0', '[-1-]', '1', '0', 'Commerciale Validé','success','".'<span class="label label-sm label-success">Commerciale Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver commerciale' </li>";}
      // Action Task 752 - 'Commissions'
      if(!$result_action_1203 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_752, 'f2e2a34f24f845f58e3af9e1baf3d34c', 'Commissions','commissions', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="commissions"  ><i class="ace-icon fa fa-signal bigger-100"></i> Commissions</a></li>'."', '0', '[-1-5-]', '1', '0', 'Commerciale Validé','success','".'<span class="label label-sm label-success">Commerciale Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Commissions' </li>";}
  //Task 'addcommerciale' 'Ajouter commerciale '
  if(!$result_task_753 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addcommerciale', $result_insert_modul, 'addcommerciale','commerciale/main', '1', 'Ajouter commerciale ', 'cogs', '1', '0', '0','formadd', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter commerciale ' </li>";}
      // Action Task 753 - 'Ajouter commerciale'
      if(!$result_action_1204 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_753, '03b0a2e252d4c53940ca1817d9083f0a', 'Ajouter commerciale','addcommerciale', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter commerciale' </li>";}
  //Task 'editcommerciale' 'Modifier Commerciale'
  if(!$result_task_754 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editcommerciale', $result_insert_modul, 'editcommerciale','commerciale/main', '1', 'Modifier Commerciale', 'cogs', '1', '0', '0','formedit', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Commerciale' </li>";}
      // Action Task 754 - 'Modifier Commerciale'
      if(!$result_action_1205 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_754, 'ab2d80f7396b53342b8455293be7c892', 'Modifier Commerciale','editcommerciale', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Commerciale' </li>";}
  //Task 'validcommerciale' 'Valider commerciale'
  if(!$result_task_755 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validcommerciale', $result_insert_modul, 'validcommerciale','commerciale/main', '1', 'Valider commerciale', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider commerciale' </li>";}
      // Action Task 755 - 'Valider commerciale'
      if(!$result_action_1206 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_755, 'b9de9130d6ec79fa1981fd935590d9c7', 'Valider commerciale','validcommerciale', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider commerciale' </li>";}
  //Task 'deletecommerciale' 'Supprimer commerciale'
  if(!$result_task_756 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletecommerciale', $result_insert_modul, 'deletecommerciale','commerciale/main', '1', 'Supprimer commerciale', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer commerciale' </li>";}
      // Action Task 756 - 'Supprimer commerciale'
      if(!$result_action_1207 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_756, '97f27dfbac6c8d8f785585ca54b1b8d4', 'Supprimer commerciale','deletecommerciale', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer commerciale' </li>";}
  //Task 'detailscommerciale' 'Détails commerciale'
  if(!$result_task_757 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailscommerciale', $result_insert_modul, 'detailscommerciale','commerciale/main', '1', 'Détails commerciale', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails commerciale' </li>";}
      // Action Task 757 - 'Détails commerciale'
      if(!$result_action_1208 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_757, '250db5ee83c4c30061b983a26fb91ba9', 'Détails commerciale','detailscommerciale', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commerciale' </li>";}
  //Task 'commissions' 'Commissions'
  if(!$result_task_758 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('commissions', $result_insert_modul, 'commissions','commerciale/main', '1', 'Commissions', 'signal', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Commissions' </li>";}
      // Action Task 758 - 'Commissions'
      if(!$result_action_1209 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_758, '738a72cd47c2630b73be1a92f8117525', 'Commissions','commissions', NULL, '".NULL."', '1', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Commissions' </li>";}
      // Action Task 758 - 'Modifier commission'
      if(!$result_action_1212 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_758, 'd4327189d68e6aae34e614fbd5ecc9b8', 'Modifier commission','editcommissions', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editcommissions"  ><i class="ace-icon fa fa-pencil-square-o bigger-100"></i> Modifier commission</a></li>'."', '0', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier commission' </li>";}
      // Action Task 758 - 'Valider Commission'
      if(!$result_action_1213 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_758, '31cb75b08edc1219b940b8d9c3f74dec', 'Valider Commission','validcommission', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validcommission"  ><i class="ace-icon fa fa-check-square-o bigger-100"></i> Valider Commission</a></li>'."', '0', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Commission' </li>";}
      // Action Task 758 - 'Détails commission'
      if(!$result_action_1214 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_758, '7b78301b1dfe281483854f0e23102bb1', 'Détails commission','detailscommission', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscommission"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails commission</a></li>'."', '0', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commission' </li>";}
      // Action Task 758 - 'Détails commission'
      if(!$result_action_1215 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_758, '9d48b04e7eb927ba243a8a52eed24d66', 'Détails commission','detailscommission', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscommission"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails commission</a></li>'."', '0', '[-1-5-]', '1', '0', 'Attente Paiement','success','".'<span class="label label-sm label-success">Attente Paiement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commission' </li>";}
      // Action Task 758 - 'Détails commission'
      if(!$result_action_1216 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_758, 'f9ecac816e2e67543667014a6e2bd01b', 'Détails commission','detailscommission', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscommission"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails commission</a></li>'."', '0', '[-1-5-]', '2', '0', 'Payé Partiellement','info','".'<span class="label label-sm label-info">Payé Partiellement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commission' </li>";}
      // Action Task 758 - 'Détails commission'
      if(!$result_action_1217 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_758, 'a824d5f254bea8798c2c719fba1d4f3b', 'Détails commission','detailscommission', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscommission"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails commission</a></li>'."', '0', '[-1-5-]', '3', '0', 'Commission Payée','danger','".'<span class="label label-sm label-danger">Commission Payée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commission' </li>";}
      // Action Task 758 - 'Paiements'
      if(!$result_action_1431 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_758, 'ad7fe82af9edf6f5e1d8686e62249b7c', 'Paiements','paiements', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="paiements"  ><i class="ace-icon fa fa-euro bigger-100"></i> Paiements</a></li>'."', '0', '[-1-2-3-4-7-6-]', '1', '0', 'Attente Paiement','success','".'<span class="label label-sm label-success">Attente Paiement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Paiements' </li>";}
      // Action Task 758 - 'Paiements'
      if(!$result_action_1432 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_758, '0c7272e219c26b63141e833c0071d3bc', 'Paiements','paiements', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="paiements"  ><i class="ace-icon fa fa-euro bigger-100"></i> Paiements</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '2', '0', 'Payé Partiellement','info','".'<span class="label label-sm label-info">Payé Partiellement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Paiements' </li>";}
  //Task 'paycommission' 'Payer Commission'
  if(!$result_task_759 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('paycommission', $result_insert_modul, 'paycommission','commerciale/main', '1', 'Payer Commission', 'euro', '1', '0', '0','formpers', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Payer Commission' </li>";}
      // Action Task 759 - 'Payer Commission'
      if(!$result_action_1218 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_759, '5adc1562f2a8f48f30492133e6d82d48', 'Payer Commission','paycommission', NULL, '".NULL."', '1', '[-1-5-]', '0', '0', 'Attente Paiement','info','".'<span class="label label-sm label-info">Attente Paiement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Payer Commission' </li>";}
  //Task 'addcommissions' 'Ajouter commission'
  if(!$result_task_760 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addcommissions', $result_insert_modul, 'addcommissions','commerciale/main', '1', 'Ajouter commission', 'cogs', '1', '0', '0','formadd', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter commission' </li>";}
      // Action Task 760 - 'Ajouter commission'
      if(!$result_action_1219 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_760, 'd374ca19122a0b3f66f67bdbf74efc60', 'Ajouter commission','addcommissions', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter commission' </li>";}
  //Task 'editcommissions' 'Modifier commission'
  if(!$result_task_761 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editcommissions', $result_insert_modul, 'editcommissions','commerciale/main', '1', 'Modifier commission', 'cogs', '1', '0', '0','formedit', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier commission' </li>";}
      // Action Task 761 - 'Modifier commission'
      if(!$result_action_1220 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_761, '25bbc454f35643c1af3371fd02cc9195', 'Modifier commission','editcommissions', NULL, '".NULL."', '1', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier commission' </li>";}
  //Task 'validcommission' 'Valider Commission'
  if(!$result_task_762 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validcommission', $result_insert_modul, 'validcommission','commerciale/main', '1', 'Valider Commission', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Commission' </li>";}
      // Action Task 762 - 'Valider Commission'
      if(!$result_action_1221 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_762, 'c35c2ca29c5083910a20996ccd465a48', 'Valider Commission','validcommission', NULL, '".NULL."', '1', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Commission' </li>";}
  //Task 'detailscommission' 'Détails commission'
  if(!$result_task_763 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailscommission', $result_insert_modul, 'detailscommission','commerciale/main', '1', 'Détails commission', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails commission' </li>";}
      // Action Task 763 - 'Détails commission'
      if(!$result_action_1222 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_763, '418e3a3591fc54086c56b385077bfb71', 'Détails commission','detailscommission', NULL, '".NULL."', '1', '[-1-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails commission' </li>";}
  //Task 'paiements' 'Paiements'
  if(!$result_task_866 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('paiements', $result_insert_modul, 'paiements','commerciale/main', '1', 'Paiements', 'euro', '1', '0', '0','list', '[-1-3-5-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Paiements' </li>";}
      // Action Task 866 - 'Paiements'
      if(!$result_action_1430 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_866, '9d88519ac4b35c1c72e40d4183d7479e', 'Paiements','paiements', NULL, '".NULL."', '1', '[-1-3-5-4-7-6-]', '0', '0', 'Commerciale Validé','success','".'<span class="label label-sm label-success">Commerciale Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Paiements' </li>";}
      // Action Task 866 - 'Détails Paiement'
      if(!$result_action_1435 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_866, 'a1a893e54a2802719c722bc0b201ca2f', 'Détails Paiement','detailspaiements', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailspaiements"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails Paiement</a></li>'."', '0', '[-1-2-3-5-7-6-]', '0', '0', 'Attente Décharge','warning','".'<span class="label label-sm label-warning">Attente Décharge</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Paiement' </li>";}
      // Action Task 866 - 'Détails Paiement'
      if(!$result_action_1437 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_866, '77cc463f372268d3a0b41071b1d2151a', 'Détails Paiement','detailspaiements', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailspaiements"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails Paiement</a></li>'."', '0', '[-1-2-5-7-]', '1', '0', 'Paiement Effectué','success','".'<span class="label label-sm label-success">Paiement Effectué</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Paiement' </li>";}
      // Action Task 866 - 'Ajouter Décharge'
      if(!$result_action_1438 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_866, 'bee620ffe27fa9c863219f8377dea76b', 'Ajouter Décharge','adddecharge', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="adddecharge"  ><i class="ace-icon fa fa-paypal bigger-100"></i> Ajouter Décharge</a></li>'."', '0', '[-1-2-3-5-7-]', '0', '0', 'Attente Décharge','warning','".'<span class="label label-sm label-warning">Attente Décharge</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Décharge' </li>";}
  //Task 'addpaiements' 'Ajouter Paiement'
  if(!$result_task_867 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addpaiements', $result_insert_modul, 'addpaiements','commerciale/main', '1', 'Ajouter Paiement', 'euro', '1', '0', '0','formadd', '[-1-3-5-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Paiement' </li>";}
      // Action Task 867 - 'Ajouter Paiement'
      if(!$result_action_1433 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_867, 'e6cbf93fb1347eddf63387adb8dd4655', 'Ajouter Paiement','addpaiements', NULL, '".NULL."', '1', '[-1-2-3-5-7-6-]', '0', '0', 'Commerciale Validé','warning','".'<span class="label label-sm label-warning">Commerciale Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Paiement' </li>";}
  //Task 'detailspaiements' 'Détails Paiement'
  if(!$result_task_868 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailspaiements', $result_insert_modul, 'detailspaiements','commerciale/main', '1', 'Détails Paiement', 'eye', '1', '0', '0','profil', '[-1-3-5-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails Paiement' </li>";}
      // Action Task 868 - 'Détails Paiement'
      if(!$result_action_1434 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_868, 'a587909ace3d675326a7180c55b002c6', 'Détails Paiement','detailspaiements', NULL, '".NULL."', '1', '[-1-2-3-5-7-]', '0', '0', 'Commerciale Validé','success','".'<span class="label label-sm label-success">Commerciale Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Paiement' </li>";}
  //Task 'adddecharge' 'Ajouter décharge'
  if(!$result_task_869 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adddecharge', $result_insert_modul, 'adddecharge','commerciale/main', '1', 'Ajouter décharge', 'hand-o-up', '1', '0', '0','formadd', '[-1-3-5-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter décharge' </li>";}
      // Action Task 869 - 'Ajouter décharge'
      if(!$result_action_1436 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_869, 'bc317a95c45865763b4239b0727607dc', 'Ajouter décharge','adddecharge', NULL, '".NULL."', '1', '[-1-2-3-5-7-]', '0', '0', 'Attente Décharge','warning','".'<span class="label label-sm label-warning">Attente Décharge</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter décharge' </li>";}
