<?php 
//Export Module 'contrats_fournisseurs' Date: 22-09-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('contrats_fournisseurs', 'Gestion Contrats Fournisseurs','contrats_fournisseurs/main','contrats_frn','contrats_fournisseurs',NULL,'0', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'contrats_fournisseurs' </li>";}
  //Task 'contrats_fournisseurs' 'Gestion Contrats Fournisseurs'
  if(!$result_task_501 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('contrats_fournisseurs', $result_insert_modul, 'contrats_fournisseurs','contrats_fournisseurs/main', '1', 'Gestion Contrats Fournisseurs', 'book', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Contrats Fournisseurs' </li>";}
      // Action Task 501 - 'Gestion Contrats Fournisseurs'
      if(!$result_action_724 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_501, 'ec45512f34613446e7a2e367d4b4cfbd', 'Gestion Contrats Fournisseurs','contrats_fournisseurs', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Contrats Fournisseurs' </li>";}
      // Action Task 501 - 'Editer Contrat'
      if(!$result_action_744 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_501, 'e3c0d7e92dad7f8794b2415c334ec3ff', 'Editer Contrat','editcontrat_frn', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editcontrat_frn"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Editer Contrat</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Contrat' </li>";}
      // Action Task 501 - 'Valider Contrat'
      if(!$result_action_745 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_501, '9dfff1c8dcb804837200f38e95381420', 'Valider Contrat','validcontrat_frn', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validcontrat_frn"  ><i class="ace-icon fa fa-lock bigger-100"></i> Valider Contrat</a></li>'."', '0', '[-1-]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Contrat' </li>";}
      // Action Task 501 - 'Désactiver Contrat'
      if(!$result_action_746 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_501, '9fe39b496077065105a57ccd9ed05863', 'Désactiver Contrat','validcontrat_frn', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validcontrat_frn"  ><i class="ace-icon fa fa-unlock bigger-100"></i> Désactiver Contrat</a></li>'."', '0', '[-1-]', '1', '0', 'Contrat Validé','success','".'<span class="label label-sm label-success">Contrat Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver Contrat' </li>";}
      // Action Task 501 - 'Détails Contrat'
      if(!$result_action_747 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_501, '0092ad9ef69b6420a611df6859a43cda', 'Détails Contrat','detailscontrat_frn', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscontrat_frn"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails Contrat</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Contrat' </li>";}
      // Action Task 501 - 'Détails  Contrat'
      if(!$result_action_748 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_501, '6ca83d9c6c0b229446da30b60b74031a', 'Détails  Contrat','detailscontrat_frn', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailscontrat_frn"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails  Contrat</a></li>'."', '0', '[-1-]', '1', '0', 'Contrat Validé','success','".'<span class="label label-sm label-success">Contrat Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails  Contrat' </li>";}
  //Task 'addcontrat_frn' 'Ajouter Contrat'
  if(!$result_task_509 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addcontrat_frn', $result_insert_modul, 'addcontrat_frn','contrats_fournisseurs/main', '1', 'Ajouter Contrat', 'book', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Contrat' </li>";}
      // Action Task 509 - 'Ajouter Contrat'
      if(!$result_action_739 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_509, 'ded24eb817021c5a666a677b1565bc5e', 'Ajouter Contrat','addcontrat_frn', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Contrat' </li>";}
  //Task 'editcontrat_frn' 'Editer Contrat'
  if(!$result_task_510 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editcontrat_frn', $result_insert_modul, 'editcontrat_frn','contrats_fournisseurs/main', '1', 'Editer Contrat', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer Contrat' </li>";}
      // Action Task 510 - 'Editer Contrat'
      if(!$result_action_740 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_510, 'ed6b8695494bf4ed86d5fb18690b3a59', 'Editer Contrat','editcontrat_frn', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Contrat' </li>";}
  //Task 'deletecontrat_frn' 'Supprimer Contrat'
  if(!$result_task_511 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletecontrat_frn', $result_insert_modul, 'deletecontrat_frn','contrats_fournisseurs/main', '1', 'Supprimer Contrat', 'trash', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Contrat' </li>";}
      // Action Task 511 - 'Supprimer Contrat'
      if(!$result_action_741 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_511, 'b8a40913b5955209994aaa26d0e8c3d4', 'Supprimer Contrat','deletecontrat_frn', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Contrat' </li>";}
  //Task 'validcontrat_frn' 'Valider Contrat'
  if(!$result_task_512 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validcontrat_frn', $result_insert_modul, 'validcontrat_frn','contrats_fournisseurs/main', '1', 'Valider Contrat', 'lock', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Contrat' </li>";}
      // Action Task 512 - 'Valider Contrat'
      if(!$result_action_742 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_512, '5efb874e7d73ccd722df806e8275770f', 'Valider Contrat','validcontrat_frn', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Contrat' </li>";}
  //Task 'detailscontrat_frn' 'Détails Contrat'
  if(!$result_task_513 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailscontrat_frn', $result_insert_modul, 'detailscontrat_frn','contrats_fournisseurs/main', '1', 'Détails Contrat', 'eye', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails Contrat' </li>";}
      // Action Task 513 - 'Détails Contrat'
      if(!$result_action_743 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_513, '11cabf03a954a5476cc78cf221f04d78', 'Détails Contrat','detailscontrat_frn', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Contrat' </li>";}
