<?php 
//Export Module 'contrats' Date: 07-08-2018
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('contrats', 'Abonnements','vente/submodul/contrats','contrats','contrats','vente','2', '0', '[-1-2-3-5-7-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'contrats' </li>";}
  //Task 'contrats' 'Abonnements'
  if(!$result_task_784 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('contrats', $result_insert_modul, 'contrats','vente/submodul/contrats', '1', 'Abonnements', 'cloud', '1', '0', '0','list', '[-1-2-3-5-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Abonnements' </li>";}
      // Action Task 784 - 'Gestion des contrats'
      if(!$result_action_1266 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, '899d40c8f22d4f7a6f048366f1829787', 'Gestion des contrats','contrats', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion des contrats' </li>";}
      // Action Task 784 - 'Modifier  contrat'
      if(!$result_action_1267 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, '4aea0d5a7bdb0e2513897507947fc3de', 'Modifier  contrat','editcontrats', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editcontrats"  ><i class="ace-icon fa fa-pencil-square bigger-100"></i> Modifier  contrat</a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier  contrat' </li>";}
      // Action Task 784 - 'Détail  contrat'
      if(!$result_action_1268 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, 'fd2c086794632f9db4be5a5d3540ef7c', 'Détail  contrat','detailcontrat', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailcontrat"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détail  contrat</a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail  contrat' </li>";}
      // Action Task 784 - 'Valider  contrat'
      if(!$result_action_1269 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, '18c5260f189a488c59134c1d53270dae', 'Valider  contrat','validcontrat', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validcontrat"  ><i class="ace-icon fa fa-check-square-o bigger-100"></i> Valider  contrat</a></li>'."', '0', '[-1-]', '0', '1', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider  contrat' </li>";}
      // Action Task 784 - 'Détails  Contrat'
      if(!$result_action_1270 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, '2cb20ed305fb0b3408e24eddf5839522', 'Détails  Contrat','detailcontrat', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailcontrat"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails  Contrat</a></li>'."', '0', '[-1-]', '1', '0', 'Contrat Validé','success','".'<span class="label label-sm label-success">Contrat Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails  Contrat' </li>";}
      // Action Task 784 - 'Renouveler  Contrat'
      if(!$result_action_1271 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, '5576802adf8c53e87bc61e21c32c6600', 'Renouveler  Contrat','renouvelercontrats', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="renouvelercontrats"  ><i class="ace-icon fa fa-share bigger-100"></i> Renouveler  Contrat</a></li>'."', '0', '[-1-]', '2', '1', 'Attente Renouvelement','warning','".'<span class="label label-sm label-warning">Attente Renouvelement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Renouveler  Contrat' </li>";}
      // Action Task 784 - 'Détails Contrat '
      if(!$result_action_1272 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, '7ad3b47040cc543cfc0facda03d819ef', 'Détails Contrat ','detailcontrat', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailcontrat"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails Contrat </a></li>'."', '0', '[-1-]', '3', '0', 'Contrat Expiré','info','".'<span class="label label-sm label-info">Contrat Expiré</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Contrat ' </li>";}
      // Action Task 784 - ' Détails    Contrat'
      if(!$result_action_1273 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, 'b8a644acc6fbceda996f6ada4983a4e7', ' Détails    Contrat','detailcontrat', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailcontrat"  ><i class="ace-icon fa fa-eye bigger-100"></i>  Détails    Contrat</a></li>'."', '0', '[-1-]', '2', '0', 'Attente Renouvelement','warning','".'<span class="label label-sm label-warning">Attente Renouvelement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action ' Détails    Contrat' </li>";}
      // Action Task 784 - 'Détails  Contrat'
      if(!$result_action_1274 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, '1e373be70f6c8420ea7087db578247b9', 'Détails  Contrat','detailcontrat', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailcontrat"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails  Contrat</a></li>'."', '0', '[-1-]', '4', '0', 'Contrat Expiré','inverse','".'<span class="label label-sm label-inverse">Contrat Expiré</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails  Contrat' </li>";}
      // Action Task 784 - 'Renouveler Contrat'
      if(!$result_action_1275 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, '9e3a99ee2eb0e35a49950898afef47c4', 'Renouveler Contrat','renouvelercontrats', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="renouvelercontrats"  ><i class="ace-icon fa fa-share bigger-100"></i> Renouveler Contrat</a></li>'."', '0', '[-1-]', '3', '0', 'Contrat Expiré','info','".'<span class="label label-sm label-info">Contrat Expiré</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Renouveler Contrat' </li>";}
      // Action Task 784 - 'Résilier Contrat'
      if(!$result_action_1276 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, '9a7cae6e28f8265acf392c94c2c38aec', 'Résilier Contrat','resiliercontrat', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="resiliercontrat"  ><i class="ace-icon fa fa-ban bigger-100"></i> Résilier Contrat</a></li>'."', '0', '[-1-]', '1', '0', 'Contrat Validé','success','".'<span class="label label-sm label-success">Contrat Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Résilier Contrat' </li>";}
      // Action Task 784 - 'Détails   Contrat'
      if(!$result_action_1277 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, 'f0d08cdf8dec47b8e7d8a90838ac1e8b', 'Détails   Contrat','detailcontrat', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailcontrat"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails   Contrat</a></li>'."', '0', '[-1-]', '5', '0', 'Contrat Résilié','inverse','".'<span class="label label-sm label-inverse">Contrat Résilié</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails   Contrat' </li>";}
      // Action Task 784 - 'Echéances'
      if(!$result_action_1278 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, 'e5c2a867baf3429d758742a021d4795c', 'Echéances','echeances', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="echeances"  ><i class="ace-icon fa fa-exchange bigger-100"></i> Echéances</a></li>'."', '0', '[-1-]', '1', '0', 'Contrat Validé','success','".'<span class="label label-sm label-success">Contrat Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Echéances' </li>";}
      // Action Task 784 - 'Echéances'
      if(!$result_action_1279 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, 'dfc236bfafa081e74f23a1c5f631fe78', 'Echéances','echeances', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="echeances"  ><i class="ace-icon fa fa-exchange bigger-100"></i> Echéances</a></li>'."', '0', '[-1-]', '2', '0', 'Attente Renouvelement','warning','".'<span class="label label-sm label-warning">Attente Renouvelement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Echéances' </li>";}
      // Action Task 784 - 'Echéances '
      if(!$result_action_1422 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, '4d089388d8352205f44bc0afa1b1d7f9', 'Echéances ','echeances', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="echeances"  ><i class="ace-icon fa fa-exchange bigger-100"></i> Echéances </a></li>'."', '0', '[-1-3-7-]', '3', '0', 'Contrat Expiré','info','".'<span class="label label-sm label-info">Contrat Expiré</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Echéances ' </li>";}
      // Action Task 784 - 'Echéances '
      if(!$result_action_1423 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, 'c4afb786140c9f81eedb8c048545985c', 'Echéances ','echeances', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="echeances"  ><i class="ace-icon fa fa-exchange bigger-100"></i> Echéances </a></li>'."', '0', '[-1-3-7-]', '4', '0', 'Contrat Expiré','inverse','".'<span class="label label-sm label-inverse">Contrat Expiré</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Echéances ' </li>";}
      // Action Task 784 - 'Echéances '
      if(!$result_action_1424 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_784, 'd2ed22c1f8d624766212273bb6c6e614', 'Echéances ','echeances', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="echeances"  ><i class="ace-icon fa fa-exchange bigger-100"></i> Echéances </a></li>'."', '0', '[-1-3-7-]', '5', '0', 'Contrat Résilié','inverse','".'<span class="label label-sm label-inverse">Contrat Résilié</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Echéances ' </li>";}
  //Task 'addcontrats' 'Ajouter contrat'
  if(!$result_task_785 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addcontrats', $result_insert_modul, 'addcontrat','vente/submodul/contrats', '1', 'Ajouter contrat', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter contrat' </li>";}
      // Action Task 785 - 'Ajouter contrat'
      if(!$result_action_1280 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_785, '87f4c3ed4713c3bc9e3fef60a6649055', 'Ajouter contrat','addcontrats', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter contrat' </li>";}
  //Task 'editcontrats' 'Modifier contrat'
  if(!$result_task_786 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editcontrats', $result_insert_modul, 'editcontrat','vente/submodul/contrats', '1', 'Modifier contrat', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier contrat' </li>";}
      // Action Task 786 - 'Modifier contrat'
      if(!$result_action_1281 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_786, '9e49a431d9637544cefa2869fd7278b9', 'Modifier contrat','editcontrats', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier contrat' </li>";}
  //Task 'deletecontrat' 'Supprimer contrat'
  if(!$result_task_787 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletecontrat', $result_insert_modul, 'deletecontrat','vente/submodul/contrats', '1', 'Supprimer contrat', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer contrat' </li>";}
      // Action Task 787 - 'Supprimer contrat'
      if(!$result_action_1282 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_787, '1e9395a182a44787e493bc038cd80bbf', 'Supprimer contrat','deletecontrat', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer contrat' </li>";}
  //Task 'validcontrat' 'Valider contrat'
  if(!$result_task_788 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validcontrat', $result_insert_modul, 'validcontrat','vente/submodul/contrats', '1', 'Valider contrat', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider contrat' </li>";}
      // Action Task 788 - 'Valider contrat'
      if(!$result_action_1283 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_788, '460d92834715b149c4db28e1643bd932', 'Valider contrat','validcontrat', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider contrat' </li>";}
  //Task 'detailcontrat' 'Détail contrat'
  if(!$result_task_789 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailcontrat', $result_insert_modul, 'detailcontrat','vente/submodul/contrats', '1', 'Détail contrat', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détail contrat' </li>";}
      // Action Task 789 - 'Détail contrat'
      if(!$result_action_1284 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_789, 'bbcf2879c2f8f60cfa55fa97c6e79268', 'Détail contrat','detailcontrat', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail contrat' </li>";}
  //Task 'addecheance_contrat' 'Ajouter échéance contrat'
  if(!$result_task_790 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addecheance_contrat', $result_insert_modul, 'addecheance_contrat','vente/submodul/contrats', '1', 'Ajouter échéance contrat', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter échéance contrat' </li>";}
      // Action Task 790 - 'Ajouter échéance '
      if(!$result_action_1285 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_790, 'fe058ccb890b25a54866be7f24a40363', 'Ajouter échéance ','addecheance_contrat', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter échéance ' </li>";}
  //Task 'editecheance_contrat' 'Modifier échéance contrat'
  if(!$result_task_791 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editecheance_contrat', $result_insert_modul, 'editecheance_contrat','vente/submodul/contrats', '1', 'Modifier échéance contrat', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier échéance contrat' </li>";}
      // Action Task 791 - 'Modifier échéance contrat'
      if(!$result_action_1286 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_791, '36a248f56a6a80977e5c90a5c59f39d3', 'Modifier échéance contrat','editecheance_contrat', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier échéance contrat' </li>";}
  //Task 'renouvelercontrats' 'Renouveler Contrat'
  if(!$result_task_792 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('renouvelercontrats', $result_insert_modul, 'renouvelercontrat','vente/submodul/contrats', '1', 'Renouveler Contrat', 'exchange', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Renouveler Contrat' </li>";}
      // Action Task 792 - 'Renouveler Contrat'
      if(!$result_action_1287 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_792, 'f0567980556249721f24f2fc88ebfed5', 'Renouveler Contrat','renouvelercontrats', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Renouvelement','danger','".'<span class="label label-sm label-danger">Attente Renouvelement</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Renouveler Contrat' </li>";}
  //Task 'resiliercontrat' 'Résilier Contrat'
  if(!$result_task_793 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('resiliercontrat', $result_insert_modul, 'resiliercontrat','vente/submodul/contrats', '1', 'Résilier Contrat', 'trash', '1', '0', '0','exec', '[-1-2-3-5-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Résilier Contrat' </li>";}
      // Action Task 793 - 'Résilier Contrat'
      if(!$result_action_1288 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_793, 'd3fc6f1bcca0a0250c5f6de29fd72b80', 'Résilier Contrat','resiliercontrat', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Contrat Validé','success','".'<span class="label label-sm label-success">Contrat Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Résilier Contrat' </li>";}
  //Task 'echeances' 'Echéances'
  if(!$result_task_794 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('echeances', $result_insert_modul, 'echeances','vente/submodul/contrats', '1', 'Echéances', 'exchange', '1', '0', '0','list', '[-1-2-3-5-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Echéances' </li>";}
      // Action Task 794 - 'Echéances'
      if(!$result_action_1289 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_794, '428bf9d4c56394d24e15f5458b077990', 'Echéances','echeances', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','success','".'<span class="label label-sm label-success">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Echéances' </li>";}
      // Action Task 794 - 'Générer Facture'
      if(!$result_action_1290 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_794, 'b0cff04f8af9234adbc81e7f679c7176', 'Générer Facture','generatefacture', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="generatefacture"  ><i class="ace-icon fa fa-book bigger-100"></i> Générer Facture</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Générer Facture' </li>";}
      // Action Task 794 - 'Afficher Facture'
      if(!$result_action_1291 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_794, '1596760bb0380a6a77c784ec92eb6fa7', 'Afficher Facture','afficherfacture', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="afficherfacture"  ><i class="ace-icon fa fa-eye bigger-100"></i> Afficher Facture</a></li>'."', '0', '[-1-]', '1', '0', 'Facture Générée','success','".'<span class="label label-sm label-success">Facture Générée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Afficher Facture' </li>";}
  //Task 'generatefacture' 'Générer Facture'
  if(!$result_task_795 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('generatefacture', $result_insert_modul, 'generatefacture','vente/submodul/contrats', '1', 'Générer Facture', 'book', '1', '0', '0','exec', '[-1-2-3-5-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Générer Facture' </li>";}
      // Action Task 795 - 'Générer Facture'
      if(!$result_action_1292 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_795, 'b37af8eb31b7082afa5ad48f0d618f3b', 'Générer Facture','generatefacture', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Générer Facture' </li>";}
  //Task 'afficherfacture' 'Afficher Facture'
  if(!$result_task_796 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('afficherfacture', $result_insert_modul, 'afficherfacture','vente/submodul/contrats', '1', 'Afficher Facture', 'eye', '1', '0', '0','profil', '[-1-2-3-5-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Afficher Facture' </li>";}
      // Action Task 796 - 'Afficher Facture'
      if(!$result_action_1293 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_796, 'd860c94cc554cc0ff03af97a9248d2de', 'Afficher Facture','afficherfacture', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Afficher Facture' </li>";}
