<?php 
//Export Module 'contrats' Date: 15-09-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('contrats', 'Gestion des contrats','contrats/main','contrats','contrats',NULL,'0', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'contrats' </li>";}
  //Task 'contrats' 'Gestion des contrats'
  if(!$result_task_413 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('contrats', $result_insert_modul, 'contrats','contrats/main', '1', 'Gestion des contrats', 'cloud', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion des contrats' </li>";}
      // Action Task 413 - 'Gestion des contrats'
      if(!$result_action_617 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_413, '899d40c8f22d4f7a6f048366f1829787', 'Gestion des contrats','contrats', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion des contrats' </li>";}
      // Action Task 413 - 'Modifier contrat'
      if(!$result_action_623 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_413, 'a20f4c5b9c9ebaa238757d6f9f9cb6fb', 'Modifier contrat','editcontrat', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editcontrat"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier contrat</a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier contrat' </li>";}
      // Action Task 413 - 'Détail contrat'
      if(!$result_action_624 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_413, 'fbb243d2c2fa4200c40993e527b3a339', 'Détail contrat','detailcontrat', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailcontrat"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Détail contrat</a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail contrat' </li>";}
      // Action Task 413 - 'Valider contrat'
      if(!$result_action_625 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_413, 'e970c1414507e5b83ae39e7ddedbf15e', 'Valider contrat','validcontrat', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validcontrat"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Valider contrat</a></li>'."', '0', '[-1-]', '0', '1', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider contrat' </li>";}
      // Action Task 413 - 'Désactiver contrat'
      if(!$result_action_626 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_413, '6908357258099272b60018c0f6fb1078', 'Désactiver contrat','validcontrat', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validcontrat"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Désactiver contrat</a></li>'."', '0', '[-1-]', '1', '0', 'Contrat validé','success','".'<span class="label label-sm label-success">Contrat validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver contrat' </li>";}
  //Task 'addcontrat' 'Ajouter contrat'
  if(!$result_task_414 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addcontrat', $result_insert_modul, 'addcontrat','contrats/main', '1', 'Ajouter contrat', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter contrat' </li>";}
      // Action Task 414 - 'Ajouter contrat'
      if(!$result_action_618 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_414, '87f4c3ed4713c3bc9e3fef60a6649055', 'Ajouter contrat','addcontrat', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter contrat' </li>";}
  //Task 'editcontrat' 'Modifier contrat'
  if(!$result_task_415 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editcontrat', $result_insert_modul, 'editcontrat','contrats/main', '1', 'Modifier contrat', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier contrat' </li>";}
      // Action Task 415 - 'Modifier contrat'
      if(!$result_action_619 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_415, '9e49a431d9637544cefa2869fd7278b9', 'Modifier contrat','editcontrat', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier contrat' </li>";}
  //Task 'deletecontrat' 'Supprimer contrat'
  if(!$result_task_416 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletecontrat', $result_insert_modul, 'deletecontrat','contrats/main', '1', 'Supprimer contrat', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer contrat' </li>";}
      // Action Task 416 - 'Supprimer contrat'
      if(!$result_action_620 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_416, '1e9395a182a44787e493bc038cd80bbf', 'Supprimer contrat','deletecontrat', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer contrat' </li>";}
  //Task 'validcontrat' 'Valider contrat'
  if(!$result_task_417 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validcontrat', $result_insert_modul, 'validcontrat','contrats/main', '1', 'Valider contrat', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider contrat' </li>";}
      // Action Task 417 - 'Valider contrat'
      if(!$result_action_621 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_417, '460d92834715b149c4db28e1643bd932', 'Valider contrat','validcontrat', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider contrat' </li>";}
  //Task 'detailcontrat' 'Détail contrat'
  if(!$result_task_418 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailcontrat', $result_insert_modul, 'detailcontrat','contrats/main', '1', 'Détail contrat', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détail contrat' </li>";}
      // Action Task 418 - 'Détail contrat'
      if(!$result_action_622 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_418, 'bbcf2879c2f8f60cfa55fa97c6e79268', 'Détail contrat','detailcontrat', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail contrat' </li>";}
  //Task 'addecheance_contrat' 'Ajouter échéance contrat'
  if(!$result_task_419 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addecheance_contrat', $result_insert_modul, 'addecheance_contrat','contrats/main', '1', 'Ajouter échéance contrat', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter échéance contrat' </li>";}
      // Action Task 419 - 'Ajouter échéance '
      if(!$result_action_627 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_419, 'fe058ccb890b25a54866be7f24a40363', 'Ajouter échéance ','addecheance_contrat', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter échéance ' </li>";}
  //Task 'editecheance_contrat' 'Modifier échéance contrat'
  if(!$result_task_420 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editecheance_contrat', $result_insert_modul, 'editecheance_contrat','contrats/main', '1', 'Modifier échéance contrat', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier échéance contrat' </li>";}
      // Action Task 420 - 'Modifier échéance contrat'
      if(!$result_action_628 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_420, '36a248f56a6a80977e5c90a5c59f39d3', 'Modifier échéance contrat','editecheance_contrat', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier échéance contrat' </li>";}
