<?php 
//Export Module 'departements' Date: 15-09-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('departements', 'Gestion Départements','Systeme/settings/departements','ref_departement','departements','Systeme','1', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'departements' </li>";}
  //Task 'departements' 'Gestion Départements'
  if(!$result_task_432 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('departements', $result_insert_modul, 'departements','Systeme/settings/departements', '1', 'Gestion Départements', 'bullhorn', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Départements' </li>";}
      // Action Task 432 - 'Gestion Départements'
      if(!$result_action_613 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_432, 'f320732af279d6f2f8ae9c98cd0216de', 'Gestion Départements','departements', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Départements' </li>";}
      // Action Task 432 - 'Editer Département'
      if(!$result_action_617 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_432, '96516cd0c72d814d5dcb1d86eacd29ab', 'Editer Département','editdepartement', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editdepartement"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Editer Département</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Département' </li>";}
      // Action Task 432 - 'Valider Département'
      if(!$result_action_619 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_432, 'ef27a63534fa9fc3bd4b5086a92db546', 'Valider Département','validdepartement', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validdepartement"  ><i class="ace-icon fa fa-lock bigger-100"></i> Valider Département</a></li>'."', '0', '[-1-]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Département' </li>";}
      // Action Task 432 - 'Désactiver Département'
      if(!$result_action_620 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_432, '9aed965af4c4b89a5a23c41bf685d403', 'Désactiver Département','validdepartement', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validdepartement"  ><i class="ace-icon fa fa-unlock bigger-100"></i> Désactiver Département</a></li>'."', '0', '[-1-]', '1', '0', 'Département Validé','success','".'<span class="label label-sm label-success">Département Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver Département' </li>";}
  //Task 'adddepartement' 'Ajouter Département'
  if(!$result_task_433 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adddepartement', $result_insert_modul, 'adddepartement','Systeme/settings/departements', '1', 'Ajouter Département', 'bullhorn', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Département' </li>";}
      // Action Task 433 - 'Ajouter Département'
      if(!$result_action_614 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_433, '722b3ba1c7fe735e87aa7415e5502a4c', 'Ajouter Département','adddepartement', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Département' </li>";}
  //Task 'editdepartement' 'Editer Département'
  if(!$result_task_434 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editdepartement', $result_insert_modul, 'editdepartement','Systeme/settings/departements', '1', 'Editer Département', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer Département' </li>";}
      // Action Task 434 - 'Editer Département'
      if(!$result_action_615 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_434, 'daeb31006124e562d284aff67360ee19', 'Editer Département','editdepartement', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Département' </li>";}
  //Task 'deletedepartement' 'Supprimer Département'
  if(!$result_task_435 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletedepartement', $result_insert_modul, 'deletedepartement','Systeme/settings/departements', '1', 'Supprimer Département', 'trash', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Département' </li>";}
      // Action Task 435 - 'Supprimer Département'
      if(!$result_action_616 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_435, 'a775da608fe55c53211d4f1c6e493251', 'Supprimer Département','deletedepartement', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Département' </li>";}
  //Task 'validdepartement' 'Valider Département'
  if(!$result_task_436 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validdepartement', $result_insert_modul, 'validdepartement','Systeme/settings/departements', '1', 'Valider Département', 'lock', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Département' </li>";}
      // Action Task 436 - 'Valider Département'
      if(!$result_action_618 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_436, 'bbb96ec910c5000a2006db2f6e8af10a', 'Valider Département','validdepartement', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Département' </li>";}
