<?php 
//Export Module 'devis' Date: 31-07-2018
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('devis', 'Gestion Devis','vente/submodul/devis','devis','devis','vente','2', '0', '[-1-2-3-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'devis' </li>";}
  //Task 'devis' 'Gestion Devis'
  if(!$result_task_850 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('devis', $result_insert_modul, 'devis','vente/submodul/devis', '1', 'Gestion Devis', 'paper-plane-o', '1', '0', '0','list', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Devis' </li>";}
      // Action Task 850 - 'Gestion Devis'
      if(!$result_action_1393 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, '0e79510db7f03b9b6266fc7b4a612153', 'Gestion Devis','devis', NULL, '".NULL."', '1', '[-1-2-]', '0', '1', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Devis' </li>";}
      // Action Task 850 - 'Modifier Devis'
      if(!$result_action_1394 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, 'c15b00a1e37657336df8b6aa0eea2db5', 'Modifier Devis','editdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editdevis"  ><i class="ace-icon fa fa-pencil-square-o blue bigger-100"></i> Modifier Devis</a></li>'."', '0', '[-1-2-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Devis' </li>";}
      // Action Task 850 - 'Voir détails'
      if(!$result_action_1396 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, '28e267a2a0647d4cb37b18abb1e7d051', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '1', '1', 'Attente ','warning','".'<span class="label label-sm label-warning">Attente </span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 850 - 'Voir détails'
      if(!$result_action_1397 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, 'd34b07afd92adad84e1c4c2ebd92ba95', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye blue bigger-100"></i> Voir détails</a></li>'."', '0', '[-3-5-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 850 - 'Réponse Client'
      if(!$result_action_1398 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, 'f6f55b9d0ba9d704b2861d57cda32477', 'Réponse Client','validdevisclient', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="validdevisclient"  ><i class="ace-icon fa fa-check green bigger-100"></i> Réponse Client</a></li>'."', '0', '[-1-2-3-5-]', '2', '0', 'Attente réponse client','info','".'<span class="label label-sm label-info">Attente réponse client</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Réponse Client' </li>";}
      // Action Task 850 - 'Voir détails'
      if(!$result_action_1399 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, '4b11c0bfb3f970a541100f7fc334927e', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '3', '1', 'Demande modification','info','".'<span class="label label-sm label-info">Demande modification</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 850 - 'Voir détails'
      if(!$result_action_1400 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, '61a0655c2c13039b5b8262b82ae6cb51', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '2', '0', 'Attente réponse client','info','".'<span class="label label-sm label-info">Attente réponse client</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 850 - 'Voir détails'
      if(!$result_action_1401 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, 'ed30dfbb21d8d24a0da432252358bdf8', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '4', '0', 'Devis Validé par le client','success','".'<span class="label label-sm label-success">Devis Validé par le client</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 850 - 'Débloquer devis'
      if(!$result_action_1402 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, '7bd2e025ffb3893dea4776e152301716', 'Débloquer devis','debloqdevis', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="debloqdevis"  ><i class="ace-icon fa fa-unlock blue bigger-100"></i> Débloquer devis</a></li>'."', '0', '[-1-3-]', '3', '1', 'Demande modification','info','".'<span class="label label-sm label-info">Demande modification</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Débloquer devis' </li>";}
      // Action Task 850 - 'Valider devis'
      if(!$result_action_1403 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, '6d9ec7d9ebebcdc921376e7bf0c9fdaf', 'Valider devis','validdevis', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validdevis"  ><i class="ace-icon fa fa-check green bigger-100"></i> Valider devis</a></li>'."', '0', '[-1-3-]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider devis' </li>";}
      // Action Task 850 - 'Voir détails'
      if(!$result_action_1404 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, 'b1bcc4a4ab154f110abcf54c0c659fb3', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '5', '0', 'Devis rejeté par le client','danger','".'<span class="label label-sm label-danger">Devis rejeté par le client</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 850 - 'Voir détails'
      if(!$result_action_1405 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, '91a90a46e3430c491ab8db654b6e87c4', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '6', '0', 'Devis Expiré','inverse','".'<span class="label label-sm label-inverse">Devis Expiré</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 850 - 'Renouveler Devis'
      if(!$result_action_1406 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, 'cf6178eae84de71449fcee8911b77f40', 'Renouveler Devis','renewdevis', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="renewdevis"  ><i class="ace-icon fa fa-share bigger-100"></i> Renouveler Devis</a></li>'."', '0', '[-1-2-3-]', '6', '0', 'Devis Expiré','inverse','".'<span class="label label-sm label-inverse">Devis Expiré</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Renouveler Devis' </li>";}
      // Action Task 850 - 'Voir détails'
      if(!$result_action_1407 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, 'c0c64bb86ef45f064af45136b5f28ae7', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '8', '1', 'En Livraison','info','".'<span class="label label-sm label-info">En Livraison</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 850 - 'Préparer livraison'
      if(!$result_action_1408 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, '18f2ec7bc883829e215136a2318755ef', 'Préparer livraison','devislivraison', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="devislivraison"  ><i class="ace-icon fa fa-external-link  bigger-100"></i> Préparer livraison</a></li>'."', '0', '[-1-2-3-5-]', '8', '1', 'En Livraison','info','".'<span class="label label-sm label-info">En Livraison</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Préparer livraison' </li>";}
      // Action Task 850 - 'Envoi Devis'
      if(!$result_action_1426 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, '972e98928c815f2e6342c7656027e55d', 'Envoi Devis','senddevis', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="senddevis"  ><i class="ace-icon fa fa-envelope bigger-100"></i> Envoi Devis</a></li>'."', '0', '[-1-2-3-5-7-]', '1', '1', 'Attente ','warning','".'<span class="label label-sm label-warning">Attente </span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Envoi Devis' </li>";}
      // Action Task 850 - 'Devis Archivé'
      if(!$result_action_1432 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_850, '8197ef94c28b8b0597e711d52feb46c9', 'Devis Archivé','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye blue bigger-100"></i> Devis Archivé</a></li>'."', '0', '[-1-2-3-5-]', '100', '0', 'Devis archivé','inverse','".'<span class="label label-sm label-inverse">Devis archivé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Devis Archivé' </li>";}
  //Task 'adddevis' 'Ajouter Devis'
  if(!$result_task_851 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adddevis', $result_insert_modul, 'adddevis','vente/submodul/devis', '1', 'Ajouter Devis', 'plus', '1', '0', '0','form', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Devis' </li>";}
      // Action Task 851 - 'Ajouter Devis'
      if(!$result_action_1409 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_851, 'd9eeb330625c1b87e0df00986a47be01', 'Ajouter Devis','adddevis', NULL, '".NULL."', '0', '[-1-2-]', '0', '0', 'Brouillon','success','".'<span class="label label-sm label-success">Brouillon</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Devis' </li>";}
  //Task 'add_detaildevis' 'Ajouter détail devis'
  if(!$result_task_852 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('add_detaildevis', $result_insert_modul, 'add_detaildevis','vente/submodul/devis', '1', 'Ajouter détail devis', 'plus', '1', '0', '0','form', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter détail devis' </li>";}
      // Action Task 852 - 'Ajouter détail devis'
      if(!$result_action_1410 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_852, 'da93cdb05137e15aed9c4c18bddd746a', 'Ajouter détail devis','add_detaildevis', NULL, '".NULL."', '0', '[-1-2-]', '0', '0', 'Attente validation','success','".'<span class="label label-sm label-success">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter détail devis' </li>";}
  //Task 'editdevis' 'Modifier Devis'
  if(!$result_task_853 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editdevis', $result_insert_modul, 'editdevis','vente/submodul/devis', '1', 'Modifier Devis', 'pen', '1', '0', '0','form', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Devis' </li>";}
      // Action Task 853 - 'Modifier Devis'
      if(!$result_action_1411 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_853, 'f9f3c299f9bd0fec014f6bd3f0e06adb', 'Modifier Devis','editdevis', NULL, '".NULL."', '0', '[-1-2-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Devis' </li>";}
  //Task 'deletedevis' 'Supprimer Devis'
  if(!$result_task_854 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletedevis', $result_insert_modul, 'deletedevis','vente/submodul/devis', '1', 'Supprimer Devis', 'trash red', '1', '0', '0','exec', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Devis' </li>";}
      // Action Task 854 - 'Supprimer Devis'
      if(!$result_action_1412 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_854, 'e14cce6f1faf7784adb327581c516b90', 'Supprimer Devis','deletedevis', NULL, '".NULL."', '0', '[-1-3-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Devis' </li>";}
  //Task 'edit_detaildevis' 'Modifier détail Devis'
  if(!$result_task_855 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edit_detaildevis', $result_insert_modul, 'edit_detaildevis','vente/submodul/devis', '1', 'Modifier détail Devis', 'pen', '1', '0', '0','form', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier détail Devis' </li>";}
      // Action Task 855 - 'Modifier détail Devis'
      if(!$result_action_1413 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_855, '38f10871792c133ebcc6040e9a11cde8', 'Modifier détail Devis','edit_detaildevis', NULL, '".NULL."', '0', '[-1-2-3-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier détail Devis' </li>";}
  //Task 'viewdevis' 'Afficher détail devis'
  if(!$result_task_856 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('viewdevis', $result_insert_modul, 'viewdevis','vente/submodul/devis', '1', 'Afficher détail devis', 'eye', '1', '0', '0','profil', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Afficher détail devis' </li>";}
      // Action Task 856 - 'Afficher détail devis'
      if(!$result_action_1414 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_856, '8def42e75fd4aee61c378d9fb303850d', 'Afficher détail devis','viewdevis', NULL, '".NULL."', '0', '[-1-2-3-4-18-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Afficher détail devis' </li>";}
  //Task 'validdevis' 'Valider Devis'
  if(!$result_task_857 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validdevis', $result_insert_modul, 'validdevis','vente/submodul/devis', '1', 'Valider Devis', NULL, '1', '0', '0','exec', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Devis' </li>";}
      // Action Task 857 - 'Valider Devis'
      if(!$result_action_1415 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_857, '7666e87783b0f5a7eec1eea7593f7dfe', 'Valider Devis','validdevis', NULL, '".NULL."', '0', '[-1-2-3-5-4-]', '0', '0', 'Attente validation','success','".'<span class="label label-sm label-success">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Devis' </li>";}
  //Task 'validdevisclient' 'Validation Client Devis'
  if(!$result_task_858 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validdevisclient', $result_insert_modul, 'validdevisclient','vente/submodul/devis', '1', 'Validation Client Devis', 'check', '1', '0', '0','formpers', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Validation Client Devis' </li>";}
      // Action Task 858 - 'Validation Client Devis'
      if(!$result_action_1416 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_858, '7f1c48324d8c369da9aa6ab8af35acd8', 'Validation Client Devis','validdevisclient', NULL, '".NULL."', '0', '[-1-2-3-5-]', '0', '0', 'Attente validation client','info','".'<span class="label label-sm label-info">Attente validation client</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Validation Client Devis' </li>";}
  //Task 'debloqdevis' 'Débloquer devis'
  if(!$result_task_859 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('debloqdevis', $result_insert_modul, 'debloqdevis','vente/submodul/devis', '1', 'Débloquer devis', 'unlock blue', '1', '0', '0','exec', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Débloquer devis' </li>";}
      // Action Task 859 - 'Débloquer devis'
      if(!$result_action_1417 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_859, '6adf896091dde0df89f777f31606953c', 'Débloquer devis','debloqdevis', NULL, '".NULL."', '0', '[-1-3-]', '0', '0', 'Débloquer Devis','inverse','".'<span class="label label-sm label-inverse">Débloquer Devis</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Débloquer devis' </li>";}
  //Task 'archivedevis' 'Archiver Devis'
  if(!$result_task_860 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('archivedevis', $result_insert_modul, 'archivedevis','vente/submodul/devis', '1', 'Archiver Devis', 'zip', '1', '0', '0','exec', '[-1-2-3-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Archiver Devis' </li>";}
      // Action Task 860 - 'Archiver Devis'
      if(!$result_action_1418 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_860, '15cbb79dd4a74266158e6b29a83e683c', 'Archiver Devis','archivdevis', NULL, '".NULL."', '1', '[-1-3-]', '0', '0', 'Devis archivé','inverse','".'<span class="label label-sm label-inverse">Devis archivé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Archiver Devis' </li>";}
  //Task 'add_client_diver' 'Ajout client divers'
  if(!$result_task_861 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('add_client_diver', $result_insert_modul, 'add_client_diver','vente/submodul/devis', '1', 'Ajout client divers', 'plus', '1', '0', '0','formadd', '[-1-2-3-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajout client divers' </li>";}
      // Action Task 861 - 'Ajout client divers'
      if(!$result_action_1419 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_861, 'f520c1e87674cdaf83635d37863de930', 'Ajout client divers','add_client_diver', NULL, '".NULL."', '1', '[-1-2-3-]', '0', '0', 'Attente validation','success','".'<span class="label label-sm label-success">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajout client divers' </li>";}
  //Task 'renewdevis' 'Renouveler Devis'
  if(!$result_task_862 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('renewdevis', $result_insert_modul, 'renewdevis','vente/submodul/devis', '1', 'Renouveler Devis', 'share', '1', '0', '0','formedit', '[-1-2-3-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Renouveler Devis' </li>";}
      // Action Task 862 - 'Renouveler Devis'
      if(!$result_action_1420 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_862, '118fe4b340e728b2cb9ee9607531fae4', 'Renouveler Devis','renewdevis', NULL, '".NULL."', '1', '[-1-2-3-]', '0', '0', 'Devis expiré','inverse','".'<span class="label label-sm label-inverse">Devis expiré</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Renouveler Devis' </li>";}
  //Task 'devislivraison' 'Préparer livraison'
  if(!$result_task_863 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('devislivraison', $result_insert_modul, 'devislivraison','vente/submodul/devis', '1', 'Préparer livraison', 'external-link', '1', '0', '0','formpers', '[-1-2-3-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Préparer livraison' </li>";}
      // Action Task 863 - 'Préparer livraison'
      if(!$result_action_1421 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_863, '9a405d89d749c15a976b939b96a1128b', 'Préparer livraison','devislivraison', NULL, '".NULL."', '1', '[-1-2-3-5-]', '0', '0', 'En Livraison','info','".'<span class="label label-sm label-info">En Livraison</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Préparer livraison' </li>";}
  //Task 'senddevis' 'Envoi Devis'
  if(!$result_task_864 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('senddevis', $result_insert_modul, 'senddevis','vente/submodul/devis', '1', 'Envoi Devis', 'envelope', '1', '0', '0','exec', '[-1-2-3-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Envoi Devis' </li>";}
      // Action Task 864 - 'Envoi Devis'
      if(!$result_action_1395 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_864, 'eca377ac7e74379f4fadb30aff80ada1', 'Envoi Devis','senddevis', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="senddevis"  ><i class="ace-icon fa fa-envelope bigger-100"></i> Envoi Devis</a></li>'."', '0', '[-1-2-3-5-4-]', '1', '1', 'Attente Expédition','warning','".'<span class="label label-sm label-warning">Attente Expédition</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Envoi Devis' </li>";}
