<?php 
//Export Module 'devis' Date: 13-10-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('devis', 'Gestion Devis','vente/submodul/devis','devis','devis','vente','2', '0', '[-1-2-3-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'devis' </li>";}
  //Task 'devis' 'Gestion Devis'
  if(!$result_task_571 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('devis', $result_insert_modul, 'devis','vente/submodul/devis', '1', 'Gestion Devis', 'paper-plane-o', '1', '0', '0','list', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Devis' </li>";}
      // Action Task 571 - 'Gestion Devis'
      if(!$result_action_854 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, '0e79510db7f03b9b6266fc7b4a612153', 'Gestion Devis','devis', NULL, '".NULL."', '1', '[-1-2-]', '0', '1', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Devis' </li>";}
      // Action Task 571 - 'Modifier Devis'
      if(!$result_action_855 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, 'c15b00a1e37657336df8b6aa0eea2db5', 'Modifier Devis','editdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editdevis"  ><i class="ace-icon fa fa-pencil-square-o blue bigger-100"></i> Modifier Devis</a></li>'."', '0', '[-1-2-]', '0', '1', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Devis' </li>";}
      // Action Task 571 - 'Envoi au client'
      if(!$result_action_857 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, '7cfdba6bc6bc94c65b97e77746cf49b5', 'Envoi au client','validdevis', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validdevis"  ><i class="ace-icon fa fa-envelope bigger-100"></i> Envoi au client</a></li>'."', '0', '[-1-2-3-]', '1', '1', 'Attente Expédition','warning','".'<span class="label label-sm label-warning">Attente Expédition</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Envoi au client' </li>";}
      // Action Task 571 - 'Voir détails'
      if(!$result_action_858 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, '28e267a2a0647d4cb37b18abb1e7d051', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '1', '1', 'Attente Expédition','warning','".'<span class="label label-sm label-warning">Attente Expédition</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 571 - 'Voir détails'
      if(!$result_action_859 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, 'd34b07afd92adad84e1c4c2ebd92ba95', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '0', '1', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 571 - 'Réponse Client'
      if(!$result_action_914 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, 'f6f55b9d0ba9d704b2861d57cda32477', 'Réponse Client','validdevisclient', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="validdevisclient"  ><i class="ace-icon fa fa-check green bigger-100"></i> Réponse Client</a></li>'."', '0', '[-1-2-3-5-]', '2', '0', 'Attente réponse client','info','".'<span class="label label-sm label-info">Attente réponse client</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Réponse Client' </li>";}
      // Action Task 571 - 'Voir détails'
      if(!$result_action_915 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, '4b11c0bfb3f970a541100f7fc334927e', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '3', '1', 'Demande modification','info','".'<span class="label label-sm label-info">Demande modification</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 571 - 'Voir détails'
      if(!$result_action_916 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, '61a0655c2c13039b5b8262b82ae6cb51', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '2', '0', 'Attente réponse client','info','".'<span class="label label-sm label-info">Attente réponse client</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 571 - 'Voir détails'
      if(!$result_action_917 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, 'ed30dfbb21d8d24a0da432252358bdf8', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '4', '0', 'Devis Validé par le client','success','".'<span class="label label-sm label-success">Devis Validé par le client</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 571 - 'Débloquer devis'
      if(!$result_action_919 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, '7bd2e025ffb3893dea4776e152301716', 'Débloquer devis','debloqdevis', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="debloqdevis"  ><i class="ace-icon fa fa-unlock blue bigger-100"></i> Débloquer devis</a></li>'."', '0', '[-1-3-]', '3', '1', 'Demande modification','info','".'<span class="label label-sm label-info">Demande modification</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Débloquer devis' </li>";}
      // Action Task 571 - 'Valider devis'
      if(!$result_action_978 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, '6d9ec7d9ebebcdc921376e7bf0c9fdaf', 'Valider devis','validdevis', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validdevis"  ><i class="ace-icon fa fa-check green bigger-100"></i> Valider devis</a></li>'."', '0', '[-1-3-]', '0', '1', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider devis' </li>";}
      // Action Task 571 - 'Voir détails'
      if(!$result_action_987 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, 'b1bcc4a4ab154f110abcf54c0c659fb3', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '5', '0', 'Devis rejeté par le client','danger','".'<span class="label label-sm label-danger">Devis rejeté par le client</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
      // Action Task 571 - 'Voir détails'
      if(!$result_action_988 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_571, '91a90a46e3430c491ab8db654b6e87c4', 'Voir détails','viewdevis', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewdevis"  ><i class="ace-icon fa fa-eye bigger-100"></i> Voir détails</a></li>'."', '0', '[-1-2-3-5-]', '6', '0', 'Devis Expiré','inverse','".'<span class="label label-sm label-inverse">Devis Expiré</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Voir détails' </li>";}
  //Task 'adddevis' 'Ajouter Devis'
  if(!$result_task_572 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adddevis', $result_insert_modul, 'adddevis','vente/submodul/devis', '1', 'Ajouter Devis', 'plus', '1', '0', '0','form', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Devis' </li>";}
      // Action Task 572 - 'Ajouter Devis'
      if(!$result_action_860 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_572, 'd9eeb330625c1b87e0df00986a47be01', 'Ajouter Devis','adddevis', NULL, '".NULL."', '0', '[-1-2-]', '0', '0', 'Brouillon','success','".'<span class="label label-sm label-success">Brouillon</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Devis' </li>";}
  //Task 'add_detaildevis' 'Ajouter détail devis'
  if(!$result_task_573 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('add_detaildevis', $result_insert_modul, 'add_detaildevis','vente/submodul/devis', '1', 'Ajouter détail devis', 'plus', '1', '0', '0','form', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter détail devis' </li>";}
      // Action Task 573 - 'Ajouter détail devis'
      if(!$result_action_861 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_573, 'da93cdb05137e15aed9c4c18bddd746a', 'Ajouter détail devis','add_detaildevis', NULL, '".NULL."', '0', '[-1-2-]', '0', '0', 'Attente validation','success','".'<span class="label label-sm label-success">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter détail devis' </li>";}
  //Task 'editdevis' 'Modifier Devis'
  if(!$result_task_574 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editdevis', $result_insert_modul, 'editdevis','vente/submodul/devis', '1', 'Modifier Devis', 'pen', '1', '0', '0','form', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Devis' </li>";}
      // Action Task 574 - 'Modifier Devis'
      if(!$result_action_862 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_574, 'f9f3c299f9bd0fec014f6bd3f0e06adb', 'Modifier Devis','editdevis', NULL, '".NULL."', '0', '[-1-2-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Devis' </li>";}
  //Task 'deletedevis' 'Supprimer Devis'
  if(!$result_task_575 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletedevis', $result_insert_modul, 'deletedevis','vente/submodul/devis', '1', 'Supprimer Devis', 'trash red', '1', '0', '0','exec', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Devis' </li>";}
      // Action Task 575 - 'Supprimer Devis'
      if(!$result_action_863 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_575, 'e14cce6f1faf7784adb327581c516b90', 'Supprimer Devis','deletedevis', NULL, '".NULL."', '0', '[-1-3-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Devis' </li>";}
  //Task 'edit_detaildevis' 'Modifier détail Devis'
  if(!$result_task_576 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edit_detaildevis', $result_insert_modul, 'edit_detaildevis','vente/submodul/devis', '1', 'Modifier détail Devis', 'pen', '1', '0', '0','form', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier détail Devis' </li>";}
      // Action Task 576 - 'Modifier détail Devis'
      if(!$result_action_864 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_576, '38f10871792c133ebcc6040e9a11cde8', 'Modifier détail Devis','edit_detaildevis', NULL, '".NULL."', '0', '[-1-2-3-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier détail Devis' </li>";}
  //Task 'viewdevis' 'Afficher détail devis'
  if(!$result_task_577 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('viewdevis', $result_insert_modul, 'viewdevis','vente/submodul/devis', '1', 'Afficher détail devis', 'eye', '1', '0', '0','profil', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Afficher détail devis' </li>";}
      // Action Task 577 - 'Afficher détail devis'
      if(!$result_action_865 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_577, '8def42e75fd4aee61c378d9fb303850d', 'Afficher détail devis','viewdevis', NULL, '".NULL."', '0', '[-1-2-3-4-18-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Afficher détail devis' </li>";}
  //Task 'validdevis' 'Valider Devis'
  if(!$result_task_578 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validdevis', $result_insert_modul, 'validdevis','vente/submodul/devis', '1', 'Valider Devis', NULL, '1', '0', '0','exec', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Devis' </li>";}
      // Action Task 578 - 'Valider Devis'
      if(!$result_action_866 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_578, '7666e87783b0f5a7eec1eea7593f7dfe', 'Valider Devis','validdevis', NULL, '".NULL."', '0', '[-1-2-3-5-4-]', '0', '0', 'Attente validation','success','".'<span class="label label-sm label-success">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Devis' </li>";}
  //Task 'validdevisclient' 'Validation Client Devis'
  if(!$result_task_607 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validdevisclient', $result_insert_modul, 'validdevisclient','vente/submodul/devis', '1', 'Validation Client Devis', 'check', '1', '0', '0','formpers', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Validation Client Devis' </li>";}
      // Action Task 607 - 'Validation Client Devis'
      if(!$result_action_913 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_607, '7f1c48324d8c369da9aa6ab8af35acd8', 'Validation Client Devis','validdevisclient', NULL, '".NULL."', '0', '[-1-2-3-5-]', '0', '0', 'Attente validation client','info','".'<span class="label label-sm label-info">Attente validation client</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Validation Client Devis' </li>";}
  //Task 'debloqdevis' 'Débloquer devis'
  if(!$result_task_608 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('debloqdevis', $result_insert_modul, 'debloqdevis','vente/submodul/devis', '1', 'Débloquer devis', 'unlock blue', '1', '0', '0','exec', '[-1-2-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Débloquer devis' </li>";}
      // Action Task 608 - 'Débloquer devis'
      if(!$result_action_918 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_608, '6adf896091dde0df89f777f31606953c', 'Débloquer devis','debloqdevis', NULL, '".NULL."', '0', '[-1-3-]', '0', '0', 'Débloquer Devis','inverse','".'<span class="label label-sm label-inverse">Débloquer Devis</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Débloquer devis' </li>";}
  //Task 'archivdevis' 'Archiver Devis'
  if(!$result_task_639 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('archivdevis', $result_insert_modul, 'archivdevis','vente/submodul/devis', '1', 'Archiver Devis', 'zip', '1', '0', '0','exec', '[-1-2-3-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Archiver Devis' </li>";}
      // Action Task 639 - 'Archiver Devis'
      if(!$result_action_986 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_639, '15cbb79dd4a74266158e6b29a83e683c', 'Archiver Devis','archivdevis', NULL, '".NULL."', '1', '[-1-3-]', '0', '0', 'Devis archivé','inverse','".'<span class="label label-sm label-inverse">Devis archivé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Archiver Devis' </li>";}
