<?php 
//Export Module 'entrepots' Date: 14-05-2018
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('entrepots', 'Gestion des Entrepôts','stock/submodul/entrepots','entrepots','entrepots','stock','2', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'entrepots' </li>";}
  //Task 'entrepots' 'Gestion des Entrepôts'
  if(!$result_task_859 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('entrepots', $result_insert_modul, 'entrepots','stock/submodul/entrepots', '1', 'Gestion des Entrepôts', 'briefcase ', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion des Entrepôts' </li>";}
      // Action Task 859 - 'Gestion des Entrepôts'
      if(!$result_action_1409 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_859, '7fde4464cf64b2fca994f7cdc128307e', 'Gestion des Entrepôts','entrepots', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion des Entrepôts' </li>";}
      // Action Task 859 - 'Editer Entrepôt'
      if(!$result_action_1412 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_859, 'dfc69597b3f4c08061386486fd177e5b', 'Editer Entrepôt','editentrepots', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editentrepots"  ><i class="ace-icon fa fa-pencil bigger-100"></i> Editer Entrepôt</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Entrepôt' </li>";}
      // Action Task 859 - 'Valider Entrepôt'
      if(!$result_action_1415 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_859, '4886df3c47866eac474e1d87f7774850', 'Valider Entrepôt','validentrepots', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validentrepots"  ><i class="ace-icon fa fa-check bigger-100"></i> Valider Entrepôt</a></li>'."', '0', '[-1-]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Entrepôt' </li>";}
      // Action Task 859 - 'Désactiver Entrepôt'
      if(!$result_action_1416 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_859, 'f16f69131a3e43f28acab8db040dbe1c', 'Désactiver Entrepôt','validentrepots', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validentrepots"  ><i class="ace-icon fa fa-lock bigger-100"></i> Désactiver Entrepôt</a></li>'."', '0', '[-1-]', '1', '0', 'Entrepôt Validé','success','".'<span class="label label-sm label-success">Entrepôt Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver Entrepôt' </li>";}
  //Task 'addentrepots' 'Ajouter Entrepôt'
  if(!$result_task_860 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addentrepots', $result_insert_modul, 'addentrepots','stock/submodul/entrepots', '1', 'Ajouter Entrepôt', 'briefcase ', '1', '0', '0','formadd', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Entrepôt' </li>";}
      // Action Task 860 - 'Ajouter Entrepôt'
      if(!$result_action_1410 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_860, '462994905cf4ea3256839ee181df30f0', 'Ajouter Entrepôt','addentrepots', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Entrepôt' </li>";}
  //Task 'editentrepots' 'Editer Entrepôt'
  if(!$result_task_861 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editentrepots', $result_insert_modul, 'editentrepots','stock/submodul/entrepots', '1', 'Editer Entrepôt', 'pencil', '1', '0', '0','formedit', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer Entrepôt' </li>";}
      // Action Task 861 - 'Editer Entrepôt'
      if(!$result_action_1411 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_861, 'c7c70683c8539bf442fbb3bc145062d9', 'Editer Entrepôt','editentrepots', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Entrepôt' </li>";}
  //Task 'deleteentrepots' 'Supprimer Entrepôt'
  if(!$result_task_862 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteentrepots', $result_insert_modul, 'deleteentrepots','stock/submodul/entrepots', '1', 'Supprimer Entrepôt', 'trash', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Entrepôt' </li>";}
      // Action Task 862 - 'Supprimer Entrepôt'
      if(!$result_action_1413 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_862, '883e7763f88a902baf086a152a3c81a5', 'Supprimer Entrepôt','deleteentrepots', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Entrepôt' </li>";}
  //Task 'validentrepots' 'Valider Entrepôt'
  if(!$result_task_863 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validentrepots', $result_insert_modul, 'validentrepots','stock/submodul/entrepots', '1', 'Valider Entrepôt', 'check', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Entrepôt' </li>";}
      // Action Task 863 - 'Valider Entrepôt'
      if(!$result_action_1414 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_863, 'c717024f55a777aece4490406767f434', 'Valider Entrepôt','validentrepots', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Entrepôt' </li>";}
