<?php 
//Export Module 'factures' Date: 02-10-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('factures', 'Gestion des factures','factures/main','factures','factures',NULL,'0', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'factures' </li>";}
  //Task 'factures' 'Gestion des factures'
  if(!$result_task_529 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('factures', $result_insert_modul, 'factures','factures/main', '1', 'Gestion des factures', 'cogs', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion des factures' </li>";}
      // Action Task 529 - 'Gestion des factures'
      if(!$result_action_773 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_529, 'd76c286028993aff54af01da5dc4b233', 'Gestion des factures','factures', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion des factures' </li>";}
      // Action Task 529 - 'Liste complément'
      if(!$result_action_775 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_529, '98a697ec628778765b25e02ba2929d38', 'Liste complément','complements', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="complements"  ><i class="ace-icon fa fa-circle bigger-100"></i> Liste complément</a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste complément' </li>";}
      // Action Task 529 - 'Liste encaissements'
      if(!$result_action_780 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_529, '3b6d1456980ea86c0f44c16c464ca790', 'Liste encaissements','encaissements', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="encaissements"  ><i class="ace-icon fa fa-euro bigger-100"></i> Liste encaissements</a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste encaissements' </li>";}
      // Action Task 529 - 'Valider facture'
      if(!$result_action_786 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_529, '9a51fb5298e39a28af3ad6272fc51177', 'Valider facture','validfacture', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validfacture"  ><i class="ace-icon fa fa-check  bigger-100"></i> Valider facture</a></li>'."', '0', '[-1-]', '0', '1', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider facture' </li>";}
      // Action Task 529 - 'Désactiver facture'
      if(!$result_action_787 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_529, '851f1d4c13f6025f69f5b9315321d350', 'Désactiver facture','validfacture', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validfacture"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Désactiver facture</a></li>'."', '0', '[-1-]', '1', '0', 'Facture validée','success','".'<span class="label label-sm label-success">Facture validée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver facture' </li>";}
      // Action Task 529 - 'Détail facture'
      if(!$result_action_793 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_529, '5c79105956d28b5cac52f85784039919', 'Détail facture','detailsfacture', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsfacture"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détail facture</a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail facture' </li>";}
  //Task 'complements' 'complements'
  if(!$result_task_530 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('complements', $result_insert_modul, 'complements','factures/main', '1', 'complements', 'cogs', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'complements' </li>";}
      // Action Task 530 - 'complements'
      if(!$result_action_774 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_530, '55c3c5d2d93143b315513b7401043c8b', 'complements','complements', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'complements' </li>";}
      // Action Task 530 - 'Modifier complément'
      if(!$result_action_788 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_530, 'dfc4772cc03cf0b92a47f54fc6a2326e', 'Modifier complément','editcomplement', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editcomplement"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier complément</a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier complément' </li>";}
  //Task 'addcomplement' 'Ajouter complément'
  if(!$result_task_531 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addcomplement', $result_insert_modul, 'addcomplement','factures/main', '1', 'Ajouter complément', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter complément' </li>";}
      // Action Task 531 - 'Ajouter complément'
      if(!$result_action_776 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_531, '03a18bdd5201e433a3c523a2b34d059a', 'Ajouter complément','addcomplement', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter complément' </li>";}
  //Task 'encaissements' 'Encaissement'
  if(!$result_task_532 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('encaissements', $result_insert_modul, 'encaissements','factures/main', '1', 'Encaissement', 'cogs', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Encaissement' </li>";}
      // Action Task 532 - 'Encaissement'
      if(!$result_action_778 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_532, '88d9bc979cd1102eb8196e7f5e6042ca', 'Encaissement','encaissements', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Encaissement' </li>";}
      // Action Task 532 - 'Modifier encaissement'
      if(!$result_action_789 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_532, 'c690cc68f5257c0c225b8b8e6126ea56', 'Modifier encaissement','editencaissement', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editencaissement"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier encaissement</a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier encaissement' </li>";}
      // Action Task 532 - 'Détails encaissement'
      if(!$result_action_791 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_532, '1dc06f602e8630f273d44aa2751b2127', 'Détails encaissement','detailsencaissement', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsencaissement"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails encaissement</a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails encaissement' </li>";}
  //Task 'addencaissement' 'Ajouter encaissement'
  if(!$result_task_533 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addencaissement', $result_insert_modul, 'addencaissement','factures/main', '1', 'Ajouter encaissement', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter encaissement' </li>";}
      // Action Task 533 - 'Ajouter encaissement'
      if(!$result_action_779 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_533, 'e4866b292dbc3c9c5d9cc37273a5b498', 'Ajouter encaissement','addencaissement', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter encaissement' </li>";}
  //Task 'editcomplement' 'Modifier complément'
  if(!$result_task_534 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editcomplement', $result_insert_modul, 'editcomplement','factures/main', '1', 'Modifier complément', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier complément' </li>";}
      // Action Task 534 - 'Modifier complément'
      if(!$result_action_781 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_534, '8665be10959f39df4f149962eb70041f', 'Modifier complément','editcomplement', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier complément' </li>";}
  //Task 'editencaissement' 'Modifier encaissement'
  if(!$result_task_535 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editencaissement', $result_insert_modul, 'editencaissement','factures/main', '1', 'Modifier encaissement', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier encaissement' </li>";}
      // Action Task 535 - 'Modifier encaissement'
      if(!$result_action_782 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_535, '585d411904bf7d9e83d21b2810ff1d6c', 'Modifier encaissement','editencaissement', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier encaissement' </li>";}
  //Task 'deletecomplement' 'Supprimer complément'
  if(!$result_task_536 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletecomplement', $result_insert_modul, 'deletecomplement','factures/main', '1', 'Supprimer complément', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer complément' </li>";}
      // Action Task 536 - 'Supprimer complément'
      if(!$result_action_783 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_536, '8c8b058a4d030cdc8b49c9008abb2e92', 'Supprimer complément','deletecomplement', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'Attente de validation'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer complément' </li>";}
  //Task 'deleteencaissement' 'Supprimer encaissement'
  if(!$result_task_537 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteencaissement', $result_insert_modul, 'deleteencaissement','factures/main', '1', 'Supprimer encaissement', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer encaissement' </li>";}
      // Action Task 537 - 'Supprimer encaissement'
      if(!$result_action_784 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_537, '6bf7d5180940f03567a5d711e8563ba4', 'Supprimer encaissement','deleteencaissement', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer encaissement' </li>";}
  //Task 'validfacture' 'Valider facture'
  if(!$result_task_538 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validfacture', $result_insert_modul, 'validfacture','factures/main', '1', 'Valider facture', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider facture' </li>";}
      // Action Task 538 - 'Valider facture'
      if(!$result_action_785 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_538, '256abad0ec8e3bc8ed1c0653ff177255', 'Valider facture','validfacture', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider facture' </li>";}
  //Task 'detailsencaissement' 'Détail encaissement'
  if(!$result_task_539 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsencaissement', $result_insert_modul, 'detailsencaissement','factures/main', '1', 'Détail encaissement', 'eye', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détail encaissement' </li>";}
      // Action Task 539 - 'Détail encaissement'
      if(!$result_action_790 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_539, 'b5dc5719c1f96df7334f371dcf51a5b6', 'Détail encaissement','detailsencaissement', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail encaissement' </li>";}
  //Task 'detailsfacture' 'Détails facture'
  if(!$result_task_540 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsfacture', $result_insert_modul, 'detailsfacture','factures/main', '1', 'Détails facture', 'eye', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails facture' </li>";}
      // Action Task 540 - 'Détails facture'
      if(!$result_action_792 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_540, '16fbf6fdcbb72f863bcf7e4ef28d8e75', 'Détails facture','detailsfacture', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails facture' </li>";}
