<?php 
//Export Module 'fencaissements' Date: 19-04-2020
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('fencaissements', 'Gestion Encaissements','facturation_paiement/submodul/fencaissements','encaissements','fencaissement','facturation_paiement','2', '0', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'fencaissements' </li>";}
  //Task 'fencaissement' 'Gestion Encaissements'
  if(!$result_task_1267 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('fencaissement', $result_insert_modul, 'fencaissement','facturation_paiement/submodul/fencaissements', '1', 'Gestion Encaissements', 'eye', '1', '0', '0','list', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Encaissements' </li>";}
      // Action Task 1267 - 'Gestion Encaissements'
      if(!$result_action_2235 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1267, 'a774fee40d349fdc4572c3f17c98d24d', 'Gestion Encaissements','fencaissement', NULL, '".' '."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Encaissements' </li>";}
      // Action Task 1267 - 'Editer Encaissement'
      if(!$result_action_2237 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1267, '05c8cb30426818f1509034db6b589cfc', 'Editer Encaissement','editfencaissement', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editfencaissement"  ><i class="ace-icon fa fa-pencil-square bigger-100"></i> Editer Encaissement</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Encaissement' </li>";}
      // Action Task 1267 - 'Valider Encaissement'
      if(!$result_action_2239 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1267, '984e3a5ba149be90738f7e4962ff8213', 'Valider Encaissement','validfencaissement', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validfencaissement"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Valider Encaissement</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Encaissement' </li>";}
      // Action Task 1267 - 'Détails Encaissement'
      if(!$result_action_2241 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1267, '8393b8b342a82048cf303aeab38e6901', 'Détails Encaissement','detailsfencaissement', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsfencaissement"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails Encaissement</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Encaissement' </li>";}
      // Action Task 1267 - 'Détails Encaissement'
      if(!$result_action_2242 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1267, '1288810cef9cbaeeb01e9a519dd396f7', 'Détails Encaissement','detailsfencaissement', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsfencaissement"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails Encaissement</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '1', '0', 'Encaissement Validé','success','".'<span class="label label-sm label-success">Encaissement Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Encaissement' </li>";}
  //Task 'editfencaissement' 'Editer Encaissement'
  if(!$result_task_1268 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editfencaissement', $result_insert_modul, 'editfencaissement','facturation_paiement/submodul/fencaissements', '1', 'Editer Encaissement', 'pencil', '1', '0', '0','formedit', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer Encaissement' </li>";}
      // Action Task 1268 - 'Editer Encaissement'
      if(!$result_action_2236 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1268, '69a37577ea5bce48dea88851217f4c54', 'Editer Encaissement','editfencaissement', NULL, '".' '."', '1', 'null', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Encaissement' </li>";}
  //Task 'validfencaissement' 'Valider Encaissement'
  if(!$result_task_1269 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validfencaissement', $result_insert_modul, 'validfencaissement','facturation_paiement/submodul/fencaissements', '1', 'Valider Encaissement', 'eye', '1', '0', '0','exec', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Encaissement' </li>";}
      // Action Task 1269 - 'Valider Encaissement'
      if(!$result_action_2238 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1269, '79fe9189c4674ffaefaa4912b1d95413', 'Valider Encaissement','validfencaissement', NULL, '".' '."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Encaissement' </li>";}
  //Task 'detailsfencaissement' 'Détails Encaissement'
  if(!$result_task_1270 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsfencaissement', $result_insert_modul, 'detailsfencaissement','facturation_paiement/submodul/fencaissements', '1', 'Détails Encaissement', 'eye', '1', '0', '0','profil', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails Encaissement' </li>";}
      // Action Task 1270 - 'Détails Encaissement'
      if(!$result_action_2240 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1270, '3b2304948636c4e1d0d5f0c2864fd992', 'Détails Encaissement','detailsfencaissement', NULL, '".' '."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Encaissement' </li>";}
