<?php 
//Export Module 'gsm' Date: 13-06-2017z
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('gsm', 'Stations GSM','gsm','gsm_stations','gsm',NULL,'0', '0', '[-1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'gsm' </li>";}
  //Task 'gsm' 'Stations GSM'
  if(!$result_task_243 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('gsm', $result_insert_modul, 'gsm','gsm', '1', 'Stations GSM', 'gsm', '1', '0', '0','list', '[-1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Stations GSM' </li>";}
      // Action Task 243 - 'Stations GSM'
      if(!$result_action_357 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_243, '7a7410d377fc922b5709eb53ae018f61', 'Stations GSM', '".NULL."', '1', '[-1-19-18-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Stations GSM' </li>";}
      // Action Task 243 - 'Editer Station GSM'
      if(!$result_action_358 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_243, '1d7bf960e2a33d4d29b6f15d9f73e714', 'Editer Station GSM', '".'<li><a href="#" class="this_url" data="%id%" rel="editgsm"  ><i class="ace-icon fa fa-pencil bigger-100"></i> Editer Station GSM</a></li>'."', '0', '[-1-19-18-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Station GSM' </li>";}
      // Action Task 243 - 'Liste GSM Technologie'
      if(!$result_action_359 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_243, '41955a0e07dddf93209e9c0e5cbab2cb', 'Liste GSM Technologie', '".'<li><a href="#" class="this_url" data="%id%" rel="gsm_technologie"  ><i class="ace-icon fa fa-cloud bigger-100"></i> Liste GSM Technologie</a></li>'."', '0', '[-1-19-18-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste GSM Technologie' </li>";}
      // Action Task 243 - 'Valider Station GSM'
      if(!$result_action_360 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_243, 'a8b1965aa66999404751e6761622c871', 'Valider Station GSM', '".'<li><a href="#" class="this_exec" data="%id%" rel="validgsm"  ><i class="ace-icon fa fa-unlock bigger-100"></i> Valider Station GSM</a></li>'."', '0', '[-1-19-18-]', '0', '1', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Station GSM' </li>";}
      // Action Task 243 - 'Détails station GSM'
      if(!$result_action_361 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_243, '8936f0f56185c85112305acb26b423ec', 'Détails station GSM', '".'<li><a href="#" class="this_url" data="%id%" rel="consultgsm"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails station GSM</a></li>'."', '0', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails station GSM' </li>";}
      // Action Task 243 - 'Détails station GSM'
      if(!$result_action_362 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_243, '633fffb3ac97b0970560040ba7c16bf3', 'Détails station GSM', '".'<li><a href="#" class="this_url" data="%id%" rel="consultgsm"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails station GSM</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails station GSM' </li>";}
  //Task 'addgsm' 'AJouter Station GSM'
  if(!$result_task_244 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addgsm', $result_insert_modul, 'addgsm','gsm', '1', 'AJouter Station GSM', NULL, '1', '0', '0','form', '[-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'AJouter Station GSM' </li>";}
      // Action Task 244 - 'AJouter Station GSM'
      if(!$result_action_363 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_244, '8d95b9c525f610d4cf3b6a8324207648', 'AJouter Station GSM', '".NULL."', '1', '[-1-19-18-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'AJouter Station GSM' </li>";}
  //Task 'editgsm' 'Editer Station GSM'
  if(!$result_task_245 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editgsm', $result_insert_modul, 'editgsm','gsm', '1', 'Editer Station GSM', NULL, '1', '0', '0','form', '[-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer Station GSM' </li>";}
      // Action Task 245 - 'Editer Station GSM'
      if(!$result_action_364 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_245, 'b19cb703c74ae03d96769e05ef5a6b73', 'Editer Station GSM', '".NULL."', '1', '[-1-19-18-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Station GSM' </li>";}
  //Task 'deletegsm' 'Supprimer Station'
  if(!$result_task_246 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletegsm', $result_insert_modul, 'deletegsm','gsm', '1', 'Supprimer Station', NULL, '1', '0', '0','exec', '[-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Station' </li>";}
      // Action Task 246 - 'Supprimer Station'
      if(!$result_action_365 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_246, '645bfcb546eacda07e0242b30e26895e', 'Supprimer Station', '".NULL."', '1', '[-1-17-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Station' </li>";}
  //Task 'gsm_technologie' 'GSM Technologie'
  if(!$result_task_247 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('gsm_technologie', $result_insert_modul, 'gsm_technologie','gsm', '1', 'GSM Technologie', NULL, '1', '0', '0','list', '[-1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'GSM Technologie' </li>";}
      // Action Task 247 - 'GSM Technologie'
      if(!$result_action_366 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_247, 'f542cd069094b75b5bf484dd1cdc64cc', 'GSM Technologie', '".NULL."', '1', '[-1-19-18-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'GSM Technologie' </li>";}
      // Action Task 247 - 'Editer GSM Technologie'
      if(!$result_action_367 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_247, 'bd99144fb26076873a995ed306d9a49e', 'Editer GSM Technologie', '".'<li><a href="#" class="this_url" data="%id%" rel="editgsm_technologie"  ><i class="ace-icon fa fa-pencil bigger-100"></i> Editer GSM Technologie</a></li>'."', '0', '[-1-19-18-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer GSM Technologie' </li>";}
      // Action Task 247 - 'Liste GSM Secteur'
      if(!$result_action_368 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_247, '2dc4797160ac9124ef19b6234b74fc7d', 'Liste GSM Secteur', '".'<li><a href="#" class="this_url" data="%id%" rel="gsm_secteur"  ><i class="ace-icon fa fa-bullhorn bigger-100"></i> Liste GSM Secteur</a></li>'."', '0', '[-1-19-18-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste GSM Secteur' </li>";}
      // Action Task 247 - 'Détails technologie GSM'
      if(!$result_action_369 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_247, '56522ccc9297a6449c7d02e5dc5c8cfe', 'Détails technologie GSM', '".'<li><a href="#" class="this_url" data="%id%" rel="consulttechnologiegsm"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails technologie GSM</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails technologie GSM' </li>";}
      // Action Task 247 - 'Détails technologie GSM'
      if(!$result_action_370 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_247, '79a917d85e394b48b38d882845b3c775', 'Détails technologie GSM', '".'<li><a href="#" class="this_url" data="%id%" rel="consulttechnologiegsm"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails technologie GSM</a></li>'."', '0', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails technologie GSM' </li>";}
  //Task 'addgsm_technologie' 'Ajouter GSM Technologie'
  if(!$result_task_248 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addgsm_technologie', $result_insert_modul, 'addgsm_technologie','gsm', '1', 'Ajouter GSM Technologie', NULL, '1', '0', '0','form', '[-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter GSM Technologie' </li>";}
      // Action Task 248 - 'Ajouter GSM Technologie'
      if(!$result_action_371 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_248, '16411ad315d1c110f5a75617b637d2be', 'Ajouter GSM Technologie', '".NULL."', '1', '[-1-19-18-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter GSM Technologie' </li>";}
  //Task 'editgsm_technologie' 'Editer GSM Technologie'
  if(!$result_task_249 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editgsm_technologie', $result_insert_modul, 'editgsm_technologie','gsm', '1', 'Editer GSM Technologie', NULL, '1', '0', '0','form', '[1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer GSM Technologie' </li>";}
      // Action Task 249 - 'Editer GSM Technologie'
      if(!$result_action_372 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_249, 'a3ad0d2ef0e1f2ac27048d56835189a0', 'Editer GSM Technologie', '".NULL."', '1', '[-1-19-18-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer GSM Technologie' </li>";}
  //Task 'deletegsm_technologie' 'Supprimer technologie GSM'
  if(!$result_task_250 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletegsm_technologie', $result_insert_modul, 'deletegsm_technologie','gsm', '1', 'Supprimer technologie GSM', 'gsm', '1', '0', '0','exec', '[-1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer technologie GSM' </li>";}
      // Action Task 250 - 'Supprimer technologie GSM'
      if(!$result_action_373 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_250, '9c3007e547f6bb319c8d5272160d3b42', 'Supprimer technologie GSM', '".NULL."', '1', '[-1-19-18-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer technologie GSM' </li>";}
  //Task 'gsm_secteur' 'GSM Secteur'
  if(!$result_task_251 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('gsm_secteur', $result_insert_modul, 'gsm_secteur','gsm', '1', 'GSM Secteur', 'bullhorn', '1', '0', '0','list', '[-1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'GSM Secteur' </li>";}
      // Action Task 251 - 'GSM Secteur'
      if(!$result_action_374 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_251, '971d1865dd9a502da767a3b85a6da533', 'GSM Secteur', '".NULL."', '1', '[-1-19-18-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'GSM Secteur' </li>";}
      // Action Task 251 - 'Editer GSM Secteur'
      if(!$result_action_375 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_251, 'a8fadc71a73cdf1da069b4ff11d1313c', 'Editer GSM Secteur', '".'<li><a href="#" class="this_url" data="%id%" rel="editgsm_secteur"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Editer GSM Secteur</a></li>'."', '0', '[-1-19-18-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer GSM Secteur' </li>";}
      // Action Task 251 - 'Détails secteur GSM'
      if(!$result_action_376 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_251, '60edac1bb11261ae827ccd57702e0c2a', 'Détails secteur GSM', '".'<li><a href="#" class="this_url" data="%id%" rel="consultsecteurgsm"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails secteur GSM</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails secteur GSM' </li>";}
      // Action Task 251 - 'Détails secteur GSM'
      if(!$result_action_377 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_251, 'b50e422599d70176b2e7a9a844bc3082', 'Détails secteur GSM', '".'<li><a href="#" class="this_url" data="%id%" rel="consultsecteurgsm"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails secteur GSM</a></li>'."', '0', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails secteur GSM' </li>";}
  //Task 'addgsm_secteur' 'Ajouter GSM Secteur'
  if(!$result_task_252 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addgsm_secteur', $result_insert_modul, 'addgsm_secteur','gsm', '1', 'Ajouter GSM Secteur', 'bullhorn', '1', '0', '0','form', '[-1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter GSM Secteur' </li>";}
      // Action Task 252 - 'Ajouter GSM Secteur'
      if(!$result_action_378 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_252, 'b963f700889f7653f5e07771b4b81757', 'Ajouter GSM Secteur', '".NULL."', '1', '[-1-19-18-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter GSM Secteur' </li>";}
  //Task 'editgsm_secteur' 'Editer GSM Secteur'
  if(!$result_task_253 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editgsm_secteur', $result_insert_modul, 'editgsm_secteur','gsm', '1', 'Editer GSM Secteur', 'cogs', '1', '0', '0','form', '[-1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer GSM Secteur' </li>";}
      // Action Task 253 - 'Editer GSM Secteur'
      if(!$result_action_379 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_253, 'c9b7115a99697ab9d1b672a9bfa18f8c', 'Editer GSM Secteur', '".NULL."', '1', '[-1-19-18-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer GSM Secteur' </li>";}
  //Task 'deletegsm_secteur' 'Supprimer secteur GSM'
  if(!$result_task_254 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletegsm_secteur', $result_insert_modul, 'deletegsm_secteur','gsm', '1', 'Supprimer secteur GSM', 'lock', '1', '0', '0','exec', '[-1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer secteur GSM' </li>";}
      // Action Task 254 - 'Supprimer secteur GSM'
      if(!$result_action_380 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_254, '9f2857a1f150c22e537f875e5cbad25d', 'Supprimer secteur GSM', '".NULL."', '1', 'null', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer secteur GSM' </li>";}
  //Task 'validgsm' 'Valider Station GSM'
  if(!$result_task_255 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validgsm', $result_insert_modul, 'validgsm','gsm', '1', 'Valider Station GSM', 'unlock', '1', '0', '0','exec', '[-1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Station GSM' </li>";}
      // Action Task 255 - 'Valider Station GSM'
      if(!$result_action_381 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_255, '04ff6875419f6535df2a4d172556d23f', 'Valider Station GSM', '".NULL."', '1', '[-1-19-18-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Station GSM' </li>";}
  //Task 'consultgsm' 'Détails station GSM'
  if(!$result_task_256 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('consultgsm', $result_insert_modul, 'consultgsm','gsm', '1', 'Détails station GSM', 'eye', '1', '0', '0','profil', '[-1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails station GSM' </li>";}
      // Action Task 256 - 'Consulter station GSM'
      if(!$result_action_382 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_256, 'c8cbc454d586ca8a607918cd4392a810', 'Consulter station GSM', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Consulter station GSM' </li>";}
  //Task 'consultsecteurgsm' 'Détails secteur GSM'
  if(!$result_task_257 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('consultsecteurgsm', $result_insert_modul, 'consultsecteurgsm','gsm', '1', 'Détails secteur GSM', 'eye', '1', '0', '0','profil', '[-1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails secteur GSM' </li>";}
      // Action Task 257 - 'Consulter secteur GSM'
      if(!$result_action_383 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_257, '50c444fea0b54ba505c0df8f114738b7', 'Consulter secteur GSM', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Consulter secteur GSM' </li>";}
  //Task 'consulttechnologiegsm' 'Détails technologie GSM'
  if(!$result_task_258 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('consulttechnologiegsm', $result_insert_modul, 'consulttechnologiegsm','gsm', '1', 'Détails technologie GSM', 'eye', '1', '0', '0','profil', '[-1-19-18-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails technologie GSM' </li>";}
      // Action Task 258 - 'Consulter technologie GSM'
      if(!$result_action_384 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_258, 'e7d6dc522c35b1a881400a1311e9592c', 'Consulter technologie GSM', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Consulter technologie GSM' </li>";}
