<?php 
//Export Module 'installateurs' Date: 13-06-2017z
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('installateurs', 'Gestion Installateurs','installateurs','installateurs','installateurs',NULL,'0', '0', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'installateurs' </li>";}
  //Task 'installateurs' 'Gestion Installateurs'
  if(!$result_task_232 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('installateurs', $result_insert_modul, 'installateurs','installateurs', '1', 'Gestion Installateurs', 'installer', '1', '0', '0','list', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Installateurs' </li>";}
      // Action Task 232 - 'Gestion Installateurs'
      if(!$result_action_339 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_232, '4005eb8193a9ee09d7d76f0b29090291', 'Gestion Installateurs', '".NULL."', '1', '[-1-17-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Installateurs' </li>";}
      // Action Task 232 - 'Editer Installateur'
      if(!$result_action_340 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_232, '0c7a655db3043845852363b20f14a43e', 'Editer Installateur', '".'<li><a href="#" class="this_url" data="%id%" rel="editinstallateur"  ><i class="ace-icon fa fa-pencil bigger-100"></i> Editer Installateur</a></li>'."', '0', '[-1-17-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Installateur' </li>";}
      // Action Task 232 - 'Valider Installateur'
      if(!$result_action_341 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_232, 'd552061a32c7e27f883c1aa93bee12f9', 'Valider Installateur', '".'<li><a href="#" class="this_exec" data="%id%" rel="validinstallateur"  ><i class="ace-icon fa fa-lock bigger-100"></i> Valider Installateur</a></li>'."', '0', '[-1-17-]', '0', '1', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Installateur' </li>";}
      // Action Task 232 - 'Test WF'
      if(!$result_action_342 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_232, '5d9c4381ffa39b99ba193891fc7bf2ab', 'Test WF', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Test WF' </li>";}
      // Action Task 232 - 'Désactiver installateur'
      if(!$result_action_343 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_232, '31b13d915043f782cba5c915795a4c8b', 'Désactiver installateur', '".'<li><a href="#" class="this_exec" data="%id%" rel="validinstallateur"  ><i class="ace-icon fa fa-lock bigger-100"></i> Désactiver installateur</a></li>'."', '0', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver installateur' </li>";}
      // Action Task 232 - 'Détails installateur'
      if(!$result_action_344 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_232, '172d1bd007aec717430cdfdc04d17a87', 'Détails installateur', '".'<li><a href="#" class="this_url" data="%id%" rel="consultinstallateur"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails installateur</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails installateur' </li>";}
      // Action Task 232 - 'Détails installateur'
      if(!$result_action_345 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_232, '162051fd1ce0af851b6471769d9bd16d', 'Détails installateur', '".'<li><a href="#" class="this_url" data="%id%" rel="consultinstallateur"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails installateur</a></li>'."', '0', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails installateur' </li>";}
  //Task 'addinstallateur_ph' 'Ajouter Installateur'
  if(!$result_task_233 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addinstallateur_ph', $result_insert_modul, 'addinstallateur_ph','installateurs', '1', 'Ajouter Installateur', NULL, '1', '0', '0','form', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Installateur' </li>";}
      // Action Task 233 - 'Ajouter Installateur P.Physique'
      if(!$result_action_346 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_233, '9554bcd9e4f2f629b90476dd40852804', 'Ajouter Installateur P.Physique', '".NULL."', '1', '[-1-17-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Installateur P.Physique' </li>";}
  //Task 'editinstallateur' 'Editer Installateur'
  if(!$result_task_234 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editinstallateur', $result_insert_modul, 'editinstallateur','installateurs', '1', 'Editer Installateur', NULL, '1', '0', '0','form', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer Installateur' </li>";}
      // Action Task 234 - 'Editer Installateur'
      if(!$result_action_347 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_234, '25e3ea1332af00177d27d830d8099079', 'Editer Installateur', '".NULL."', '1', '[-1-17-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Installateur' </li>";}
  //Task 'validinstallateur' 'Valider Installateur'
  if(!$result_task_235 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validinstallateur', $result_insert_modul, 'validinstallateur','installateurs', '1', 'Valider Installateur', NULL, '1', '0', '0','exec', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Installateur' </li>";}
      // Action Task 235 - 'Valider Installateur'
      if(!$result_action_348 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_235, '30f47a0742878353a9c689e40cfd8f14', 'Valider Installateur', '".NULL."', '1', '[-1-17-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Installateur' </li>";}
  //Task 'addinstallateur_m' 'Ajouter Installateur'
  if(!$result_task_236 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addinstallateur_m', $result_insert_modul, 'addinstallateur_m','installateurs', '1', 'Ajouter Installateur', NULL, '1', '0', '0','form', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Installateur' </li>";}
      // Action Task 236 - 'Ajouter Installateur P.Moral'
      if(!$result_action_349 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_236, 'daa743dc99c9c9a434c318319360b861', 'Ajouter Installateur P.Moral', '".NULL."', '1', '[-1-17-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Installateur P.Moral' </li>";}
  //Task 'deleteinstallateur' 'Supprimer installateur'
  if(!$result_task_237 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteinstallateur', $result_insert_modul, 'deleteinstallateur','installateurs', '1', 'Supprimer installateur', 'lock', '1', '0', '0','exec', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer installateur' </li>";}
      // Action Task 237 - 'Supprimer installateur'
      if(!$result_action_350 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_237, 'fd6fca8522838608af4a0442b305bfc3', 'Supprimer installateur', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer installateur' </li>";}
  //Task 'consultinstallateur' 'Détails installateur'
  if(!$result_task_238 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('consultinstallateur', $result_insert_modul, 'consultinstallateur','installateurs', '1', 'Détails installateur', 'eye', '1', '0', '0','profil', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails installateur' </li>";}
      // Action Task 238 - 'Consulter installateur'
      if(!$result_action_351 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_238, 'a33bf6facdf71c54c67563a17b4a53ef', 'Consulter installateur', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Consulter installateur' </li>";}
