<?php 
//Export Module 'objectif_commercial' Date: 25-11-2018
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('objectif_commercial', 'Objectifs Commercial','objectifs/submodul/objectif_commercial','objectif_commercial','objectif_commercial','objectifs','2', '0', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'objectif_commercial' </li>";}
  //Task 'objectif_commercial' 'Objectifs Commercial'
  if(!$result_task_1107 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('objectif_commercial', $result_insert_modul, 'objectif_commercial','objectifs/submodul/objectif_commercial', '1', 'Objectifs Commercial', 'bar-chart-o', '1', '0', '0','list', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Objectifs Commercial' </li>";}
      // Action Task 1107 - 'Objectifs Commercial'
      if(!$result_action_1879 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1107, 'ce7a65f39c6a9641b7f71853ce726624', 'Objectifs Commercial','objectif_commercial', NULL, '".NULL."', '1', '[-1-2-3-7-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Objectifs Commercial' </li>";}
      // Action Task 1107 - 'Valider Objectif'
      if(!$result_action_1880 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1107, 'cab28d894596927374eabcd445f80e3f', 'Valider Objectif','valid_objectif_commercial', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="valid_objectif_commercial"  ><i class="ace-icon fa fa-check bigger-100"></i> Valider Objectif</a></li>'."', '0', '[-1-2-3-7-]', '0', '1', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Objectif' </li>";}
      // Action Task 1107 - 'Modifier Objectif'
      if(!$result_action_1881 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1107, '45378fbcf10186649eeffb9482c9fdf0', 'Modifier Objectif','edit_objectif_commercial', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="edit_objectif_commercial"  ><i class="ace-icon fa fa-pencil-square-o blue bigger-100"></i> Modifier Objectif</a></li>'."', '0', '[-1-2-3-7-]', '0', '1', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Objectif' </li>";}
      // Action Task 1107 - 'Détail Objectif Commercial'
      if(!$result_action_1882 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1107, 'af44f2001b5634f05151d6236763a241', 'Détail Objectif Commercial','detail_objectif_commercial', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detail_objectif_commercial"  ><i class="ace-icon fa fa-eye blue bigger-100"></i> Détail Objectif Commercial</a></li>'."', '0', '[-1-2-3-7-]', '0', '1', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Objectif Commercial' </li>";}
      // Action Task 1107 - 'Détail Objectif Commercial'
      if(!$result_action_1883 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1107, 'ac270a34fa2aea5779b6458579b147f1', 'Détail Objectif Commercial','detail_objectif_commercial', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detail_objectif_commercial"  ><i class="ace-icon fa fa-eye blue bigger-100"></i> Détail Objectif Commercial</a></li>'."', '0', '[-1-2-3-7-]', '1', '0', 'Objectif en cours','success','".'<span class="label label-sm label-success">Objectif en cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Objectif Commercial' </li>";}
  //Task 'add_objectif_commercial' 'Ajouter Objectif Service'
  if(!$result_task_1108 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('add_objectif_commercial', $result_insert_modul, 'add_objectif_commercial','objectifs/submodul/objectif_commercial', '1', 'Ajouter Objectif Service', 'plus', '1', '0', '0','formadd', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Objectif Service' </li>";}
      // Action Task 1108 - 'Ajouter Objectif Service'
      if(!$result_action_1884 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1108, '3d80d692290d386078773b5e70960b0d', 'Ajouter Objectif Service','add_objectif_commercial', NULL, '".NULL."', '1', '[-1-2-3-7-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Objectif Service' </li>";}
  //Task 'edit_objectif_commercial' 'Modifier Objectif'
  if(!$result_task_1109 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edit_objectif_commercial', $result_insert_modul, 'edit_objectif_commercial','objectifs/submodul/objectif_commercial', '1', 'Modifier Objectif', 'pen', '1', '0', '0','formedit', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Objectif' </li>";}
      // Action Task 1109 - 'Modifier Objectif'
      if(!$result_action_1885 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1109, '851fb22fd86860448f57e91b28b0bbc1', 'Modifier Objectif','edit_objectif_commercial', NULL, '".NULL."', '1', '[-1-2-3-7-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Objectif' </li>";}
  //Task 'valid_objectif_commercial' 'Valider Objectif'
  if(!$result_task_1110 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('valid_objectif_commercial', $result_insert_modul, 'valid_objectif_commercial','objectifs/submodul/objectif_commercial', '1', 'Valider Objectif', 'check', '1', '0', '0','exec', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Objectif' </li>";}
      // Action Task 1110 - 'Valider Objectif'
      if(!$result_action_1886 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1110, 'e455035b810042644ec403be2e066138', 'Valider Objectif','valid_objectif_commercial', NULL, '".NULL."', '1', '[-1-3-7-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Objectif' </li>";}
  //Task 'detail_objectif_commercial' 'Détail Objectif Commercial'
  if(!$result_task_1111 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detail_objectif_commercial', $result_insert_modul, 'detail_objectif_commercial','objectifs/submodul/objectif_commercial', '1', 'Détail Objectif Commercial', 'eye green', '1', '0', '0','profil', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détail Objectif Commercial' </li>";}
      // Action Task 1111 - 'Détail Objectif Commercial'
      if(!$result_action_1887 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1111, 'e9b9502d5d92a34f82c8b7ca17812de1', 'Détail Objectif Commercial','detail_objectif_commercial', NULL, '".NULL."', '1', '[-1-2-3-7-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Objectif Commercial' </li>";}
