<?php 
//Export Module 'objectif_mensuel_groupe' Date: 06-06-2020
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('objectif_mensuel_groupe', 'Objectif mensuel','objectifs/submodul/objectif_mensuel_groupe','objectif_mensuels','objectif_mensuel_groupe','objectifs','2', '0', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'objectif_mensuel_groupe' </li>";}
  //Task 'objectif_mensuel_groupe' 'Objectif mensuel'
  if(!$result_task_1271 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('objectif_mensuel_groupe', $result_insert_modul, 'objectif_mensuel_groupe','objectifs/submodul/objectif_mensuel_groupe', '1', 'Objectif mensuel', 'chart', '1', '0', '0','list', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Objectif mensuel' </li>";}
      // Action Task 1271 - 'Objectif mensuel'
      if(!$result_action_2243 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1271, '55a1e98502749d0c3ce2b646c47d2cb4', 'Objectif mensuel','objectif_mensuel_groupe', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Objectif mensuel' </li>";}
      // Action Task 1271 - 'Objectif mensuel'
      if(!$result_action_2245 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1271, '8364c7caa52e4a3351d0e071faa536b6', 'Objectif mensuel','objectif_mensuel', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="objectif_mensuel"  ><i class="ace-icon fa fa-cubes bigger-100"></i> Objectif mensuel</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '1', '1', 'Exercice  Validé','success','".'<span class="label label-sm label-success">Exercice  Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Objectif mensuel' </li>";}
      // Action Task 1271 - 'Editer Objectif'
      if(!$result_action_2265 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1271, '0ad14aca3ccb39762a5ef12c5fce5588', 'Editer Objectif','editobjectifgroupe', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editobjectifgroupe"  ><i class="ace-icon fa fa-pencil-square bigger-100"></i> Editer Objectif</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Objectif' </li>";}
      // Action Task 1271 - 'Valider objectif'
      if(!$result_action_2267 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1271, 'cd1ed395965a2486032a040726aa0416', 'Valider objectif','validerobjectif', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validerobjectif"  ><i class="ace-icon fa fa-check bigger-100"></i> Valider objectif</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider objectif' </li>";}
  //Task 'objectif_mensuel' 'Objectif mensuel détaillé'
  if(!$result_task_1272 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('objectif_mensuel', $result_insert_modul, 'objectif_mensuel','objectifs/submodul/objectif_mensuel_groupe', '1', 'Objectif mensuel détaillé', 'chart', '1', '0', '0','list', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Objectif mensuel détaillé' </li>";}
      // Action Task 1272 - 'Objectif mensuel détaillé'
      if(!$result_action_2244 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, 'bf3d06e4fef057901fb71f29023b0965', 'Objectif mensuel détaillé','objectif_mensuel', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Objectif mensuel détaillé' </li>";}
      // Action Task 1272 - 'Editer Objectif mensuel'
      if(!$result_action_2251 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, '9d5794da3a80a5171bf399f62db85813', 'Editer Objectif mensuel','edit_objectif_mensuel', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="edit_objectif_mensuel"  ><i class="ace-icon fa fa-pencil-square bigger-100"></i> Editer Objectif mensuel</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Démarrage','warning','".'<span class="label label-sm label-warning">Attente Démarrage</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Objectif mensuel' </li>";}
      // Action Task 1272 - 'Détails objectif mensuel'
      if(!$result_action_2252 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, '4b8bc915fc2c9ec0146749218646b25f', 'Détails objectif mensuel','details_objectif_mensuel', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="details_objectif_mensuel"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails objectif mensuel</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Démarrage','warning','".'<span class="label label-sm label-warning">Attente Démarrage</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails objectif mensuel' </li>";}
      // Action Task 1272 - 'Détails objectif mensuel'
      if(!$result_action_2253 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, '9c6230f9144d018e51bd8b59984e9a46', 'Détails objectif mensuel','details_objectif_mensuel', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="details_objectif_mensuel"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails objectif mensuel</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '1', '0', 'Objectif en cours','success','".'<span class="label label-sm label-success">Objectif en cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails objectif mensuel' </li>";}
      // Action Task 1272 - 'Détails objectif mensuel'
      if(!$result_action_2254 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, 'fcb29a49d2d5053b33089b5608055d12', 'Détails objectif mensuel','details_objectif_mensuel', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="details_objectif_mensuel"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails objectif mensuel</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '3', '0', 'Seuil Objectif Atteint','inverse','".'<span class="label label-sm label-inverse">Seuil Objectif Atteint</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails objectif mensuel' </li>";}
      // Action Task 1272 - 'Détails objectif mensuel'
      if(!$result_action_2255 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, 'd79ca73b81db63be43e1a9a112184ea5', 'Détails objectif mensuel','details_objectif_mensuel', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="details_objectif_mensuel"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails objectif mensuel</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '2', '0', 'Objectif terminé','info','".'<span class="label label-sm label-info">Objectif terminé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails objectif mensuel' </li>";}
      // Action Task 1272 - 'Détails objectif mensuel'
      if(!$result_action_2256 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, '3c46ad38609bf870d88ef81141fc1aad', 'Détails objectif mensuel','details_objectif_mensuel', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="details_objectif_mensuel"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails objectif mensuel</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '4', '0', 'Objectif raté','danger','".'<span class="label label-sm label-danger">Objectif raté</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails objectif mensuel' </li>";}
      // Action Task 1272 - 'Suspendre Objectif'
      if(!$result_action_2257 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, '779d2092d44ad8c0c1f4774b2d3b0972', 'Suspendre Objectif','suspendre_objectif_mensuel', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="suspendre_objectif_mensuel"  ><i class="ace-icon fa fa-ban bigger-100"></i> Suspendre Objectif</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Démarrage','warning','".'<span class="label label-sm label-warning">Attente Démarrage</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Suspendre Objectif' </li>";}
      // Action Task 1272 - 'Détails objectif mensuel'
      if(!$result_action_2258 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, 'b93e2b8f4974a809f1eacb06bbd7093a', 'Détails objectif mensuel','details_objectif_mensuel', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="details_objectif_mensuel"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails objectif mensuel</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '6', '0', 'Objectif suspendue','danger','".'<span class="label label-sm label-danger">Objectif suspendue</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails objectif mensuel' </li>";}
      // Action Task 1272 - 'Suspendre Objectif'
      if(!$result_action_2259 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, '123a616e47b6ff263b1de842c553f9bc', 'Suspendre Objectif','suspendre_objectif_mensuel', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="suspendre_objectif_mensuel"  ><i class="ace-icon fa fa-ban bigger-100"></i> Suspendre Objectif</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '1', '0', 'Objectif en cours','success','".'<span class="label label-sm label-success">Objectif en cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Suspendre Objectif' </li>";}
      // Action Task 1272 - 'Forcer commission'
      if(!$result_action_2260 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, 'f8793f580f250dcb0def286f2d677312', 'Forcer commission','force_commission_object', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="force_commission_object"  ><i class="ace-icon fa fa-gift bigger-100"></i> Forcer commission</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '4', '0', 'Objectif raté','danger','".'<span class="label label-sm label-danger">Objectif raté</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Forcer commission' </li>";}
      // Action Task 1272 - 'Détails objectif mensuel'
      if(!$result_action_2261 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, '45a997daa63258e5ad71ed3ad33ecdf8', 'Détails objectif mensuel','details_objectif_mensuel', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="details_objectif_mensuel"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails objectif mensuel</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '5', '0', 'Commission forcée','inverse','".'<span class="label label-sm label-inverse">Commission forcée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails objectif mensuel' </li>";}
      // Action Task 1272 - 'Détails objectif mensuel'
      if(!$result_action_2262 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1272, 'f8d621571e4fc8bd0d529496968e113f', 'Détails objectif mensuel','details_objectif_mensuel', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="details_objectif_mensuel"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails objectif mensuel</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '7', '0', 'Objectif atteint & payé','info','".'<span class="label label-sm label-info">Objectif atteint & payé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails objectif mensuel' </li>";}
  //Task 'add_objectif_mensuel' 'Ajouter Objectif mensuel'
  if(!$result_task_1273 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('add_objectif_mensuel', $result_insert_modul, 'add_objectif_mensuel','objectifs/submodul/objectif_mensuel_groupe', '1', 'Ajouter Objectif mensuel', 'eye', '1', '0', '0','formadd', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Objectif mensuel' </li>";}
      // Action Task 1273 - 'Ajouter Objectif mensuel'
      if(!$result_action_2246 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1273, '8b3e3aa7cc9e4351b9284cc15354d66a', 'Ajouter Objectif mensuel','add_objectif_mensuel', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Objectif mensuel' </li>";}
  //Task 'edit_objectif_mensuel' 'Editer Objectif mensuel'
  if(!$result_task_1274 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edit_objectif_mensuel', $result_insert_modul, 'edit_objectif_mensuel','objectifs/submodul/objectif_mensuel_groupe', '1', 'Editer Objectif mensuel', 'eye', '1', '0', '0','formedit', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer Objectif mensuel' </li>";}
      // Action Task 1274 - 'Editer Objectif mensuel'
      if(!$result_action_2247 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1274, '7f596437814697c7a051ae92c2d0dee6', 'Editer Objectif mensuel','edit_objectif_mensuel', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Objectif mensuel' </li>";}
  //Task 'details_objectif_mensuel' 'Détails objectif mensuel'
  if(!$result_task_1275 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('details_objectif_mensuel', $result_insert_modul, 'details_objectif_mensuel','objectifs/submodul/objectif_mensuel_groupe', '1', 'Détails objectif mensuel', 'eye', '1', '0', '0','profil', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails objectif mensuel' </li>";}
      // Action Task 1275 - 'Détails objectif mensuel'
      if(!$result_action_2248 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1275, '8b503789312df443678798ef55891969', 'Détails objectif mensuel','details_objectif_mensuel', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails objectif mensuel' </li>";}
  //Task 'force_commission_object' 'Forcer commission'
  if(!$result_task_1276 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('force_commission_object', $result_insert_modul, 'force_commission_object','objectifs/submodul/objectif_mensuel_groupe', '1', 'Forcer commission', 'eye', '1', '0', '0','exec', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Forcer commission' </li>";}
      // Action Task 1276 - 'Forcer commission'
      if(!$result_action_2249 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1276, '18209f748cb598960deaa97d5bd257fe', 'Forcer commission','force_commission_object', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Forcer commission' </li>";}
  //Task 'suspendre_objectif_mensuel' 'Suspendre Objectif'
  if(!$result_task_1277 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('suspendre_objectif_mensuel', $result_insert_modul, 'suspendre_objectif_mensuel','objectifs/submodul/objectif_mensuel_groupe', '1', 'Suspendre Objectif', 'eye', '1', '0', '0','exec', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Suspendre Objectif' </li>";}
      // Action Task 1277 - 'Suspendre Objectif'
      if(!$result_action_2250 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1277, '9445ee8ec35c39bd3347607bb3871e68', 'Suspendre Objectif','suspendre_objectif_mensuel', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Suspendre Objectif' </li>";}
  //Task 'addobjectifgroupe' 'Ajouter Objetif '
  if(!$result_task_1278 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addobjectifgroupe', $result_insert_modul, 'addobjectifgroupe','objectifs/submodul/objectif_mensuel_groupe', '1', 'Ajouter Objetif ', 'pencil', '1', '0', '0','formadd', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Objetif ' </li>";}
      // Action Task 1278 - 'Ajouter Objetif '
      if(!$result_action_2263 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1278, 'fb21fbd14ec0d02fe3eccfc9e730192f', 'Ajouter Objetif ','addobjectifgroupe', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','success','".'<span class="label label-sm label-success">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Objetif ' </li>";}
  //Task 'editobjectifgroupe' 'Editer Objectif'
  if(!$result_task_1279 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editobjectifgroupe', $result_insert_modul, 'editobjectifgroupe','objectifs/submodul/objectif_mensuel_groupe', '1', 'Editer Objectif', 'eye', '1', '0', '0','formedit', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer Objectif' </li>";}
      // Action Task 1279 - 'Editer Objectif'
      if(!$result_action_2264 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1279, 'd12427160216724c81111bf912ba758d', 'Editer Objectif','editobjectifgroupe', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Objectif' </li>";}
  //Task 'validerobjectif' 'Valider objectif'
  if(!$result_task_1280 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validerobjectif', $result_insert_modul, 'validerobjectif','objectifs/submodul/objectif_mensuel_groupe', '1', 'Valider objectif', 'eye', '1', '0', '0','exec', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider objectif' </li>";}
      // Action Task 1280 - 'Valider objectif'
      if(!$result_action_2266 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1280, '2ca5329dbaf1d76c6f3be864888d30b5', 'Valider objectif','validerobjectif', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider objectif' </li>";}
