<?php 
//Export Module 'proforma' Date: 29-09-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('proforma', 'Gestion Proforma','vente/submodul/proforma','proforma','proforma','vente','2', '0', '[-1-2-3-5-4-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'proforma' </li>";}
  //Task 'proforma' 'Gestion Proforma'
  if(!$result_task_505 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('proforma', $result_insert_modul, 'proforma','vente/submodul/proforma', '1', 'Gestion Proforma', 'book', '1', '0', '0','list', '[-1-2-3-5-4-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Proforma' </li>";}
      // Action Task 505 - 'Gestion Proforma'
      if(!$result_action_773 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_505, '1eb847d87adcad78d5e951e6110061e5', 'Gestion Proforma','proforma', NULL, '".NULL."', '0', '[-1-2-3-5-4-]', '0', '0', 'Attente validation','success','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Proforma' </li>";}
      // Action Task 505 - 'Editer proforma'
      if(!$result_action_778 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_505, '44ef6849d8d5d17d8e0535187e923d32', 'Editer proforma','editproforma', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editproforma"  ><i class="ace-icon fa fa-pen blue bigger-100"></i> Editer proforma</a></li>'."', '0', '[-1-2-3-5-]', '0', '1', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer proforma' </li>";}
      // Action Task 505 - 'Valider Proforma'
      if(!$result_action_779 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_505, 'b7ce06be726011362a271678547a803c', 'Valider Proforma','validproforma', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validproforma"  ><i class="ace-icon fa fa-check bigger-100"></i> Valider Proforma</a></li>'."', '0', '[-1-3-5-]', '0', '1', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Proforma' </li>";}
      // Action Task 505 - 'Détail Proforma'
      if(!$result_action_781 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_505, 'abd8c50f1d2ef4beeeddb68a72973587', 'Détail Proforma','viewproforma', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewproforma"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détail Proforma</a></li>'."', '0', '[-1-2-3-5-]', '0', '1', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Proforma' </li>";}
      // Action Task 505 - 'Détail Proforma'
      if(!$result_action_782 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_505, 'e20d83df90355eca2a65f56a2556601f', 'Détail Proforma','viewproforma', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="viewproforma"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détail Proforma</a></li>'."', '0', '[-1-2-3-5-]', '1', '0', 'Validée','success','".'<span class="label label-sm label-success">Validée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Proforma' </li>";}
  //Task 'addproforma' 'Ajouter pro-forma'
  if(!$result_task_506 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addproforma', $result_insert_modul, 'addproforma','vente/submodul/proforma', '1', 'Ajouter pro-forma', 'plus', '1', '0', '0','form', '[-1-2-3-5-4-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter pro-forma' </li>";}
      // Action Task 506 - 'Ajouter pro-forma'
      if(!$result_action_774 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_506, 'd5a6338765b9eab63104b59f01c06114', 'Ajouter pro-forma','addproforma', NULL, '".NULL."', '0', '[-1-2-3-5-]', '0', '0', 'Brouillon','warning','".'<span class="label label-sm label-warning">Brouillon</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter pro-forma' </li>";}
  //Task 'editproforma' 'Editer proforma'
  if(!$result_task_507 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editproforma', $result_insert_modul, 'editproforma','vente/submodul/proforma', '1', 'Editer proforma', 'pen', '1', '0', '0','form', '[-1-2-3-5-4-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer proforma' </li>";}
      // Action Task 507 - 'Editer proforma'
      if(!$result_action_775 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_507, '95831bde77bc886d6ab4dd5e734de743', 'Editer proforma','editproforma', NULL, '".NULL."', '0', '[-1-2-3-5-]', '0', '0', 'Brouillon','warning','".'<span class="label label-sm label-warning">Brouillon</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer proforma' </li>";}
  //Task 'add_detailproforma' 'Ajouter détail proforma'
  if(!$result_task_508 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('add_detailproforma', $result_insert_modul, 'add_detailproforma','vente/submodul/proforma', '1', 'Ajouter détail proforma', 'plus', '1', '0', '0','form', '[-1-2-3-5-4-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter détail proforma' </li>";}
      // Action Task 508 - 'Ajouter détail proforma'
      if(!$result_action_776 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_508, 'cbb4e1efa1c05b42d25a3a6bcab038a2', 'Ajouter détail proforma','adddetailproforma', NULL, '".NULL."', '0', '[-1-2-3-5-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter détail proforma' </li>";}
  //Task 'validproforma' 'valider Proforma'
  if(!$result_task_509 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validproforma', $result_insert_modul, 'validproforma','vente/submodul/proforma', '1', 'valider Proforma', 'check', '1', '0', '0','exec', '[-1-2-3-5-4-]')")){$this->error = false; $this->log .= "<li> Error Import task 'valider Proforma' </li>";}
      // Action Task 509 - 'valider Proforma'
      if(!$result_action_777 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_509, 'e9f745054778257a255452c6609461a0', 'valider Proforma','validproforma', NULL, '".NULL."', '0', '[-1-2-3-5-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'valider Proforma' </li>";}
  //Task 'viewproforma' 'Détail Pro-forma'
  if(!$result_task_510 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('viewproforma', $result_insert_modul, 'viewproforma','vente/submodul/proforma', '1', 'Détail Pro-forma', 'eye', '1', '0', '0','profil', '[-1-2-3-5-4-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détail Pro-forma' </li>";}
      // Action Task 510 - 'Détail Pro-forma'
      if(!$result_action_780 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_510, 'defef148c404c7e6ac79e4783e0a7ab7', 'Détail Pro-forma','viewproforma', NULL, '".NULL."', '0', '[-1-2-3-5-]', '0', '0', 'Attente validation','warning','".'Attente validation'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détail Pro-forma' </li>";}
  //Task 'edit_detailproforma' 'Editer détail proforma'
  if(!$result_task_511 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edit_detailproforma', $result_insert_modul, 'edit_detailproforma','vente/submodul/proforma', '1', 'Editer détail proforma', 'pen', '1', '0', '0','form', '[-1-2-3-5-4-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer détail proforma' </li>";}
      // Action Task 511 - 'Editer détail proforma'
      if(!$result_action_783 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_511, '53008d64edf241c937a06f03eff139aa', 'Editer détail proforma','edit_detailproforma', NULL, '".NULL."', '0', '[-1-2-3-5-]', '0', '0', 'Attente validation','warning','".'<span class="label label-sm label-warning">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer détail proforma' </li>";}
