<?php 
//Export Module 'prospects' Date: 27-10-2019
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('prospects', 'Gestion Prospects','prospects/main','prospects','prospects',NULL,'0', '0', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'prospects' </li>";}
  //Task 'prospects' 'Gestion Prospects'
  if(!$result_task_1157 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('prospects', $result_insert_modul, 'prospects','prospects/main', '1', 'Gestion Prospects', 'book', '1', '0', '0','list', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Prospects' </li>";}
      // Action Task 1157 - 'Gestion Prospects'
      if(!$result_action_1988 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1157, '35795f859b26f640084aefc6651fa2ca', 'Gestion Prospects','prospects', NULL, '".NULL."', '0', '[-1-2-3-7-]', '0', '0', 'En cours','warning','".'<span class="label label-sm label-warning">En cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Prospects' </li>";}
      // Action Task 1157 - 'Modifier Prospect'
      if(!$result_action_1992 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1157, '44b4996ee611f1691291e22657f10296', 'Modifier Prospect','editprospect', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editprospect"  ><i class="ace-icon fa fa-pencil-square-o blue bigger-100"></i> Modifier Prospect</a></li>'."', '0', '[-1-2-3-7-]', '0', '0', 'En cours','warning','".'<span class="label label-sm label-warning">En cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Prospect' </li>";}
      // Action Task 1157 - 'Supprimer Prospect'
      if(!$result_action_1994 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1157, 'ee2934075223bc5fe30b13c3490fdc3d', 'Supprimer Prospect','deleteprospect', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="deleteprospect"  ><i class="ace-icon fa fa-trash-o red bigger-100"></i> Supprimer Prospect</a></li>'."', '0', '[-1-2-3-7-]', '0', '0', 'En cours','warning','".'<span class="label label-sm label-warning">En cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Prospect' </li>";}
      // Action Task 1157 - 'Gagner Prospect'
      if(!$result_action_1996 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1157, '5c6b628f794e236454dc39019525c835', 'Gagner Prospect','addclient', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="addclients"><i class="ace-icon fa fa-check-square-o green bigger-100"></i> Gagner Prospect</a></li>'."', '0', '[-1-2-3-7-]', '0', '1', 'En cours','warning','".'<span class="label label-sm label-warning">En cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gagner Prospect' </li>";}
      // Action Task 1157 - 'Perdre Prospect'
      if(!$result_action_1998 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1157, '4892f0c0e728b85656be7452ffa97115', 'Perdre Prospect','perdreprospect', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%,%offre%" rel="perdreprospect"  ><i class="ace-icon fa fa-close red bigger-100"></i> Perdre Prospect</a></li>'."', '0', '[-1-2-3-7-]', '0', '1', 'En cours','warning','".'<span class="label label-sm label-warning">En cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Perdre Prospect' </li>";}
      // Action Task 1157 - 'Détails Prospect'
      if(!$result_action_2001 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1157, 'f36da9502791e866a7b5af6303fc3a92', 'Détails Prospect','detailsprospect', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsprospect"  ><i class="ace-icon fa fa-eye pink bigger-100"></i> Détails Prospect</a></li>'."', '0', '[-1-2-3-7-]', '0', '0', 'En cours','warning','".'<span class="label label-sm label-warning">En cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Prospect' </li>";}
      // Action Task 1157 - 'Détails Prospect'
      if(!$result_action_2002 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1157, 'd4fb413d3989e5d9a5045ec08a2cbd8e', 'Détails Prospect','detailsprospect', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsprospect"  ><i class="ace-icon fa fa-eye pink bigger-100"></i> Détails Prospect</a></li>'."', '0', '[-1-2-3-7-]', '1', '0', 'Gagné','success','".'<span class="label label-sm label-success">Gagné</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Prospect' </li>";}
      // Action Task 1157 - 'Détails Prospect'
      if(!$result_action_2003 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1157, 'e6875d37dd995d388ca51c732627cffc', 'Détails Prospect','detailsprospect', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsprospect"  ><i class="ace-icon fa fa-eye pink bigger-100"></i> Détails Prospect</a></li>'."', '0', '[-1-2-3-7-]', '2', '0', 'Perdu','danger','".'<span class="label label-sm label-danger">Perdu</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Prospect' </li>";}
      // Action Task 1157 - 'Détails Prospect'
      if(!$result_action_2005 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1157, '284726eb92d58b173978a1ae833d4d83', 'Détails Prospect','detailsprospect', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsprospect"  ><i class="ace-icon fa fa-eye pink bigger-100"></i> Détails Prospect</a></li>'."', '0', '[-1-2-3-7-]', '100', '0', 'Prospect Archivé','inverse','".'<span class="label label-sm label-inverse">Prospect Archivé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Prospect' </li>";}
  //Task 'addprospects' 'Ajouter Prospect'
  if(!$result_task_1158 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addprospects', $result_insert_modul, 'addprospects','prospects/main', '1', 'Ajouter Prospect', 'book', '1', '0', '0','formadd', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Prospect' </li>";}
      // Action Task 1158 - 'Ajouter Prospect'
      if(!$result_action_1989 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1158, '45fb560b2dc38ead373200598df729e3', 'Ajouter Prospect','addprospects', NULL, '".NULL."', '1', '[-1-2-3-7-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Prospect' </li>";}
  //Task 'editprospect' 'Modifier Prospect'
  if(!$result_task_1159 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editprospect', $result_insert_modul, 'editprospect','prospects/main', '1', 'Modifier Prospect', 'pencil-square-o blue', '1', '0', '0','formedit', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Prospect' </li>";}
      // Action Task 1159 - 'Modifier Prospect'
      if(!$result_action_1990 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1159, '27e42ebcbf946c0b9ef6de230d6fcf98', 'Modifier Prospect','editprospect', NULL, '".NULL."', '1', '[-1-2-3-7-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Prospect' </li>";}
  //Task 'deleteprospect' 'Supprimer Prospect'
  if(!$result_task_1160 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteprospect', $result_insert_modul, 'deleteprospect','prospects/main', '1', 'Supprimer Prospect', 'trash-o red', '1', '0', '0','exec', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Prospect' </li>";}
      // Action Task 1160 - 'Supprimer Prospect'
      if(!$result_action_1991 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1160, '2a8d0212c88a6409c87983a18dba7693', 'Supprimer Prospect','deleteprospect', NULL, '".NULL."', '1', '[-1-2-3-7-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Prospect' </li>";}
  //Task 'validprospect' 'Valider Prospect'
  if(!$result_task_1161 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validprospect', $result_insert_modul, 'validprospect','prospects/main', '1', 'Valider Prospect', 'check-square-o green', '1', '0', '0','profil', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Prospect' </li>";}
      // Action Task 1161 - 'Valider Prospect'
      if(!$result_action_1995 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1161, '115227c51797353844ea7dd70b76db41', 'Valider Prospect','validprospect', NULL, '".NULL."', '1', '[-1-2-3-7-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Prospect' </li>";}
  //Task 'perdreprospect' 'Perdre Prospect'
  if(!$result_task_1162 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('perdreprospect', $result_insert_modul, 'perdreprospect','prospects/main', '1', 'Perdre Prospect', 'close red', '1', '0', '0','exec', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Perdre Prospect' </li>";}
      // Action Task 1162 - 'Perdre Prospect'
      if(!$result_action_1999 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1162, '5b203d047818e85d677ead0cffa66438', 'Perdre Prospect','perdreprospect', NULL, '".NULL."', '1', '[-1-2-3-7-]', '0', '0', 'En cours','warning','".'<span class="label label-sm label-warning">En cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Perdre Prospect' </li>";}
  //Task 'detailsprospect' 'Détails Prospect'
  if(!$result_task_1163 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsprospect', $result_insert_modul, 'detailsprospect','prospects/main', '1', 'Détails Prospect', 'eye pink', '1', '0', '0','profil', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails Prospect' </li>";}
      // Action Task 1163 - 'Détails Prospect'
      if(!$result_action_2000 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1163, '6c118e9d051f7df327a0425adcc99043', 'Détails Prospect','detailsprospect', NULL, '".NULL."', '1', '[-1-2-3-7-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Prospect' </li>";}
  //Task 'archiveprospects' 'Archiver Prospect'
  if(!$result_task_1164 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('archiveprospects', $result_insert_modul, 'archiveprospects','prospects/main', '1', 'Archiver Prospect', 'archive', '1', '0', '0','exec', '[-1-2-3-7-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Archiver Prospect' </li>";}
      // Action Task 1164 - 'Archiver Prospect'
      if(!$result_action_2004 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1164, '0bdfb332fbd927003274d4115a805c59', 'Archiver Prospect','archiveprospect', NULL, '".NULL."', '1', '[-1-2-3-]', '1', '0', 'Gagné','success','".'<span class="label label-sm label-success">Gagné</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Archiver Prospect' </li>";}
