<?php 
//Export Module 'regions' Date: 14-09-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('regions', 'Gestion des régions','Systeme/settings/regions','ref_region','regions','Systeme','1', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'regions' </li>";}
  //Task 'regions' 'Gestion des régions'
  if(!$result_task_400 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('regions', $result_insert_modul, 'regions','Systeme/settings/regions', '1', 'Gestion des régions', 'cogs', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion des régions' </li>";}
      // Action Task 400 - 'Gestion des régions'
      if(!$result_action_598 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_400, 'd57b16b3aad4ce59f909609246c4fd36', 'Gestion des régions','regions', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion des régions' </li>";}
      // Action Task 400 - 'Modifier région'
      if(!$result_action_603 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_400, 'd2e007184668dd70b9bae44d46d28ded', 'Modifier région','editregion', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editregion"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier région</a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier région' </li>";}
      // Action Task 400 - 'Valider région'
      if(!$result_action_604 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_400, 'e74403c99ac8325b78735c531a20442f', 'Valider région','validregion', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validregion"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Valider région</a></li>'."', '0', '[-1-]', '0', '1', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider région' </li>";}
      // Action Task 400 - 'Désactiver région'
      if(!$result_action_605 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_400, '7397a0fab078728bd5c53be61022d5ce', 'Désactiver région','validregion', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validregion"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Désactiver région</a></li>'."', '0', '[-1-]', '1', '0', 'Région Validée','success','".'<span class="label label-sm label-success">Région Validée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver région' </li>";}
  //Task 'addregion' 'Ajouter région'
  if(!$result_task_401 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addregion', $result_insert_modul, 'addregion','Systeme/settings/regions', '1', 'Ajouter région', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter région' </li>";}
      // Action Task 401 - 'Ajouter région'
      if(!$result_action_599 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_401, '0237bd41cf70c3529681b4ccb041f1fd', 'Ajouter région','addregion', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter région' </li>";}
  //Task 'editregion' 'Modifier région'
  if(!$result_task_402 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editregion', $result_insert_modul, 'editregion','Systeme/settings/regions', '1', 'Modifier région', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier région' </li>";}
      // Action Task 402 - 'Modifier région'
      if(!$result_action_600 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_402, '6d290f454da473cb8a557829a410c3f1', 'Modifier région','editregion', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier région' </li>";}
  //Task 'validregion' 'Valider région'
  if(!$result_task_403 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validregion', $result_insert_modul, 'validregion','Systeme/settings/regions', '1', 'Valider région', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider région' </li>";}
      // Action Task 403 - 'Valider région'
      if(!$result_action_601 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_403, '008cd9ea5767c739675fef4e1261cfe8', 'Valider région','validregion', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider région' </li>";}
  //Task 'deleteregion' 'Supprimer région'
  if(!$result_task_404 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteregion', $result_insert_modul, 'deleteregion','Systeme/settings/regions', '1', 'Supprimer région', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer région' </li>";}
      // Action Task 404 - 'Supprimer région'
      if(!$result_action_602 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_404, 'fc477e6a4c90cd427ae81e555c11d6a9', 'Supprimer région','deleteregion', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer région' </li>";}
