<?php 
//Export Module 'revendeurs' Date: 13-06-2017z
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('revendeurs', 'Gestion Revendeurs','revendeurs','revendeurs','revendeurs',NULL,'0', '0', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'revendeurs' </li>";}
  //Task 'revendeurs' 'Gestion Revendeurs'
  if(!$result_task_279 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('revendeurs', $result_insert_modul, 'revendeurs','revendeurs', '1', 'Gestion Revendeurs', 'vendor', '1', '0', '0','list', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Revendeurs' </li>";}
      // Action Task 279 - 'Gestion Revendeurs'
      if(!$result_action_416 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_279, '34f0b6f81efecc4b4b5977af59ea8fa2', 'Gestion Revendeurs', '".NULL."', '1', '[-1-17-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Revendeurs' </li>";}
      // Action Task 279 - 'Editer revendeur'
      if(!$result_action_417 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_279, '0e9f4157acc1863f63e39e84cd6f12d7', 'Editer revendeur', '".'<li><a href="#" class="this_url" data="%id%" rel="editrevendeur"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Editer revendeur</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer revendeur' </li>";}
      // Action Task 279 - 'Valider revendeur'
      if(!$result_action_418 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_279, 'ee68399991a48d98a96694cdd0ec9878', 'Valider revendeur', '".'<li><a href="#" class="this_exec" data="%id%" rel="validrevendeur"  ><i class="ace-icon fa fa-lock bigger-100"></i> Valider revendeur</a></li>'."', '0', '[-1-]', '0', '1', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider revendeur' </li>";}
      // Action Task 279 - 'Désactiver revendeur'
      if(!$result_action_419 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_279, '460dce28895299f98d50a7c5be337763', 'Désactiver revendeur', '".'<li><a href="#" class="this_exec" data="%id%" rel="validrevendeur"  ><i class="ace-icon fa fa-lock bigger-100"></i> Désactiver revendeur</a></li>'."', '0', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver revendeur' </li>";}
      // Action Task 279 - 'Détails revendeur'
      if(!$result_action_420 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_279, 'b209c4bd543187abf81ae01eaafea761', 'Détails revendeur', '".'<li><a href="#" class="this_url" data="%id%" rel="consultrevendeur"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails revendeur</a></li>'."', '0', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails revendeur' </li>";}
      // Action Task 279 - 'Détails revendeur'
      if(!$result_action_421 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_279, '40667f3348f62289e2c9d54e3285baed', 'Détails revendeur', '".'<li><a href="#" class="this_url" data="%id%" rel="consultrevendeur"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails revendeur</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails revendeur' </li>";}
  //Task 'addrevendeur' 'Ajouter revendeur'
  if(!$result_task_280 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addrevendeur', $result_insert_modul, 'addrevendeur','revendeurs', '1', 'Ajouter revendeur', 'vendor', '1', '0', '0','form', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter revendeur' </li>";}
      // Action Task 280 - 'Ajouter revendeur'
      if(!$result_action_422 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_280, 'db838b80117d46ddad883759f21b3ad0', 'Ajouter revendeur', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter revendeur' </li>";}
  //Task 'editrevendeur' 'Editer revendeur'
  if(!$result_task_281 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editrevendeur', $result_insert_modul, 'editrevendeur','revendeurs', '1', 'Editer revendeur', 'cogs', '1', '0', '0','form', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer revendeur' </li>";}
      // Action Task 281 - 'Editer revendeur'
      if(!$result_action_423 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_281, '3f395363832b5b0c90a591658752ef0e', 'Editer revendeur', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer revendeur' </li>";}
  //Task 'validrevendeur' 'Valider revendeur'
  if(!$result_task_282 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validrevendeur', $result_insert_modul, 'validrevendeur','revendeurs', '1', 'Valider revendeur', 'lock', '1', '0', '0','exec', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider revendeur' </li>";}
      // Action Task 282 - 'Valider revendeur'
      if(!$result_action_424 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_282, '34bb0df8d70a695a6c8d65643579f81f', 'Valider revendeur', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider revendeur' </li>";}
  //Task 'deleterevendeur' 'Supprimer revendeur'
  if(!$result_task_283 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleterevendeur', $result_insert_modul, 'deleterevendeur','revendeurs', '1', 'Supprimer revendeur', 'lock', '1', '0', '0','exec', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer revendeur' </li>";}
      // Action Task 283 - 'Supprimer revendeur'
      if(!$result_action_425 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_283, 'f094a2be55e84e9ed419436d9fc14fa3', 'Supprimer revendeur', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer revendeur' </li>";}
  //Task 'consultrevendeur' 'Détails revendeur'
  if(!$result_task_284 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('consultrevendeur', $result_insert_modul, 'consultrevendeur','revendeurs', '1', 'Détails revendeur', 'eye', '1', '0', '0','profil', '[-1-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails revendeur' </li>";}
      // Action Task 284 - 'Consulter revendeur'
      if(!$result_action_426 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_284, '4ca3ecd6fd066731450caf00f4023fa1', 'Consulter revendeur', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Consulter revendeur' </li>";}
