<?php 
//Export Module 'sys_setting' Date: 07-10-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('sys_setting', 'Paramètrage Système','Systeme/settings/sys_setting','sys','sys_setting','Systeme','1', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'sys_setting' </li>";}
  //Task 'sys_setting' 'Paramètrage Système'
  if(!$result_task_538 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('sys_setting', $result_insert_modul, 'sys_setting','Systeme/settings/sys_setting', '1', 'Paramètrage Système', 'setting', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Paramètrage Système' </li>";}
      // Action Task 538 - 'Paramètrage Système'
      if(!$result_action_789 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_538, 'a1c5a2657cc1b2ff6f85c6fe8f1c51ac', 'Paramètrage Système','sys_setting', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Rien','success','".'<span class="label label-sm label-success">Rien</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Paramètrage Système' </li>";}
      // Action Task 538 - 'Editer paramètre'
      if(!$result_action_793 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_538, 'de6285d9c0027ff8bccdf2af385ac337', 'Editer paramètre','edit_sys_setting', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="edit_sys_setting"  ><i class="ace-icon fa fa-pen blue bigger-100"></i> Editer paramètre</a></li>'."', '0', '[-1-]', '1', '0', 'Active','success','".'<span class="label label-sm label-success">Active</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer paramètre' </li>";}
  //Task 'add_sys_setting' 'Ajouter Paramètre'
  if(!$result_task_539 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('add_sys_setting', $result_insert_modul, 'add_sys_setting','Systeme/settings/sys_setting', '1', 'Ajouter Paramètre', 'plus', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Paramètre' </li>";}
      // Action Task 539 - 'Ajouter Paramètre'
      if(!$result_action_790 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_539, '82f83d9d3d30fdef00d4c3ef96f0f899', 'Ajouter Paramètre','add_sys_setting', NULL, '".NULL."', '0', '[-1-]', '1', '0', 'Confirmé','success','".'<span class="label label-sm label-success">Confirmé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Paramètre' </li>";}
  //Task 'edit_sys_setting' 'Editer paramètre'
  if(!$result_task_540 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edit_sys_setting', $result_insert_modul, 'edit_sys_setting','Systeme/settings/sys_setting', '1', 'Editer paramètre', 'pen', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer paramètre' </li>";}
      // Action Task 540 - 'Editer paramètre'
      if(!$result_action_791 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_540, 'f0e54f346e9dcfdff65274709ce2c8ca', 'Editer paramètre','edit_sys_setting', NULL, '".NULL."', '0', '[-1-]', '1', '0', 'Validé','success','".'<span class="label label-sm label-success">Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer paramètre' </li>";}
  //Task 'delete_sys_setting' 'Supprimer Paramètre'
  if(!$result_task_541 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('delete_sys_setting', $result_insert_modul, 'delete_sys_setting','Systeme/settings/sys_setting', '1', 'Supprimer Paramètre', 'trash', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Paramètre' </li>";}
      // Action Task 541 - 'Supprimer Paramètre'
      if(!$result_action_792 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_541, 'aaccd24eaf085b8f18115c9c7653d401', 'Supprimer Paramètre','delete_sys_setting', NULL, '".NULL."', '0', '[-1-]', '1', '0', 'Active','success','".'<span class="label label-sm label-success">Active</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Paramètre' </li>";}
