<?php 
//Export Module 'taux_change' Date: 27-12-2019
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('taux_change', 'Gestion Taux Change','Systeme/settings/taux_change','sys_taux_change','taux_change','Systeme','1', '0', '[-1-3-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'taux_change' </li>";}
  //Task 'taux_change' 'Gestion Taux Change'
  if(!$result_task_1166 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('taux_change', $result_insert_modul, 'taux_change','Systeme/settings/taux_change', '1', 'Gestion Taux Change', 'money', '1', '0', '0','list', '[-1-3-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Taux Change' </li>";}
      // Action Task 1166 - 'Gestion Taux Change'
      if(!$result_action_2007 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1166, 'fa971e75b5756bb1f4184742bc12da7b', 'Gestion Taux Change','taux_change', NULL, '".NULL."', '1', '[-1-3-]', '0', '0', 'Taux Actuel','success','".'<span class="label label-sm label-success">Taux Actuel</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Taux Change' </li>";}
      // Action Task 1166 - 'Actualiser Taux Change'
      if(!$result_action_2009 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1166, '22a4f56da133381e1f4c0d0611160595', 'Actualiser Taux Change','refresh_taux_change', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="refresh_taux_change"  ><i class="ace-icon fa fa-pencil-square-o blue bigger-100"></i> Actualiser Taux Change</a></li>'."', '0', '[-1-3-]', '0', '0', 'Taux Actuel','success','".'<span class="label label-sm label-success">Taux Actuel</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Actualiser Taux Change' </li>";}
  //Task 'refresh_taux_change' 'Actualiser Taux Change'
  if(!$result_task_1167 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('refresh_taux_change', $result_insert_modul, 'refresh_taux_change','Systeme/settings/taux_change', '1', 'Actualiser Taux Change', 'pencil-square-o blue', '1', '0', '0','formedit', '[-1-3-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Actualiser Taux Change' </li>";}
      // Action Task 1167 - 'Actualiser Taux Change'
      if(!$result_action_2008 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1167, '00a1564de31bab60c6248f1680789164', 'Actualiser Taux Change','refresh_taux_change', NULL, '".NULL."', '1', '[-1-3-]', '0', '0', 'Taux Actuel','success','".'<span class="label label-sm label-success">Taux Actuel</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Actualiser Taux Change' </li>";}
