<?php 
//Export Module 'tickets' Date: 01-08-2018
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('tickets', 'Gestion Tickets','tickets/main','tickets','tickets',NULL,'0', '0', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'tickets' </li>";}
  //Task 'tickets' 'Gestion Tickets'
  if(!$result_task_812 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('tickets', $result_insert_modul, 'tickets','tickets/main', '1', 'Gestion Tickets', 'bookmark ', '1', '0', '0','list', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Tickets' </li>";}
      // Action Task 812 - 'Gestion Tickets '
      if(!$result_action_1325 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_812, '558708106fa0f9c46f98e4d1e5fdf191', 'Gestion Tickets ','tickets', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Affectation','warning','".'<span class="label label-sm label-warning">Attente Affectation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Tickets ' </li>";}
      // Action Task 812 - 'Modifier ticket   '
      if(!$result_action_1326 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_812, '5f239991de8d679e13e20e7a1a6c8433', 'Modifier ticket   ','editticket', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editticket"  ><i class="ace-icon fa fa-pencil-square-o bigger-100"></i> Modifier ticket   </a></li>'."', '0', '[-1-]', '0', '0', 'Attente Affectation','warning','".'<span class="label label-sm label-warning">Attente Affectation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier ticket   ' </li>";}
      // Action Task 812 - 'Affecter ticket '
      if(!$result_action_1327 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_812, 'd0f2728310c81c3c323da9c3ec91d998', 'Affecter ticket ','affecttechnicien', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="affecttechnicien"  ><i class="ace-icon fa fa-fire bigger-100"></i> Affecter ticket </a></li>'."', '0', '[-1-]', '0', '0', 'Attente Affectation','warning','".'<span class="label label-sm label-warning">Attente Affectation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Affecter ticket ' </li>";}
      // Action Task 812 - 'Détails ticket'
      if(!$result_action_1328 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_812, 'db7e28569171b1218d7aa12f75684aa2', 'Détails ticket','detailsticket', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsticket"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails ticket</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Affectation','warning','".'<span class="label label-sm label-warning">Attente Affectation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails ticket' </li>";}
      // Action Task 812 - 'Détails ticket   '
      if(!$result_action_1329 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_812, '7813165051eca9e0dd0809ffc571b721', 'Détails ticket   ','detailsticket', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsticket"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails ticket   </a></li>'."', '0', '[-1-]', '1', '0', 'Traitement En Cours','success','".'<span class="label label-sm label-success">Traitement En Cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails ticket   ' </li>";}
      // Action Task 812 - 'Reaffecter ticket'
      if(!$result_action_1330 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_812, 'ade7658a655147c067bd85e554f5493b', 'Reaffecter ticket','reaffectticket', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="reaffectticket"  ><i class="ace-icon fa fa-fire bigger-100"></i> Reaffecter ticket</a></li>'."', '0', '[-1-]', '1', '0', 'Traitement En Cours','success','".'<span class="label label-sm label-success">Traitement En Cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Reaffecter ticket' </li>";}
      // Action Task 812 - 'Ajouter action'
      if(!$result_action_1331 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_812, '599cb4aa075b2cc84746e15f14cd5e41', 'Ajouter action','addaction', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="addaction"  ><i class="ace-icon fa fa-gavel  bigger-100"></i> Ajouter action</a></li>'."', '0', '[-1-]', '1', '0', 'Traitement En Cours','success','".'<span class="label label-sm label-success">Traitement En Cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter action' </li>";}
      // Action Task 812 - 'Confirmer Clôture'
      if(!$result_action_1332 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_812, '51691230fcf4cfd07729acff525de150', 'Confirmer Clôture','clotureticket', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="clotureticket"  ><i class="ace-icon fa fa-bell bigger-100"></i> Confirmer Clôture</a></li>'."', '0', '[-1-]', '2', '0', 'Résolution Réussi','danger','".'<span class="label label-sm label-danger">Résolution Réussi</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Confirmer Clôture' </li>";}
      // Action Task 812 - 'Détails ticket'
      if(!$result_action_1333 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_812, 'c6c0ab5988aab9c83960e0a9f261bfae', 'Détails ticket','detailsticket', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsticket"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails ticket</a></li>'."', '0', '[-1-]', '2', '0', 'Résolution Réussi','danger','".'<span class="label label-sm label-danger">Résolution Réussi</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails ticket' </li>";}
      // Action Task 812 - 'Réaffecter ticket'
      if(!$result_action_1334 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_812, 'f0ec59382bfa1553e2acb2cee8f0e8bf', 'Réaffecter ticket','reaffectticket', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="reaffectticket"  ><i class="ace-icon fa fa-fire  bigger-100"></i> Réaffecter ticket</a></li>'."', '0', '[-1-]', '2', '0', 'Résolution Réussi','danger','".'<span class="label label-sm label-danger">Résolution Réussi</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Réaffecter ticket' </li>";}
      // Action Task 812 - 'Détails ticket'
      if(!$result_action_1335 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_812, '13a62e53e80790158f2d898c2ade40de', 'Détails ticket','detailsticket', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsticket"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails ticket</a></li>'."', '0', '[-1-]', '3', '0', 'Ticket Clôturé','info','".'<span class="label label-sm label-info">Ticket Clôturé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails ticket' </li>";}
  //Task 'addtickets' 'Ajouter ticket'
  if(!$result_task_813 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addtickets', $result_insert_modul, 'addtickets','tickets/main', '1', 'Ajouter ticket', 'cogs', '1', '0', '0','formadd', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter ticket' </li>";}
      // Action Task 813 - 'Ajouter ticket'
      if(!$result_action_1336 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_813, '62191d5df0e93231d769d2b17e3b2d68', 'Ajouter ticket','addtickets', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter ticket' </li>";}
  //Task 'editticket' 'Modifier ticket'
  if(!$result_task_814 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editticket', $result_insert_modul, 'editticket','tickets/main', '1', 'Modifier ticket', 'cogs', '1', '0', '0','formedit', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier ticket' </li>";}
      // Action Task 814 - 'Modifier ticket'
      if(!$result_action_1337 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_814, 'f0a2162636fb154c6f9361b86acd87d3', 'Modifier ticket','editticket', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier ticket' </li>";}
  //Task 'deletetickets' 'Supprimer ticket'
  if(!$result_task_815 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletetickets', $result_insert_modul, 'deleteticket','tickets/main', '1', 'Supprimer ticket', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer ticket' </li>";}
      // Action Task 815 - 'Supprimer ticket'
      if(!$result_action_1338 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_815, '962353cac56b445aa4cc0073d1fa3b21', 'Supprimer ticket','deletetickets', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer ticket' </li>";}
  //Task 'reafectticket' 'Reafecter technicien'
  if(!$result_task_816 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('reafectticket', $result_insert_modul, 'reafectticket','tickets/main', '1', 'Reafecter technicien', 'cogs', '1', '0', '0','formadd', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Reafecter technicien' </li>";}
      // Action Task 816 - 'Reafecter technicien'
      if(!$result_action_1339 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_816, '9f7fa9f4122d308b77bd17e2b57bdd3e', 'Reafecter technicien','reafectticket', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Reafecter technicien' </li>";}
  //Task 'affecttechnicien' 'Affecter ticket'
  if(!$result_task_817 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('affecttechnicien', $result_insert_modul, 'affecttechnicien','tickets/main', '1', 'Affecter ticket', 'cogs', '1', '0', '0','formadd', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Affecter ticket' </li>";}
      // Action Task 817 - 'Affecter ticket'
      if(!$result_action_1340 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_817, 'ebe36becbc7f17cb4157d27d62ca7c45', 'Affecter ticket','affecttechnicien', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente de validation','warning','".'Attente de validation'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Affecter ticket' </li>";}
  //Task 'detailsticket' 'Détails ticket'
  if(!$result_task_818 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsticket', $result_insert_modul, 'detailsticket','tickets/main', '1', 'Détails ticket', 'eye', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails ticket' </li>";}
      // Action Task 818 - 'Détails ticket'
      if(!$result_action_1341 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_818, '73a480d433c6b5e4d130e83eb8d734f8', 'Détails ticket','detailsticket', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails ticket' </li>";}
  //Task 'reaffectticket' 'Réaffecter ticket'
  if(!$result_task_819 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('reaffectticket', $result_insert_modul, 'reaffectticket','tickets/main', '1', 'Réaffecter ticket', 'cogs', '1', '0', '0','formedit', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Réaffecter ticket' </li>";}
      // Action Task 819 - 'Réaffecter ticket'
      if(!$result_action_1342 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_819, 'f496ab30882773264b90dd95dac97e07', 'Réaffecter ticket','reaffectticket', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Réaffecter ticket' </li>";}
  //Task 'addaction' 'Ajouter action'
  if(!$result_task_820 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addaction', $result_insert_modul, 'addaction','tickets/main', '1', 'Ajouter action', 'cogs', '1', '0', '0','formadd', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter action' </li>";}
      // Action Task 820 - 'Ajouter action'
      if(!$result_action_1343 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_820, 'aea1d98c0b188c62f976936454e99bf2', 'Ajouter action','addaction', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter action' </li>";}
  //Task 'deleteactionticket' 'Supprimer ticket action'
  if(!$result_task_821 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteactionticket', $result_insert_modul, 'deleteactionticket','tickets/main', '1', 'Supprimer ticket action', 'trash', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer ticket action' </li>";}
      // Action Task 821 - 'supprimer action ticket'
      if(!$result_action_1344 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_821, '4f9403ccb1cf450f3ee7dc695e9d8f77', 'supprimer action ticket','deleteactionticket', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="deleteactionticket"  ><i class="ace-icon fa fa-trash bigger-100"></i> supprimer action ticket</a></li>'."', '0', '[-1-3-4-20-]', '0', '0', 'Attente validation','success','".'<span class="label label-sm label-success">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'supprimer action ticket' </li>";}
  //Task 'editaction' 'Modifier action'
  if(!$result_task_822 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editaction', $result_insert_modul, 'editaction','tickets/main', '1', 'Modifier action', 'pen blue', '1', '0', '0','formedit', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier action' </li>";}
      // Action Task 822 - 'Modifier action'
      if(!$result_action_1345 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_822, '7ee7f4b765ab9f1ac4f2ef7a5a34b988', 'Modifier action','editaction', NULL, '".NULL."', '1', '[-1-3-20-]', '0', '0', 'Attente validation','success','".'<span class="label label-sm label-success">Attente validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier action' </li>";}
  //Task 'resolution' 'Résolution Réussi'
  if(!$result_task_823 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('resolution', $result_insert_modul, 'resolution','tickets/main', '1', 'Résolution Réussi', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Résolution Réussi' </li>";}
      // Action Task 823 - 'Résolution Réussi'
      if(!$result_action_1346 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_823, 'a4dd36b475e19e7f31667939ef1c5cf5', 'Résolution Réussi','resolution', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Résolution Réussi' </li>";}
  //Task 'clotureticket' 'Ticket cloturé'
  if(!$result_task_824 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('clotureticket', $result_insert_modul, 'clotureticket','tickets/main', '1', 'Ticket cloturé', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ticket cloturé' </li>";}
      // Action Task 824 - 'Ticket cloturé'
      if(!$result_action_1347 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_824, '775d77d66d847962bc363e3c8500004c', 'Ticket cloturé','clotureticket', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ticket cloturé' </li>";}
  //Task 'detailsaction' 'Détails action'
  if(!$result_task_825 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsaction', $result_insert_modul, 'detailsaction','tickets/main', '1', 'Détails action', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails action' </li>";}
      // Action Task 825 - 'Détails action'
      if(!$result_action_1348 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_825, 'ca13381e080bc38cc9505039f618df36', 'Détails action','detailsaction', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails action' </li>";}
