<?php 
//Export Module 'ticket_frs' Date: 02-08-2018
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('ticket_frs', 'Tickets Fournisseurs','ticketing/submodul/ticket_frs','tickets_fournisseurs','ticket_frs','ticketing','2', '0', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'ticket_frs' </li>";}
  //Task 'ticket_frs' 'Tickets Fournisseurs'
  if(!$result_task_871 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('ticket_frs', $result_insert_modul, 'ticket_frs','ticketing/submodul/ticket_frs', '1', 'Tickets Fournisseurs', 'indent', '1', '0', '0','list', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Tickets Fournisseurs' </li>";}
      // Action Task 871 - 'Tickets Fournisseurs'
      if(!$result_action_1448 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_871, 'e9b9a39089f1165c359aae1f4dccfff9', 'Tickets Fournisseurs','ticket_frs', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="ticket_frs"  ><i class="ace-icon fa fa-871 bigger-100"></i> Tickets Fournisseurs</a></li>'."', '0', '[-1-2-3-4-7-6-]', '0', '0', 'Attente Affectation','warning','".'<span class="label label-sm label-warning">Attente Affectation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Tickets Fournisseurs' </li>";}
      // Action Task 871 - 'Modifier Ticket'
      if(!$result_action_1467 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_871, '6e6afd3750c86be8e42e6e5041cf8cb7', 'Modifier Ticket','editticket_frs', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editticket_frs"  ><i class="ace-icon fa fa-pencil-square-o bigger-100"></i> Modifier Ticket</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Affectation','warning','".'<span class="label label-sm label-warning">Attente Affectation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Ticket' </li>";}
      // Action Task 871 - 'Affecter Ticket'
      if(!$result_action_1468 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_871, '070ce398e82a0e807fb33fb5b6d1718b', 'Affecter Ticket','affectticket_frs', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="affectticket_frs"  ><i class="ace-icon fa fa-fire bigger-100"></i> Affecter Ticket</a></li>'."', '0', '[-1-]', '0', '1', 'Attente Affectation','warning','".'<span class="label label-sm label-warning">Attente Affectation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Affecter Ticket' </li>";}
      // Action Task 871 - 'Détails Ticket'
      if(!$result_action_1469 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_871, 'c755538a1f66670e8f8b10703ed52f89', 'Détails Ticket','detailsticket_frs', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsticket_frs"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails Ticket</a></li>'."', '0', '[-1-]', '1', '0', 'Traitement En cours','success','".'<span class="label label-sm label-success">Traitement En cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Ticket' </li>";}
      // Action Task 871 - 'Reaffecter ticket'
      if(!$result_action_1470 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_871, '6748ec11f49a24147ec6df0a807d3a5e', 'Reaffecter ticket','reaffectticket_frs', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="reaffectticket_frs"  ><i class="ace-icon fa fa-fire bigger-100"></i> Reaffecter ticket</a></li>'."', '0', '[-1-]', '1', '0', 'Traitement En cours','success','".'<span class="label label-sm label-success">Traitement En cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Reaffecter ticket' </li>";}
      // Action Task 871 - 'Ajouter action'
      if(!$result_action_1471 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_871, '054ce8ec2ba3e8660d376ada0f0d5123', 'Ajouter action','addaction_frs', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="addaction_frs"  ><i class="ace-icon fa fa-gavel  bigger-100"></i> Ajouter action</a></li>'."', '0', '[-1-]', '1', '0', 'Traitement En cours','success','".'<span class="label label-sm label-success">Traitement En cours</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter action' </li>";}
      // Action Task 871 - 'Confirmer Clôture'
      if(!$result_action_1472 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_871, '6d1e83fd59579090bef2a97c4fa72b25', 'Confirmer Clôture','clotureticket_frs', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="clotureticket_frs"  ><i class="ace-icon fa fa-bell bigger-100"></i> Confirmer Clôture</a></li>'."', '0', '[-1-]', '2', '0', 'Résolution Réussi','danger','".'<span class="label label-sm label-danger">Résolution Réussi</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Confirmer Clôture' </li>";}
      // Action Task 871 - 'Détails ticket'
      if(!$result_action_1473 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_871, '37858b8548c8c453d582dd75bf8ed240', 'Détails ticket','detailsticket_frs', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsticket_frs"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails ticket</a></li>'."', '0', '[-1-]', '2', '0', 'Résolution Réussi','danger','".'<span class="label label-sm label-danger">Résolution Réussi</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails ticket' </li>";}
      // Action Task 871 - 'Reaffecter ticket'
      if(!$result_action_1474 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_871, 'bab2e036beeeb590abae2baed6077a1b', 'Reaffecter ticket','reaffectticket_frs', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="reaffectticket_frs"  ><i class="ace-icon fa fa-fire bigger-100"></i> Reaffecter ticket</a></li>'."', '0', '[-1-]', '2', '0', 'Résolution Réussi','danger','".'<span class="label label-sm label-danger">Résolution Réussi</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Reaffecter ticket' </li>";}
      // Action Task 871 - 'Détails ticket'
      if(!$result_action_1475 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_871, '5b6cb34b3b8336500117b3ac0d7f75b5', 'Détails ticket','detailsticket_frs', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsticket_frs"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails ticket</a></li>'."', '0', '[-1-]', '3', '0', 'Ticket Clôturé','info','".'<span class="label label-sm label-info">Ticket Clôturé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails ticket' </li>";}
      // Action Task 871 - 'Détails Ticket'
      if(!$result_action_1476 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_871, '4def255736924b3c1880ef353f0641b1', 'Détails Ticket','detailsticket_frs', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsticket_frs"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails Ticket</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Affectation','warning','".'<span class="label label-sm label-warning">Attente Affectation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Ticket' </li>";}
      // Action Task 871 - 'Détails ticket '
      if(!$result_action_1482 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_871, 'b7d9f2554c40991f524bf4e110f678be', 'Détails ticket ','detailsticket_frs', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsticket_frs"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails ticket </a></li>'."', '0', '[-1-]', '100', '0', 'Ticket Clôturé','inverse','".'<span class="label label-sm label-inverse">Ticket Clôturé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails ticket ' </li>";}
  //Task 'addticket_frs' 'Ajouter ticket frs'
  if(!$result_task_872 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addticket_frs', $result_insert_modul, 'addticket_frs','ticketing/submodul/ticket_frs', '1', 'Ajouter ticket frs', 'lock', '1', '0', '0','formadd', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter ticket frs' </li>";}
      // Action Task 872 - 'Ajouter ticket frs'
      if(!$result_action_1449 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_872, '2d7ee58970dd9752b2f8ffb225fc0987', 'Ajouter ticket frs','addticket_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter ticket frs' </li>";}
  //Task 'editticket_frs' 'Modifier ticket frs'
  if(!$result_task_874 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editticket_frs', $result_insert_modul, 'editticket_frs','ticketing/submodul/ticket_frs', '1', 'Modifier ticket frs', 'cogs', '1', '0', '0','formedit', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier ticket frs' </li>";}
      // Action Task 874 - 'Modifier ticket frs'
      if(!$result_action_1450 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_874, 'f3934ccc775b76f2e48d36da3e594459', 'Modifier ticket frs','editticket_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier ticket frs' </li>";}
  //Task 'deleteticket_frs' 'Supprimer ticket frs'
  if(!$result_task_875 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteticket_frs', $result_insert_modul, 'deleteticket_frs','ticketing/submodul/ticket_frs', '1', 'Supprimer ticket frs', 'cogs', '1', '0', '0','exec', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer ticket frs' </li>";}
      // Action Task 875 - 'Supprimer ticket frs'
      if(!$result_action_1451 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_875, 'eaedfc1e5a8abd22f2ba26019b03b7f1', 'Supprimer ticket frs','deletetickts_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer ticket frs' </li>";}
  //Task 'reaffectticket_frs' 'Reaffectation ticket frs'
  if(!$result_task_876 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('reaffectticket_frs', $result_insert_modul, 'reaffectticket_frs','ticketing/submodul/ticket_frs', '1', 'Reaffectation ticket frs', 'cogs', '1', '0', '0','formedit', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Reaffectation ticket frs' </li>";}
      // Action Task 876 - 'Reaffectation ticket frs'
      if(!$result_action_1452 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_876, 'b50b1f82a4dd716d7ef97a8a45b854ec', 'Reaffectation ticket frs','reaffectticket_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'Attente Validation'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Reaffectation ticket frs' </li>";}
  //Task 'affectticket_frs' 'Affectation ticket frs'
  if(!$result_task_877 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('affectticket_frs', $result_insert_modul, 'affectticket_frs','ticketing/submodul/ticket_frs', '1', 'Affectation ticket frs', 'cogs', '1', '0', '0','formadd', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Affectation ticket frs' </li>";}
      // Action Task 877 - 'Affectation ticket frs'
      if(!$result_action_1453 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_877, 'e6542511bcdd36ff70544270d587fa3a', 'Affectation ticket frs','affectticket_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Affectation ticket frs' </li>";}
  //Task 'detailsticket_frs' 'Détails ticket frs'
  if(!$result_task_878 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsticket_frs', $result_insert_modul, 'detailsticket_frs','ticketing/submodul/ticket_frs', '1', 'Détails ticket frs', 'cogs', '1', '0', '0','profil', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails ticket frs' </li>";}
      // Action Task 878 - 'Détails ticket frs'
      if(!$result_action_1454 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_878, 'b1ed6e46d9d195eedaf93e7ecd7e5336', 'Détails ticket frs','detailsticket_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails ticket frs' </li>";}
  //Task 'addaction_frs' 'Ajouter action frs'
  if(!$result_task_879 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addaction_frs', $result_insert_modul, 'addaction_frs','ticketing/submodul/ticket_frs', '1', 'Ajouter action frs', 'cogs', '1', '0', '0','formadd', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter action frs' </li>";}
      // Action Task 879 - 'Ajouter action frs'
      if(!$result_action_1455 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_879, '3fc738273c09eced6b9070a5f49b7452', 'Ajouter action frs','addaction_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter action frs' </li>";}
  //Task 'deleteaction_frs' 'Supprimer action frs'
  if(!$result_task_880 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteaction_frs', $result_insert_modul, 'deleteaction_frs','ticketing/submodul/ticket_frs', '1', 'Supprimer action frs', 'cogs', '1', '0', '0','exec', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer action frs' </li>";}
      // Action Task 880 - 'Supprimer action frs'
      if(!$result_action_1456 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_880, '7f92ab4f5bb363d3a90856e2064daf33', 'Supprimer action frs','deleteaction_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer action frs' </li>";}
  //Task 'editaction_frs' 'Modifier action frs'
  if(!$result_task_881 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editaction_frs', $result_insert_modul, 'editaction_frs','ticketing/submodul/ticket_frs', '1', 'Modifier action frs', 'cogs', '1', '0', '0','formedit', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier action frs' </li>";}
      // Action Task 881 - 'Modifier action frs'
      if(!$result_action_1457 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_881, 'c1b0803e3b31014bf287c6e654c87cfc', 'Modifier action frs','editaction_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier action frs' </li>";}
  //Task 'resolution_frs' 'Résolution reussi frs'
  if(!$result_task_882 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('resolution_frs', $result_insert_modul, 'resolution_frs','ticketing/submodul/ticket_frs', '1', 'Résolution reussi frs', 'cogs', '1', '0', '0','exec', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Résolution reussi frs' </li>";}
      // Action Task 882 - 'Résolution reussi frs'
      if(!$result_action_1458 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_882, '41530b6d8111f4e7384d59d73f0809ef', 'Résolution reussi frs','resolution_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Résolution reussi frs' </li>";}
  //Task 'clotureticket_frs' 'Ticket cloturé frs'
  if(!$result_task_883 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('clotureticket_frs', $result_insert_modul, 'clotureticket_frs','ticketing/submodul/ticket_frs', '1', 'Ticket cloturé frs', 'cogs', '1', '0', '0','exec', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ticket cloturé frs' </li>";}
      // Action Task 883 - 'Ticket cloturé frs'
      if(!$result_action_1459 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_883, '5915fe5aa1bbe8c27088ffd5997d9e7c', 'Ticket cloturé frs','clotureticket_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ticket cloturé frs' </li>";}
  //Task 'detailsaction_frs' 'Détails action frs'
  if(!$result_task_884 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsaction_frs', $result_insert_modul, 'detailsaction_frs','ticketing/submodul/ticket_frs', '1', 'Détails action frs', 'cogs', '1', '0', '0','profil', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails action frs' </li>";}
      // Action Task 884 - 'Détails action frs'
      if(!$result_action_1460 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_884, '27b69f1ac4f376049bbbb7674538dc92', 'Détails action frs','detailsaction_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails action frs' </li>";}
  //Task 'archiveticket_frs' 'Archiver ticket frs'
  if(!$result_task_890 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('archiveticket_frs', $result_insert_modul, 'archiveticket_frs','ticketing/submodul/ticket_frs', '1', 'Archiver ticket frs', 'cogs', '1', '0', '0','exec', '[-1-2-3-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Archiver ticket frs' </li>";}
      // Action Task 890 - 'Archiver ticket frs'
      if(!$result_action_1481 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_890, '57bc158aa8cbee6549a62330f703d186', 'Archiver ticket frs','archiveticket_frs', NULL, '".NULL."', '1', '[-1-]', '0', '0', 'Attente Validation','inverse','".'<span class="label label-sm label-inverse">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Archiver ticket frs' </li>";}
