<?php 
//Export Module 'type_echeance' Date: 23-09-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('type_echeance', 'Gestion Type Echeance','contrats/settings/type_echeance','ref_type_echeance','type_echeance','contrats','1', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'type_echeance' </li>";}
  //Task 'type_echeance' 'Gestion Type Echeance'
  if(!$result_task_480 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('type_echeance', $result_insert_modul, 'type_echeance','contrats/settings/type_echeance', '1', 'Gestion Type Echeance', 'info-circle', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Type Echeance' </li>";}
      // Action Task 480 - 'Gestion Type Echeance'
      if(!$result_action_692 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_480, '312fd18860781a7b1b7e33587fa423d4', 'Gestion Type Echeance','type_echeance', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Type Echeance' </li>";}
      // Action Task 480 - 'Editer Type Echéance'
      if(!$result_action_697 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_480, '46ad76148075d6b458f43e84ddf00791', 'Editer Type Echéance','edittype_echeance', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="edittype_echeance"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Editer Type Echéance</a></li>'."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Type Echéance' </li>";}
      // Action Task 480 - 'Valider Type Echéance'
      if(!$result_action_698 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_480, 'add2bf057924e606653fbf5bbd65ca09', 'Valider Type Echéance','validtype_echeance', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validtype_echeance"  ><i class="ace-icon fa fa-lock bigger-100"></i> Valider Type Echéance</a></li>'."', '0', '[-1-]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Type Echéance' </li>";}
      // Action Task 480 - 'Désactiver Type Echéance'
      if(!$result_action_699 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_480, '463d9e1e8367736b958f0dd84b4e36d5', 'Désactiver Type Echéance','validtype_echeance', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validtype_echeance"  ><i class="ace-icon fa fa-unlock bigger-100"></i> Désactiver Type Echéance</a></li>'."', '0', '[-1-]', '1', '0', 'Type Echéance Validé','success','".'<span class="label label-sm label-success">Type Echéance Validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver Type Echéance' </li>";}
  //Task 'addtype_echeance' 'Ajouter Type Echéance'
  if(!$result_task_481 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addtype_echeance', $result_insert_modul, 'addtype_echeance','contrats/settings/type_echeance', '1', 'Ajouter Type Echéance', 'info-circle', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Type Echéance' </li>";}
      // Action Task 481 - 'Ajouter Type Echéance'
      if(!$result_action_693 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_481, '76170b14c7b6f1f7058d079fe24f739b', 'Ajouter Type Echéance','addtype_echeance', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Type Echéance' </li>";}
  //Task 'edittype_echeance' 'Editer Type Echéance'
  if(!$result_task_482 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edittype_echeance', $result_insert_modul, 'edittype_echeance','contrats/settings/type_echeance', '1', 'Editer Type Echéance', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer Type Echéance' </li>";}
      // Action Task 482 - 'Editer Type Echéance'
      if(!$result_action_694 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_482, 'decc5ed58c4d91e6967c9c67e0975cf0', 'Editer Type Echéance','edittype_echeance', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Type Echéance' </li>";}
  //Task 'deletetype_echeance' 'Supprimer Type Echéance'
  if(!$result_task_483 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletetype_echeance', $result_insert_modul, 'deletetype_echeance','contrats/settings/type_echeance', '1', 'Supprimer Type Echéance', 'trash', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Type Echéance' </li>";}
      // Action Task 483 - 'Supprimer Type Echéance'
      if(!$result_action_695 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_483, '89db6f23dd8e96a69c6a97f556c44e14', 'Supprimer Type Echéance','deletetype_echeance', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Type Echéance' </li>";}
  //Task 'validtype_echeance' 'Valider Type Echéance'
  if(!$result_task_484 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validtype_echeance', $result_insert_modul, 'validtype_echeance','contrats/settings/type_echeance', '1', 'Valider Type Echéance', 'lock', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Type Echéance' </li>";}
      // Action Task 484 - 'Valider Type Echéance'
      if(!$result_action_696 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_484, '7527021168823e0118d44297c7684d44', 'Valider Type Echéance','validtype_echeance', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Type Echéance' </li>";}
