<?php 
//Export Module 'types_produits' Date: 23-09-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('types_produits', 'Gestion des types de produits','produits/settings/types_produits','ref_types_produits','types_produits','produits','1', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'types_produits' </li>";}
  //Task 'types_produits' 'Gestion des types de produits'
  if(!$result_task_460 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('types_produits', $result_insert_modul, 'types_produits','produits/settings/types_produits', '1', 'Gestion des types de produits', 'cogs', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion des types de produits' </li>";}
      // Action Task 460 - 'Gestion des types de produits'
      if(!$result_action_660 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_460, 'b6b6bfbd070b5b3dd84acedae7b854e9', 'Gestion des types de produits','types_produits', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion des types de produits' </li>";}
      // Action Task 460 - 'Modifier type'
      if(!$result_action_661 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_460, '3c5400b775264499825a039d66aa9c90', 'Modifier type','edittype_produit', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="edittype_produit"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier type</a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier type' </li>";}
      // Action Task 460 - 'Valider type'
      if(!$result_action_662 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_460, 'dcf55bc300d690af4c81e4d2335e60e5', 'Valider type','validtype_produit', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validtype_produit"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Valider type</a></li>'."', '0', '[-1-]', '0', '1', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider type' </li>";}
      // Action Task 460 - 'Désactiver type'
      if(!$result_action_663 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_460, '230b9554d37da1c71986af94962cb340', 'Désactiver type','validtype_produit', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validtype_produit"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Désactiver type</a></li>'."', '0', '[-1-]', '1', '0', 'Type validé','success','".'<span class="label label-sm label-success">Type validé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver type' </li>";}
  //Task 'addtype_produit' 'Ajouter un type'
  if(!$result_task_461 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addtype_produit', $result_insert_modul, 'addtype_produit','produits/settings/types_produits', '1', 'Ajouter un type', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter un type' </li>";}
      // Action Task 461 - 'Ajouter un type'
      if(!$result_action_664 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_461, 'e0d163499b4ba11d6d7a648bc6fc6de6', 'Ajouter un type','addtype_produit', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter un type' </li>";}
  //Task 'edittype_produit' 'Modifier type'
  if(!$result_task_462 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edittype_produit', $result_insert_modul, 'edittype_produit','produits/settings/types_produits', '1', 'Modifier type', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier type' </li>";}
      // Action Task 462 - 'Modifier type'
      if(!$result_action_665 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_462, 'ac5a6d087b3c8db7501fa5137a47773e', 'Modifier type','edittype_produit', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier type' </li>";}
  //Task 'validtype_produit' 'Valider type'
  if(!$result_task_463 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validtype_produit', $result_insert_modul, 'validtype_produit','produits/settings/types_produits', '1', 'Valider type', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider type' </li>";}
      // Action Task 463 - 'Valider type'
      if(!$result_action_666 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_463, '2e8242a93a62a264ad7cfc953967f575', 'Valider type','validtype_produit', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider type' </li>";}
  //Task 'deletetype_produit' 'Supprimer type'
  if(!$result_task_464 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletetype_produit', $result_insert_modul, 'deletetype_produit','produits/settings/types_produits', '1', 'Supprimer type', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer type' </li>";}
      // Action Task 464 - 'Supprimer type'
      if(!$result_action_667 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_464, 'e3725ba15ca483b9278f68553eca5918', 'Supprimer type','deletetype_produit', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation','warning','".'<span class="label label-sm label-warning">Attente de validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer type' </li>";}
