<?php 
//Export Module 'uhf_vhf_stations' Date: 13-06-2017z
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('uhf_vhf_stations', 'Gestion UHF/VHF','uhf_vhf_stations','uhf_vhf_stations','uhf_vhf_stations',NULL,'0', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'uhf_vhf_stations' </li>";}
  //Task 'uhf_vhf_stations' 'UHF/VHF Stations'
<<<<<<< HEAD
  if(!$result_task_127 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('uhf_vhf_stations', $result_insert_modul, 'uhf_vhf_stations','uhf_vhf_stations', '1', 'UHF/VHF Stations', 'cogs', '1', '0', '0','list', 'null')")){$this->error = false; $this->log .= "<li> Error Import task 'UHF/VHF Stations' </li>";}
      // Action Task 127 - 'Gestion UHF/VHF'
      if(!$result_action_167 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_127, 'a103e1e77e0862705ec62ad2741e6522', 'Gestion UHF/VHF', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion UHF/VHF' </li>";}
      // Action Task 127 - 'Modifier Station'
      if(!$result_action_168 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_127, '3e1c02423135af5a3edc8f6c8a24c130', 'Modifier Station', '".'<li><a href="#" class="this_url" data="%id%" rel="edituhf_vhf_stations"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier Station</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Station' </li>";}
      // Action Task 127 - 'Valider Station'
      if(!$result_action_169 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_127, '7cd9ae4f8c0e1c85ab01766d85784e00', 'Valider Station', '".'<li><a href="#" class="this_exec" data="%id%" rel="validuhf_vhf_stations"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Valider Station</a></li>'."', '0', '[-1-]', '0', '1', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Station' </li>";}
      // Action Task 127 - 'Supprimer Station'
      if(!$result_action_170 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_127, 'caa8133286c46887e3b52c1b761d89a0', 'Supprimer Station', '".'<li><a href="#" class="this_exec" data="%id%" rel="deleteuhf_vhf_stations"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Supprimer Station</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Station' </li>";}
      // Action Task 127 - 'Liste des clients'
      if(!$result_action_171 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_127, 'aadaec7e401d946c3edcba4e15ae83db', 'Liste des clients', '".'<li><a href="#" class="this_url" data="%id%" rel="uhf_vhf_clients"  ><i class="ace-icon fa fa-circle bigger-100"></i> Liste des clients</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste des clients' </li>";}
      // Action Task 127 - 'Liste des clients'
      if(!$result_action_172 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_127, '3a479d262ee66b99eb69793b3a8152a7', 'Liste des clients', '".'<li><a href="#" class="this_url" data="%id%" rel="uhf_vhf_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Liste des clients</a></li>'."', '0', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste des clients' </li>";}
  //Task 'adduhf_vhf_stations' 'Ajouter station'
  if(!$result_task_128 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adduhf_vhf_stations', $result_insert_modul, 'adduhf_vhf_stations','uhf_vhf_stations', '1', 'Ajouter station', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter station' </li>";}
      // Action Task 128 - 'Ajouter station'
      if(!$result_action_173 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_128, '59c93bdf7dc111cae9d6f1306382c896', 'Ajouter station', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter station' </li>";}
  //Task 'edituhf_vhf_stations' 'Modifier Station'
  if(!$result_task_129 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edituhf_vhf_stations', $result_insert_modul, 'edituhf_vhf_stations','uhf_vhf_stations', '1', 'Modifier Station', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Station' </li>";}
      // Action Task 129 - 'Modifier Station'
      if(!$result_action_174 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_129, 'c1bc9b42786ad026f9147aeaa99f622d', 'Modifier Station', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Station' </li>";}
  //Task 'deleteuhf_vhf_stations' 'Supprimer Station'
  if(!$result_task_130 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteuhf_vhf_stations', $result_insert_modul, 'deleteuhf_vhf_stations','uhf_vhf_stations', '1', 'Supprimer Station', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Station' </li>";}
      // Action Task 130 - 'Supprimer Station'
      if(!$result_action_175 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_130, 'aea042f6366208cae37f384b85531ef8', 'Supprimer Station', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Station' </li>";}
  //Task 'validuhf_vhf_stations' 'Valider Station'
  if(!$result_task_131 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validuhf_vhf_stations', $result_insert_modul, 'validuhf_vhf_stations','uhf_vhf_stations', '1', 'Valider Station', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Station' </li>";}
      // Action Task 131 - 'Valider Station'
      if(!$result_action_176 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_131, '939ccf06a327d91881b7b258b93585a4', 'Valider Station', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Station' </li>";}
  //Task 'adduhf_vhf_clt_mobile' 'Ajout client'
  if(!$result_task_132 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adduhf_vhf_clt_mobile', $result_insert_modul, 'adduhf_vhf_clt_mobile','uhf_vhf_stations', '1', 'Ajout client', 'cloud', '1', '0', '0','form', 'null')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajout client' </li>";}
      // Action Task 132 - 'Ajout client'
      if(!$result_action_177 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_132, '988f8f0817f020facab448bb694fc2e9', 'Ajout client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajout client' </li>";}
  //Task 'edituhf_vhf_clt_mobile' 'Modifier client'
  if(!$result_task_133 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edituhf_vhf_clt_mobile', $result_insert_modul, 'edituhf_vhf_clt_mobile','uhf_vhf_stations', '1', 'Modifier client', 'cogs', '1', '0', '0','form', 'null')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier client' </li>";}
      // Action Task 133 - 'Modifier client'
      if(!$result_action_178 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_133, '2cd2dcab297ab7cf9103426510aeb918', 'Modifier client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier client' </li>";}
  //Task 'uhf_vhf_clients' 'UHF/VHF Clients'
  if(!$result_task_134 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('uhf_vhf_clients', $result_insert_modul, 'uhf_vhf_clients','uhf_vhf_stations', '1', 'UHF/VHF Clients', 'cogs', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'UHF/VHF Clients' </li>";}
      // Action Task 134 - 'UHF/VHF Clients'
      if(!$result_action_179 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_134, 'd6fc10807987de7f39ad3dc712d0363c', 'UHF/VHF Clients', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'UHF/VHF Clients' </li>";}
      // Action Task 134 - 'Valider Client'
      if(!$result_action_180 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_134, '6a4de3fbaa5ecbfa40301d1b3a81b303', 'Valider Client', '".'<li><a href="#" class="this_exec" data="%id%" rel="validuhf_vhf_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Valider Client</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Client' </li>";}
      // Action Task 134 - 'Supprimer client'
      if(!$result_action_181 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_134, '8ebc4a0a0229c84f1561555e8edcaf5f', 'Supprimer client', '".'<li><a href="#" class="this_exec" data="%id%" rel="deleteuhf_vhf_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Supprimer client</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer client' </li>";}
      // Action Task 134 - 'Modifier client'
      if(!$result_action_182 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_134, '45e026b77e91abe81b21baa473d536fd', 'Modifier client', '".'<li><a href="#" class="this_url" data="%id%" rel="edituhf_vhf_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier client</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier client' </li>";}
  //Task 'validuhf_vhf_clients' 'Validation client'
  if(!$result_task_135 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validuhf_vhf_clients', $result_insert_modul, 'validuhf_vhf_clients','uhf_vhf_stations', '1', 'Validation client', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Validation client' </li>";}
      // Action Task 135 - 'Validation client'
      if(!$result_action_183 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_135, '4247ce573d3fc49fda24dbfc017d9cc4', 'Validation client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Validation client' </li>";}
  //Task 'adduhf_vhf_clt_handset' 'Ajout Client'
  if(!$result_task_136 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adduhf_vhf_clt_handset', $result_insert_modul, 'adduhf_vhf_clt_handset','uhf_vhf_stations', '1', 'Ajout Client', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajout Client' </li>";}
      // Action Task 136 - 'Ajout Client'
      if(!$result_action_184 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_136, 'dd2a86ec80f60514f3d5cbd8fa987404', 'Ajout Client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajout Client' </li>";}
  //Task 'adduhf_vhf_clt_fixe' 'Ajout Client'
  if(!$result_task_137 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adduhf_vhf_clt_fixe', $result_insert_modul, 'adduhf_vhf_clt_fixe','uhf_vhf_stations', '1', 'Ajout Client', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajout Client' </li>";}
      // Action Task 137 - 'Ajout Client'
      if(!$result_action_185 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_137, 'b27c2ab70726c47c242fca8b9c30b771', 'Ajout Client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajout Client' </li>";}
  //Task 'deleteuhf_vhf_clients' 'Supprimer client'
  if(!$result_task_138 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteuhf_vhf_clients', $result_insert_modul, 'deleteuhf_vhf_clients','uhf_vhf_stations', '1', 'Supprimer client', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer client' </li>";}
      // Action Task 138 - 'Supprimer client'
      if(!$result_action_186 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_138, '113ca83b68ce633598e8340fa2b4bf70', 'Supprimer client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer client' </li>";}
  //Task 'edituhf_vhf_clt_handset' 'Modifier client'
  if(!$result_task_139 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edituhf_vhf_clt_handset', $result_insert_modul, 'edituhf_vhf_clt_handset','uhf_vhf_stations', '1', 'Modifier client', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier client' </li>";}
      // Action Task 139 - 'Modifier client'
      if(!$result_action_187 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_139, 'b0e750a138dcf4ab959ef8225252be2a', 'Modifier client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier client' </li>";}
  //Task 'edituhf_vhf_clt_fixe' 'Modifier client'
  if(!$result_task_140 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edituhf_vhf_clt_fixe', $result_insert_modul, 'edituhf_vhf_clt_fixe','uhf_vhf_stations', '1', 'Modifier client', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier client' </li>";}
      // Action Task 140 - 'Modifier client'
      if(!$result_action_188 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_140, 'da74878d46c49cc2accb5cdeb7fa438e', 'Modifier client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier client' </li>";}
  //Task 'edituhf_vhf_clients' 'Modifier client'
  if(!$result_task_141 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edituhf_vhf_clients', $result_insert_modul, 'edituhf_vhf_clients','uhf_vhf_stations', '1', 'Modifier client', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier client' </li>";}
      // Action Task 141 - 'Modifier client'
      if(!$result_action_189 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_141, 'b7e5f4088fa129cf0c76b8ed071dc79b', 'Modifier client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier client' </li>";}
=======
  if(!$result_task_285 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('uhf_vhf_stations', $result_insert_modul, 'uhf_vhf_stations','uhf_vhf_stations', '1', 'UHF/VHF Stations', 'cogs', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'UHF/VHF Stations' </li>";}
      // Action Task 285 - 'Gestion UHF/VHF'
      if(!$result_action_427 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_285, 'a103e1e77e0862705ec62ad2741e6522', 'Gestion UHF/VHF', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion UHF/VHF' </li>";}
      // Action Task 285 - 'Modifier Station UHF/VHF'
      if(!$result_action_428 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_285, 'a1f144f8657651c76ad15958ef08ff01', 'Modifier Station UHF/VHF', '".'<li><a href="#" class="this_url" data="%id%" rel="edituhf_vhf_stations"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier Station UHF/VHF</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Station UHF/VHF' </li>";}
      // Action Task 285 - 'Valider Station UHF/VHF'
      if(!$result_action_429 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_285, 'b10d348ae35c3c4b63750f0e476337de', 'Valider Station UHF/VHF', '".'<li><a href="#" class="this_exec" data="%id%" rel="validuhf_vhf_stations"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Valider Station UHF/VHF</a></li>'."', '0', '[-1-]', '0', '1', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Station UHF/VHF' </li>";}
      // Action Task 285 - 'Liste des clients UHF/VHF'
      if(!$result_action_430 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_285, '83db9ed69a22dffab229681e83e45c08', 'Liste des clients UHF/VHF', '".'<li><a href="#" class="this_url" data="%id%" rel="uhf_vhf_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Liste des clients UHF/VHF</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste des clients UHF/VHF' </li>";}
      // Action Task 285 - 'Liste des clients UHF/VHF'
      if(!$result_action_431 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_285, '5fa72d068be4095ffb500d23a2acc4e7', 'Liste des clients UHF/VHF', '".'<li><a href="#" class="this_url" data="%id%" rel="uhf_vhf_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Liste des clients UHF/VHF</a></li>'."', '0', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste des clients UHF/VHF' </li>";}
      // Action Task 285 - 'Détails station uhf_vhf'
      if(!$result_action_432 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_285, '0e7910af90ffffac7b7e200f7c32365d', 'Détails station uhf_vhf', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsuhf_vhf"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Détails station uhf_vhf</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails station uhf_vhf' </li>";}
  //Task 'adduhf_vhf_stations' 'Ajouter Station UHF/VHF'
  if(!$result_task_286 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adduhf_vhf_stations', $result_insert_modul, 'adduhf_vhf_stations','uhf_vhf_stations', '1', 'Ajouter Station UHF/VHF', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Station UHF/VHF' </li>";}
      // Action Task 286 - 'Ajouter station'
      if(!$result_action_433 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_286, '59c93bdf7dc111cae9d6f1306382c896', 'Ajouter station', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter station' </li>";}
  //Task 'edituhf_vhf_stations' 'Modifier Station UHF/VHF'
  if(!$result_task_287 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edituhf_vhf_stations', $result_insert_modul, 'edituhf_vhf_stations','uhf_vhf_stations', '1', 'Modifier Station UHF/VHF', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Station UHF/VHF' </li>";}
      // Action Task 287 - 'Modifier Station'
      if(!$result_action_434 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_287, 'c1bc9b42786ad026f9147aeaa99f622d', 'Modifier Station', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Station' </li>";}
  //Task 'validuhf_vhf_stations' 'Valider Station UHF/VHF'
  if(!$result_task_288 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validuhf_vhf_stations', $result_insert_modul, 'validuhf_vhf_stations','uhf_vhf_stations', '1', 'Valider Station UHF/VHF', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Station UHF/VHF' </li>";}
      // Action Task 288 - 'Valider Station'
      if(!$result_action_435 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_288, '939ccf06a327d91881b7b258b93585a4', 'Valider Station', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Station' </li>";}
  //Task 'adduhf_vhf_clt_mobile' 'Ajout Client Mobile'
  if(!$result_task_289 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adduhf_vhf_clt_mobile', $result_insert_modul, 'adduhf_vhf_clt_mobile','uhf_vhf_stations', '1', 'Ajout Client Mobile', 'cloud', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajout Client Mobile' </li>";}
      // Action Task 289 - 'Ajout client'
      if(!$result_action_436 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_289, '988f8f0817f020facab448bb694fc2e9', 'Ajout client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajout client' </li>";}
  //Task 'edituhf_vhf_clt_mobile' 'Modifier Client mobile'
  if(!$result_task_290 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edituhf_vhf_clt_mobile', $result_insert_modul, 'edituhf_vhf_clt_mobile','uhf_vhf_stations', '1', 'Modifier Client mobile', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Client mobile' </li>";}
      // Action Task 290 - 'Modifier client'
      if(!$result_action_437 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_290, '2cd2dcab297ab7cf9103426510aeb918', 'Modifier client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier client' </li>";}
  //Task 'uhf_vhf_clients' 'UHF/VHF Clients'
  if(!$result_task_291 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('uhf_vhf_clients', $result_insert_modul, 'uhf_vhf_clients','uhf_vhf_stations', '1', 'UHF/VHF Clients', 'cogs', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'UHF/VHF Clients' </li>";}
      // Action Task 291 - 'UHF/VHF Clients'
      if(!$result_action_438 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_291, 'd6fc10807987de7f39ad3dc712d0363c', 'UHF/VHF Clients', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'UHF/VHF Clients' </li>";}
      // Action Task 291 - 'Modifier Client UHF/VHF'
      if(!$result_action_439 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_291, '1bc2f3c2d42d92cb6563eb40f0b777d7', 'Modifier Client UHF/VHF', '".'<li><a href="#" class="this_url" data="%id%" rel="edituhf_vhf_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier Client UHF/VHF</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Client UHF/VHF' </li>";}
      // Action Task 291 - 'Détails client UHF/VHF'
      if(!$result_action_440 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_291, '2c6d3519de701ab8fd0712cf0e8178d8', 'Détails client UHF/VHF', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsuhf_vhf_clients"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Détails client UHF/VHF</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails client UHF/VHF' </li>";}
  //Task 'adduhf_vhf_clt_handset' 'Ajout Client Handset'
  if(!$result_task_292 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adduhf_vhf_clt_handset', $result_insert_modul, 'adduhf_vhf_clt_handset','uhf_vhf_stations', '1', 'Ajout Client Handset', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajout Client Handset' </li>";}
      // Action Task 292 - 'Ajout Client'
      if(!$result_action_441 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_292, 'dd2a86ec80f60514f3d5cbd8fa987404', 'Ajout Client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajout Client' </li>";}
  //Task 'adduhf_vhf_clt_fixe' 'Ajout Client Fixe'
  if(!$result_task_293 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adduhf_vhf_clt_fixe', $result_insert_modul, 'adduhf_vhf_clt_fixe','uhf_vhf_stations', '1', 'Ajout Client Fixe', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajout Client Fixe' </li>";}
      // Action Task 293 - 'Ajout Client'
      if(!$result_action_442 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_293, 'b27c2ab70726c47c242fca8b9c30b771', 'Ajout Client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajout Client' </li>";}
  //Task 'edituhf_vhf_clt_handset' 'Modifier Client Handset'
  if(!$result_task_294 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edituhf_vhf_clt_handset', $result_insert_modul, 'edituhf_vhf_clt_handset','uhf_vhf_stations', '1', 'Modifier Client Handset', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Client Handset' </li>";}
      // Action Task 294 - 'Modifier client'
      if(!$result_action_443 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_294, 'b0e750a138dcf4ab959ef8225252be2a', 'Modifier client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier client' </li>";}
  //Task 'edituhf_vhf_clt_fixe' 'Modifier Client Fixe'
  if(!$result_task_295 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edituhf_vhf_clt_fixe', $result_insert_modul, 'edituhf_vhf_clt_fixe','uhf_vhf_stations', '1', 'Modifier Client Fixe', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Client Fixe' </li>";}
      // Action Task 295 - 'Modifier client'
      if(!$result_action_444 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_295, 'da74878d46c49cc2accb5cdeb7fa438e', 'Modifier client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier client' </li>";}
  //Task 'edituhf_vhf_clients' 'Modifier Client UHF/VHF'
  if(!$result_task_296 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edituhf_vhf_clients', $result_insert_modul, 'edituhf_vhf_clients','uhf_vhf_stations', '1', 'Modifier Client UHF/VHF', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Client UHF/VHF' </li>";}
      // Action Task 296 - 'Modifier client'
      if(!$result_action_445 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_296, 'b7e5f4088fa129cf0c76b8ed071dc79b', 'Modifier client', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier client' </li>";}
  //Task 'detailsuhf_vhf' 'Détails station uhf_vhf'
  if(!$result_task_297 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsuhf_vhf', $result_insert_modul, 'detailsuhf_vhf','uhf_vhf_stations', '1', 'Détails station uhf_vhf', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails station uhf_vhf' </li>";}
      // Action Task 297 - 'Détails station uhf_vhf'
      if(!$result_action_446 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_297, '3f8d6bfcd973be63e6ad187c328909ec', 'Détails station uhf_vhf', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails station uhf_vhf' </li>";}
  //Task 'detailsuhf_vhf_clients_fi' 'Détails Client Fixe'
  if(!$result_task_298 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsuhf_vhf_clients_fi', $result_insert_modul, 'detailsuhf_vhf_clients_fixe','uhf_vhf_stations', '1', 'Détails Client Fixe', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails Client Fixe' </li>";}
      // Action Task 298 - 'Détails client fixe'
      if(!$result_action_447 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_298, '78265bfab90a25b7d2d1a9490b0eb5c6', 'Détails client fixe', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails client fixe' </li>";}
  //Task 'detailsuhf_vhf_clients_ha' 'Détails Client Handset'
  if(!$result_task_299 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsuhf_vhf_clients_ha', $result_insert_modul, 'detailsuhf_vhf_clients_handset','uhf_vhf_stations', '1', 'Détails Client Handset', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails Client Handset' </li>";}
      // Action Task 299 - 'Détails client handset'
      if(!$result_action_448 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_299, 'c7574f589aeb8a079d0e58ab40bc089e', 'Détails client handset', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails client handset' </li>";}
  //Task 'detailsuhf_vhf_clients_mo' 'Détails Client Mobile'
  if(!$result_task_300 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsuhf_vhf_clients_mo', $result_insert_modul, 'detailsuhf_vhf_clients_mobile','uhf_vhf_stations', '1', 'Détails Client Mobile', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails Client Mobile' </li>";}
      // Action Task 300 - 'Détails client mobile'
      if(!$result_action_449 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_300, '52a7eab115ca46630d01fc609314d650', 'Détails client mobile', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails client mobile' </li>";}
  //Task 'detailsuhf_vhf_clients' 'Détails client UHF/VHF'
  if(!$result_task_301 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsuhf_vhf_clients', $result_insert_modul, 'detailsuhf_vhf_clients','uhf_vhf_stations', '1', 'Détails client UHF/VHF', 'cogs', '1', '0', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails client UHF/VHF' </li>";}
      // Action Task 301 - 'Détails client UHF/VHF'
      if(!$result_action_450 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_301, '466764849b81808d9c4ae57f3dfe6a6c', 'Détails client UHF/VHF', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails client UHF/VHF' </li>";}
>>>>>>> origin/pre_deploy
