<?php 
//Export Module 'unites_vente' Date: 03-09-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('unites_vente', 'Gestion des unités de vente','produits/settings/unites_vente','ref_unites_vente','unites_vente','produits','1', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'unites_vente' </li>";}
  //Task 'unites_vente' 'Gestion des unités de vente'
  if(!$result_task_341 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('unites_vente', $result_insert_modul, 'unites_vente','produits/settings/unites_vente', '1', 'Gestion des unités de vente', 'cogs', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion des unités de vente' </li>";}
      // Action Task 341 - 'Gestion des unités de vente'
      if(!$result_action_517 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_341, '55ecbb545a49c70c0b728bb0c7951077', 'Gestion des unités de vente','unites_vente', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation',NULL,'".'nA'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion des unités de vente' </li>";}
      // Action Task 341 - 'Modifier unité '
      if(!$result_action_518 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_341, '67acd70eb04242b7091d9dcbb08295d7', 'Modifier unité ','unites_vente', NULL, '".'<li><a href="#" class="this_url" data="%id%" rel="editunite_vente"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Modifier unité </a></li>'."', '0', '[-1-]', '0', '0', 'Attente de validation',NULL,'".'nA'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier unité ' </li>";}
      // Action Task 341 - 'Valider unité'
      if(!$result_action_519 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_341, '7363022ed5ad047bfe86d3de4b75b1f4', 'Valider unité','unites_vente', NULL, '".'<li><a href="#" class="this_exec" data="%id%" rel="validunite_vente"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Valider unité</a></li>'."', '0', '[-1-]', '0', '1', 'Attente de validation',NULL,'".'nA'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider unité' </li>";}
      // Action Task 341 - 'Désactiver unité'
      if(!$result_action_520 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_341, 'ec77eb95736c27bfc269cbffc8e113f1', 'Désactiver unité','unites_vente', NULL, '".'<li><a href="#" class="this_exec" data="%id%" rel="validunite_vente"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Désactiver unité</a></li>'."', '0', '[-1-]', '1', '0', 'Valide',NULL,'".'nA'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver unité' </li>";}
  //Task 'addunite_vente' 'ajouter une unité'
  if(!$result_task_342 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addunite_vente', $result_insert_modul, 'addunite_vente','produits/settings/unites_vente', '1', 'ajouter une unité', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'ajouter une unité' </li>";}
      // Action Task 342 - 'ajouter une unité'
      if(!$result_action_521 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_342, '3a5e8dfe211121eda706f8b6d548d111', 'ajouter une unité','addunite_vente', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation',NULL,'".'nA'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'ajouter une unité' </li>";}
  //Task 'editunite_vente' 'Modifier une unité'
  if(!$result_task_343 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editunite_vente', $result_insert_modul, 'editunite_vente','produits/settings/unites_vente', '1', 'Modifier une unité', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier une unité' </li>";}
      // Action Task 343 - 'Modifier une unité'
      if(!$result_action_522 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_343, '9b7a578981de699286376903e96bc3c7', 'Modifier une unité','editunite_vente', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation',NULL,'".'nA'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier une unité' </li>";}
  //Task 'validunite_vente' 'Valider une unité'
  if(!$result_task_344 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validunite_vente', $result_insert_modul, 'validunite_vente','produits/settings/unites_vente', '1', 'Valider une unité', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider une unité' </li>";}
      // Action Task 344 - 'Valider une unité'
      if(!$result_action_523 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_344, '62355588366c13ddbadc7a7ca1d226ad', 'Valider une unité','validunite_vente', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation',NULL,'".'nA'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider une unité' </li>";}
  //Task 'deleteunite_vente' 'Supprimer une unité'
  if(!$result_task_345 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteunite_vente', $result_insert_modul, 'deleteunite_vente','produits/settings/unites_vente', '1', 'Supprimer une unité', 'cogs', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer une unité' </li>";}
      // Action Task 345 - 'Supprimer une unité'
      if(!$result_action_524 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_345, 'e5f53a3aaa324415d781156396938101', 'Supprimer une unité','deleteunite_vente', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente de validation',NULL,'".'nA'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer une unité' </li>";}
