<?php 
//Export Module 'users' Date: 13-10-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('users', 'Utilisateurs','users','users_sys','user',NULL,'0', '0', '[-1-2-3-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'users' </li>";}
  //Task 'user' 'Utilisateurs'
  if(!$result_task_592 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('user', $result_insert_modul, 'user','users', '1', 'Utilisateurs', 'users', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Utilisateurs' </li>";}
      // Action Task 592 - 'Utilisateurs'
      if(!$result_action_889 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_592, '56de23d30d6c54297c8d9772cd3c7f57', 'Utilisateurs','user', NULL, '".NULL."', '1', '-1-2-3-', '1', '0', 'Actif','success','".'<span class="label label-sm label-success">Actif</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Utilisateurs' </li>";}
      // Action Task 592 - 'Editer Utilisateur'
      if(!$result_action_890 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_592, 'e656756fb7b39a4e6ddcabca75ff2970', 'Editer Utilisateur','user', 'this_url', '".'<li><a href="#" class="this_url" redi="user" data="%id%" rel="edituser" >
     <i class="ace-icon fa fa-pencil bigger-100"></i> Editer compte
   </a></li>'."', '0', '-1-2-3-', '1', '0', 'Actif','success','".'<span class="label label-sm label-success">Actif</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Utilisateur' </li>";}
      // Action Task 592 - 'Permissions'
      if(!$result_action_891 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_592, 'c073a277957ca1b9f318ac3902555708', 'Permissions','user', 'this_url', '".'<li><a href="#" class="this_url" redi="user" data="%id%" rel="rules"  >
     <i class="ace-icon fa fa-key bigger-100"></i> Permission compte
    </a></li>'."', '0', '-1-2-3-', '1', '0', 'Actif','success','".'<span class="label label-sm label-success">Actif</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Permissions' </li>";}
      // Action Task 592 - 'Désactiver compte'
      if(!$result_action_892 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_592, 'c51499ddf7007787c4434661c658bbd1', 'Désactiver compte','user', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="activeuser" ><i class="ace-icon fa fa-lock bigger-100"></i> Désactiver utilisateur</a></li>'."', '0', '-1-3-', '1', '0', 'Actif','success','".'<span class="label label-sm label-success">Actif</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver compte' </li>";}
      // Action Task 592 - 'Supprimer utilisateur'
      if(!$result_action_893 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_592, '10096b6f54456bcfc85081523ee64cf6', 'Supprimer utilisateur','user', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="delete_user" ><i class="ace-icon fa fa-trash red bigger-100"></i> Supprimer utilisateur</a></li>'."', '0', '-1-2-3-', '1', '0', 'Actif','success','".'<span class="label label-sm label-success">Actif</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer utilisateur' </li>";}
      // Action Task 592 - 'Editer Utilisateur'
      if(!$result_action_894 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_592, 'a0999cbed820aff775adf27276ee54a4', 'Editer Utilisateur','user', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="edituser" ><i class="ace-icon fa fa-users bigger-100"></i> Editer compte</a></li>'."', '0', '-1-2-3-', '0', '0', 'Attente Validation','danger','".'<span class="label label-sm label-danger">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Utilisateur' </li>";}
      // Action Task 592 - 'Activer compte'
      if(!$result_action_895 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_592, '9aa6877656339ddff2478b20449a924b', 'Activer compte','user', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="activeuser" ><i class="ace-icon fa fa-unlock bigger-100"></i> Activer utilisateur</a></li>'."', '0', '-1-2-3-', '0', '1', 'Attente Validation','danger','".'<span class="label label-sm label-danger">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Activer compte' </li>";}
      // Action Task 592 - 'Utilisateurs'
      if(!$result_action_896 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_592, 'f4c79bb797b92dfa826b51a44e3171af', 'Utilisateurs','user', NULL, '".NULL."', '0', '-1-2-3-', '0', '1', 'Attente Validation','danger','".'<span class="label label-sm label-danger">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Utilisateurs' </li>";}
      // Action Task 592 - 'Utilisateur Archivé'
      if(!$result_action_897 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_592, 'd7f7afd70a297e5c239f6cf271138390', 'Utilisateur Archivé','user', NULL, '".'dddd'."', '0', '-1-2-3-', '2', '0', 'Archivé','inverse','".'<span class="label label-sm label-inverse">Archivé</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Utilisateur Archivé' </li>";}
      // Action Task 592 - 'Permissions'
      if(!$result_action_898 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_592, '17c98287fb82388423e04d24404cf662', 'Permissions','rules', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="rules"  ><i class="ace-icon fa fa-lock bigger-100"></i> Permissions</a></li>'."', '0', '[-1-]', '0', '1', 'Attente activation','danger','".'<span class="label label-sm label-danger">Attente activation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Permissions' </li>";}
      // Action Task 592 - 'Historique session'
      if(!$result_action_909 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_592, '2c1c5556f30585c5b7c93fbbeaa98595', 'Historique session','history', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="history"  ><i class="ace-icon fa fa-clock-o blue bigger-100"></i> Historique session</a></li>'."', '0', '[-1-3-]', '1', '0', 'Compte Active','success','".'<span class="label label-sm label-success">Compte Active</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Historique session' </li>";}
      // Action Task 592 - 'Liste Activitées'
      if(!$result_action_910 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_592, '7fd4ca84d162b70d3a4f0bad73e0e4b3', 'Liste Activitées','activities', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="activities"  ><i class="ace-icon fa fa-exchange blue bigger-100"></i> Liste Activitées</a></li>'."', '0', '[-1-3-]', '1', '0', 'Compte Actif','success','".'<span class="label label-sm label-success">Compte Actif</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Liste Activitées' </li>";}
  //Task 'adduser' 'Ajouter Utilisateur'
  if(!$result_task_593 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('adduser', $result_insert_modul, 'adduser','users', '1', 'Ajouter Utilisateur', NULL, '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Utilisateur' </li>";}
      // Action Task 593 - 'Ajouter Utilisateurs'
      if(!$result_action_899 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_593, 'df91a8e6f8ee2cde64495fc0cc7d6c6f', 'Ajouter Utilisateurs','adduser', NULL, '".NULL."', '1', '-1-2-', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Utilisateurs' </li>";}
  //Task 'edituser' 'Editer compte utilisateur'
  if(!$result_task_594 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('edituser', $result_insert_modul, 'edituser','users', '1', 'Editer compte utilisateur', NULL, '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer compte utilisateur' </li>";}
      // Action Task 594 - 'Editer Utilisateurs'
      if(!$result_action_900 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_594, '2bb46b52eab9eecbdbba35605da07234', 'Editer Utilisateurs','edituser', NULL, '".NULL."', '1', '-1-2-', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Utilisateurs' </li>";}
  //Task 'rules' 'Permission Utilisateur'
  if(!$result_task_595 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('rules', $result_insert_modul, 'rules','users', '1', 'Permission Utilisateur', 'users', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Permission Utilisateur' </li>";}
      // Action Task 595 - 'Permission'
      if(!$result_action_901 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_595, '3f59a1326df27378304e142ab3bec090', 'Permission','rules', NULL, '".NULL."', '1', '-1-2-', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Permission' </li>";}
  //Task 'delete_user' 'Supprimer utilisateur'
  if(!$result_task_596 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('delete_user', $result_insert_modul, 'delete_user','users', '1', 'Supprimer utilisateur', 'trash', '1', '0', '0','exec', 'null')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer utilisateur' </li>";}
      // Action Task 596 - 'Supprimer utilisateur'
      if(!$result_action_902 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_596, 'b919571c88d036f8889742a81a4f41fd', 'Supprimer utilisateur','delete_user', NULL, '".NULL."', '1', '[-1-]', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer utilisateur' </li>";}
  //Task 'compte' 'Details profile utilisateur'
  if(!$result_task_597 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('compte', $result_insert_modul, 'compte','users', '1', 'Details profile utilisateur', NULL, '1', '1', '0','profil', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Details profile utilisateur' </li>";}
      // Action Task 597 - 'Compte utilisateur'
      if(!$result_action_903 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_597, '38f89764a26e39ce029cd3132c12b2a5', 'Compte utilisateur','compte', NULL, '".NULL."', '1', '[-1-]', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Compte utilisateur' </li>";}
  //Task 'activeuser' 'Activer utilisateur'
  if(!$result_task_598 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('activeuser', $result_insert_modul, 'activeuser','users', '1', 'Activer utilisateur', 'unlock', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Activer utilisateur' </li>";}
      // Action Task 598 - 'Activer utilisateur'
      if(!$result_action_904 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_598, 'f988a608f35a0bc551cb038b1706d207', 'Activer utilisateur','activeuser', NULL, '".NULL."', '1', '[-1-]', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Activer utilisateur' </li>";}
  //Task 'archiv_user' 'Désactiver l''utilisateur'
  if(!$result_task_599 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('archiv_user', $result_insert_modul, 'archiv_user','users', '1', 'Désactiver l''utilisateur', 'ban', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Désactiver l''utilisateur' </li>";}
      // Action Task 599 - 'Désactiver l''utilisateur'
      if(!$result_action_905 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_599, 'b7b3a09fdd73a5b0a3e5ed8a2828f548', 'Désactiver l''utilisateur','archiv_user', NULL, '".NULL."', '1', '[-1-]', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver l''utilisateur' </li>";}
  //Task 'changepass' 'Changer le mot de passe'
  if(!$result_task_600 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('changepass', $result_insert_modul, 'changepass','users', '1', 'Changer le mot de passe', 'cogs', '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Changer le mot de passe' </li>";}
      // Action Task 600 - 'Changer le mot de passe'
      if(!$result_action_906 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_600, '0d374b7e2fe21a2e2641c092a3c7f2e9', 'Changer le mot de passe','changepass', NULL, '".NULL."', '1', '[-1-]', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Changer le mot de passe' </li>";}
  //Task 'history' 'History'
  if(!$result_task_601 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('history', $result_insert_modul, 'history','users', '1', 'History', 'users', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'History' </li>";}
      // Action Task 601 - 'History'
      if(!$result_action_907 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_601, '6f642ee30722158f0318653b9113b887', 'History','history', NULL, '".NULL."', '1', '[-1-]', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'History' </li>";}
  //Task 'activities' 'Activities'
  if(!$result_task_602 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('activities', $result_insert_modul, 'activities','users', '1', 'Activities', 'users', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Activities' </li>";}
      // Action Task 602 - 'Activities'
      if(!$result_action_908 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_602, 'cc907fac13631903d129c137d671d718', 'Activities','activities', NULL, '".NULL."', '1', '[-1-]', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Activities' </li>";}
