<?php 
//Export Module 'villes' Date: 15-09-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('villes', 'Gestion Villes','Systeme/settings/villes','ref_villes','villes','Systeme','1', '0', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'villes' </li>";}
  //Task 'villes' 'Gestion Villes'
  if(!$result_task_89 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('villes', $result_insert_modul, 'villes','Systeme/settings/villes', '1', 'Gestion Villes', 'building', '1', '0', '0','list', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion Villes' </li>";}
      // Action Task 89 - 'Gestion Villes'
      if(!$result_action_114 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_89, '2c3b01c696ff401a2ac9ffedb7a06e4a', 'Gestion Villes','villes', NULL, '".NULL."', '1', '[-1-]', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion Villes' </li>";}
      // Action Task 89 - 'Editer Ville'
      if(!$result_action_119 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_89, 'b9649163b368f863a0e8036f11cd81ae', 'Editer Ville','villes', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editville"  ><i class="ace-icon fa fa-pencil bigger-100"></i> Editer Ville</a></li>'."', '0', '[-1-]', '0', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Ville' </li>";}
      // Action Task 89 - 'Editer Ville'
      if(!$result_action_121 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_89, '89dec6dabcb210cdb9dd28bbef90d43e', 'Editer Ville','villes', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editville"  ><i class="ace-icon fa fa-pencil bigger-100"></i> Editer Ville</a></li>'."', '0', '[-1-]', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Ville' </li>";}
      // Action Task 89 - 'Valider Ville'
      if(!$result_action_602 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_89, '4a2edbdcbda34c9d3d1e6abe73643b37', 'Valider Ville','validville', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validville"  ><i class="ace-icon fa fa-lock bigger-100"></i> Valider Ville</a></li>'."', '0', '[-1-]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Ville' </li>";}
      // Action Task 89 - 'Désactiver Ville'
      if(!$result_action_603 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_89, '0c8ad6595a4516be83ba5a9cdb7ea9a1', 'Désactiver Ville','validville', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validville"  ><i class="ace-icon fa fa-unlock bigger-100"></i> Désactiver Ville</a></li>'."', '0', '[-1-]', '1', '0', 'Ville Validée','success','".'<span class="label label-sm label-success">Ville Validée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Désactiver Ville' </li>";}
  //Task 'addville' 'Ajouter ville'
  if(!$result_task_90 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addville', $result_insert_modul, 'addville','Systeme/settings/villes', '1', 'Ajouter ville', NULL, '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter ville' </li>";}
      // Action Task 90 - 'Ajouter ville'
      if(!$result_action_115 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_90, 'e152b9052d3dcfcac593489dbdc0f61c', 'Ajouter ville','addville', NULL, '".NULL."', '1', '[-1-2-]', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter ville' </li>";}
  //Task 'editville' 'Editer Ville'
  if(!$result_task_91 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editville', $result_insert_modul, 'editville','Systeme/settings/villes', '1', 'Editer Ville', NULL, '1', '0', '0','form', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer Ville' </li>";}
      // Action Task 91 - 'Editer Ville'
      if(!$result_action_116 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_91, '3107e0cd0e0df14c4e94aa088e4457d7', 'Editer Ville','editville', NULL, '".NULL."', '1', '[-1-2-]', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Ville' </li>";}
  //Task 'deleteville' 'Supprimer Ville'
  if(!$result_task_92 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deleteville', $result_insert_modul, 'deleteville','Systeme/settings/villes', '1', 'Supprimer Ville', NULL, '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Ville' </li>";}
      // Action Task 92 - 'Supprimer Ville'
      if(!$result_action_117 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_92, 'da79d9214ed5819d7f4f1e3070629a3d', 'Supprimer Ville','deleteville', NULL, '".NULL."', '1', '[-1-]', '1', '0', NULL,NULL,'".NULL."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Ville' </li>";}
  //Task 'validville' 'Valider Ville'
  if(!$result_task_423 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validville', $result_insert_modul, 'validville','Systeme/settings/villes', '1', 'Valider Ville', 'lock', '1', '0', '0','exec', '[-1-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Ville' </li>";}
      // Action Task 423 - 'Valider Ville'
      if(!$result_action_601 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_423, 'fe03a68d17c62ff2c27329573a1b3550', 'Valider Ville','validville', NULL, '".NULL."', '0', '[-1-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Ville' </li>";}
