<?php 
//Export Module 'visites' Date: 24-10-2019
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('visites', 'Gestion des Visites','visites/main','visites','visites',NULL,'0', '0', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'visites' </li>";}
  //Task 'visites' 'Gestion des Visites'
  if(!$result_task_1069 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('visites', $result_insert_modul, 'visites','visites/main', '1', 'Gestion des Visites', 'archive', '1', '0', '0','list', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion des Visites' </li>";}
      // Action Task 1069 - 'Gestion des Visites'
      if(!$result_action_1824 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1069, '86b473966194ba5a0a880f31e842354f', 'Gestion des Visites','visites', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion des Visites' </li>";}
      // Action Task 1069 - 'Modifier Visite'
      if(!$result_action_1829 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1069, 'f189c9ad1168c07afab7f10cba3bb237', 'Modifier Visite','editvisite', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="editvisite"  ><i class="ace-icon fa fa-pencil-square-o green bigger-100"></i> Modifier Visite</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Visite' </li>";}
      // Action Task 1069 - 'Valider Visite'
      if(!$result_action_1830 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1069, '8b72e0dfacecc42eba54279a70d5bb18', 'Valider Visite','validvisite', 'this_exec', '".'<li><a href="#" class="this_exec" data="%id%" rel="validvisite"  ><i class="ace-icon fa fa-check-square-o green  bigger-100"></i> Valider Visite</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '0', '1', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Visite' </li>";}
      // Action Task 1069 - 'Détails Visite'
      if(!$result_action_1831 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1069, '0f934fb51b4a5b0b15e8a44da7acf56b', 'Détails Visite','detailsvisite', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsvisite"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails Visite</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Visite' </li>";}
      // Action Task 1069 - 'Détails Visite'
      if(!$result_action_1832 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1069, '9e461cb77a8fcad73338db40d27c76f0', 'Détails Visite','detailsvisite', 'this_url', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsvisite"  ><i class="ace-icon fa fa-eye bigger-100"></i> Détails Visite</a></li>'."', '0', '[-1-2-3-5-4-7-6-]', '1', '0', 'Visite Validée','success','".'<span class="label label-sm label-success">Visite Validée</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Visite' </li>";}
  //Task 'addvisites' 'Ajouter Visite'
  if(!$result_task_1070 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addvisites', $result_insert_modul, 'addvisites','visites/main', '1', 'Ajouter Visite', 'calendar-check', '1', '0', '0','formadd', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Visite' </li>";}
      // Action Task 1070 - 'Ajouter Visite'
      if(!$result_action_1825 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1070, '3f80d111e9d9e0280a17cea823143bba', 'Ajouter Visite','addvisites', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Visite' </li>";}
  //Task 'deletevisites' 'Supprimer Visite'
  if(!$result_task_1071 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletevisites', $result_insert_modul, 'deletevisites','visites/main', '1', 'Supprimer Visite', 'trash', '1', '0', '0','exec', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Visite' </li>";}
      // Action Task 1071 - 'Supprimer Visite'
      if(!$result_action_1826 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1071, 'a8ab4a6c4130240b77b76e7d3c990ae0', 'Supprimer Visite','deletevisites', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Visite' </li>";}
  //Task 'editvisite' 'Modifier Visite'
  if(!$result_task_1072 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editvisite', $result_insert_modul, 'editvisite','visites/main', '1', 'Modifier Visite', 'fa-check-square-o green', '1', '0', '0','formedit', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Modifier Visite' </li>";}
      // Action Task 1072 - 'Modifier Visite'
      if(!$result_action_1827 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1072, '3b9f25b56230670782b7bec53cfa3a71', 'Modifier Visite','editvisite', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Modifier Visite' </li>";}
  //Task 'detailsvisite' 'Détails Visite'
  if(!$result_task_1073 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsvisite', $result_insert_modul, 'detailsvisite','visites/main', '1', 'Détails Visite', 'eye', '1', '0', '0','profil', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails Visite' </li>";}
      // Action Task 1073 - 'Détails Visite'
      if(!$result_action_1828 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1073, '33f2ce6b94e9d678afe5712a1a32efdb', 'Détails Visite','detailsvisite', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Visite' </li>";}
  //Task 'validvisite' 'Valider Visite'
  if(!$result_task_1077 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('validvisite', $result_insert_modul, 'validvisite','visites/main', '1', 'Valider Visite', 'trash', '1', '0', '0','exec', '[-1-2-3-5-4-7-6-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Valider Visite' </li>";}
      // Action Task 1077 - 'Valider Visite'
      if(!$result_action_1836 = $db->Query("INSERT INTO task_action (appid, idf, descrip, app, mode_exec, code, type, service, etat_line, notif, etat_desc, message_class, message_etat)VALUES($result_task_1077, 'ff5b8d64b126138ee5e8a3270d4bd16a', 'Valider Visite','validvisite', NULL, '".NULL."', '1', '[-1-2-3-5-4-7-6-]', '0', '0', 'Attente Validation','warning','".'<span class="label label-sm label-warning">Attente Validation</span>'."')")){$this->error = false; $this->log .= "<li> Error Import task_action 'Valider Visite' </li>";}
