<?php 
//Export Module 'vsat' Date: 13-06-2017
global $db;
if(!$result_insert_modul = $db->Query("insert into modul (modul, description, rep_modul, tables, app_modul, modul_setting, is_setting, etat, services)values('vsat', 'Gestion VSAT','vsat','vsat','vsat',NULL,'0', '0', '[-1-2-17-]')")){$this->error = false; $this->log .= "<li> Error Import Modul 'vsat' </li>";}
  //Task 'vsat' 'Gestion VSAT'
  if(!$result_task_302 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('vsat', $result_insert_modul, 'vsat','VSAT', '1', 'Gestion VSAT', 'vsat', '1', '0', '0','list', '[-1-2-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Gestion VSAT' </li>";}
      // Action Task 302 - 'Gestion VSAT'
      if(!$result_action_451 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_302, '97dfd39e0b376f443f223834a2894e60', 'Gestion VSAT', '".NULL."', '1', '[-1-2-17-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Gestion VSAT' </li>";}
      // Action Task 302 - 'Editer Station VSAT'
      if(!$result_action_452 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_302, '19b70e2f6796adc757e628fa963c6f5f', 'Editer Station VSAT', '".'<li><a href="#" class="this_url" data="%id%" rel="editvsat"  ><i class="ace-icon fa fa-pencil bigger-100"></i> Editer Station VSAT</a></li>'."', '0', '[-1-17-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Station VSAT' </li>";}
      // Action Task 302 - 'Détails Station VSAT'
      if(!$result_action_453 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_302, 'b6d85ff52f1644138995e1c71dacca0f', 'Détails Station VSAT', '".'<li><a href="#" class="this_url" data="%id%" rel="detailsvsat"  ><i class="ace-icon fa fa-cogs bigger-100"></i> Détails Station VSAT</a></li>'."', '0', '[-1-]', '0', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Station VSAT' </li>";}
  //Task 'addvsat' 'Ajouter Station VSAT'
  if(!$result_task_303 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('addvsat', $result_insert_modul, 'addvsat','VSAT', '1', 'Ajouter Station VSAT', NULL, '1', '0', '0','form', 'null')")){$this->error = false; $this->log .= "<li> Error Import task 'Ajouter Station VSAT' </li>";}
      // Action Task 303 - 'Ajouter Station VSAT'
      if(!$result_action_454 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_303, '541c53713ebcf396070f27a375d8edff', 'Ajouter Station VSAT', '".NULL."', '1', '[-1-2-17-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Ajouter Station VSAT' </li>";}
  //Task 'editvsat' 'Editer Station VSAT'
  if(!$result_task_304 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('editvsat', $result_insert_modul, 'editvsat','VSAT', '1', 'Editer Station VSAT', NULL, '1', '0', '0','form', '[-1-2-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Editer Station VSAT' </li>";}
      // Action Task 304 - 'Editer Station VSAT'
      if(!$result_action_455 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_304, '064a594bbc69585173c5a4f0bef8536a', 'Editer Station VSAT', '".NULL."', '1', '[-1-2-17-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Editer Station VSAT' </li>";}
  //Task 'deletevsat' 'Supprimer Station VSAT'
  if(!$result_task_305 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('deletevsat', $result_insert_modul, 'deletevsat','VSAT', '1', 'Supprimer Station VSAT', NULL, '1', '0', '0','exec', '[-1-2-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Supprimer Station VSAT' </li>";}
      // Action Task 305 - 'Supprimer Station VSAT'
      if(!$result_action_456 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_305, 'c01ec9146fea7a8a94bf3afa068f48b3', 'Supprimer Station VSAT', '".NULL."', '1', '[-1-2-17-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Supprimer Station VSAT' </li>";}
  //Task 'detailsvsat' 'Détails Station VSAT'
  if(!$result_task_306 = $db->Query("INSERT INTO task (app, modul, file, rep, session, dscrip, sbclass, ajax, app_sys, etat, type_view, services)VALUES('detailsvsat', $result_insert_modul, 'detailsvsat','vsat', '1', 'Détails Station VSAT', 'cogs', '1', '0', '0','profil', '[-1-2-17-]')")){$this->error = false; $this->log .= "<li> Error Import task 'Détails Station VSAT' </li>";}
      // Action Task 306 - 'Détails Station VSAT'
      if(!$result_action_457 = $db->Query("INSERT INTO task_action (appid, idf, descrip, code, type, service, etat_line, notif, etat_desc)VALUES($result_task_306, '02ca060882743822d7664933f2893bad', 'Détails Station VSAT', '".NULL."', '1', '[-1-]', '1', '0', NULL)")){$this->error = false; $this->log .= "<li> Error Import task_action 'Détails Station VSAT' </li>";}
